export enum tabsValues {
  SHOPS = 'SHOPS',
  STOCK_REPORT = 'STOCK_REPORT',
  GOODS_DAYS_REPORT = 'GOODS_DAYS_REPORT',
  INVENTORY = 'INVENTORY',
  PPC = 'PPC',
  INVENTORY_SHIPMENTS = 'INVENTORY_SHIPMENTS',
}
