export const filtersFields: string[] = [
  'asin',
  'skuByClient',
  'amazonTitle',
  'id',
  'status',
  'amount',
  'client',
  'storekeeper',
  'buyer',
  'partialPaymentAmountRmb',
  'totalPrice',
  'weight',
  'createdAt',
  'updatedAt',
]
