import { action, observable } from 'mobx'

export const observerConfig = {
  showRequestForm: observable,
  showConfirmModal: observable,
  showRequestDetailModal: observable,
  showConfirmWithCommentModal: observable,
  isAcceptedProposals: observable,
  openModal: observable,
  showRequestDesignerResultClientModal: observable,
  showConfirmWorkResultFormModal: observable,
  showMainRequestResultModal: observable,
  showRequestResultModal: observable,
  selectedIndex: observable,
  selectedRequests: observable,
  researchIdToRemove: observable,
  currentRequestDetails: observable,
  curProposal: observable,
  searchRequests: observable,
  requestFormSettings: observable,
  isRequestsAtWork: observable,
  onlyWaitedProposals: observable,
  acceptProposalResultSetting: observable,
  statusGroup: observable,
  dataGridApi: observable,

  onClickChangeCatigory: action.bound,
  loadData: action.bound,
  onClickAddBtn: action.bound,
  onClickEditBtn: action.bound,
  onSubmitEditCustomSearchRequest: action.bound,
  onSubmitCreateCustomSearchRequest: action.bound,
  editCustomSearchRequest: action.bound,
  createCustomSearchRequest: action.bound,
  onClickRemoveBtn: action.bound,
  onToggleUploadedToListing: action.bound,
  onSelectRequest: action.bound,
  onClickTableRow: action.bound,
  handleListingFilters: action.bound,
  getRequestDetail: action.bound,
  handleOpenRequestDetailModal: action.bound,
  getRequestProposals: action.bound,
  handleClickResultBtn: action.bound,
  onClickOpenInNewTab: action.bound,
  onDeleteRequest: action.bound,
  onClickCancelBtn: action.bound,
  toPublishRequest: action.bound,
  onClickPublishBtn: action.bound,
  onRecoverRequest: action.bound,
  onClickAbortBtn: action.bound,
  onSubmitAbortRequest: action.bound,
  onMarkAsCompletedRequest: action.bound,
  onClickMarkAsCompletedBtn: action.bound,
  onSendInForRework: action.bound,
  onClickProposalResultAccept: action.bound,
  onClickProposalResultAcceptForm: action.bound,
  handleChangeRequestComment: action.bound,
}
