/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TestSwagger);
  }
}(this, function(expect, TestSwagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TestSwagger.ApiV1BatchesBatch();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiV1BatchesBatch', function() {
    it('should create an instance of ApiV1BatchesBatch', function() {
      // uncomment below and update the code to test ApiV1BatchesBatch
      //var instane = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be.a(TestSwagger.ApiV1BatchesBatch);
    });

    it('should have the property _id (base name: "_id")', function() {
      // uncomment below and update the code to test the property _id
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

    it('should have the property humanFriendlyId (base name: "humanFriendlyId")', function() {
      // uncomment below and update the code to test the property humanFriendlyId
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

    it('should have the property shipId (base name: "shipId")', function() {
      // uncomment below and update the code to test the property shipId
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

    it('should have the property attachedDocuments (base name: "attachedDocuments")', function() {
      // uncomment below and update the code to test the property attachedDocuments
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

    it('should have the property finalWeightAsOneBox (base name: "finalWeightAsOneBox")', function() {
      // uncomment below and update the code to test the property finalWeightAsOneBox
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

    it('should have the property finalWeightSumEachBoxAmount (base name: "finalWeightSumEachBoxAmount")', function() {
      // uncomment below and update the code to test the property finalWeightSumEachBoxAmount
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

    it('should have the property storekeeperId (base name: "storekeeperId")', function() {
      // uncomment below and update the code to test the property storekeeperId
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

    it('should have the property createdById (base name: "createdById")', function() {
      // uncomment below and update the code to test the property createdById
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new TestSwagger.ApiV1BatchesBatch();
      //expect(instance).to.be();
    });

  });

}));
