/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TestSwagger);
  }
}(this, function(expect, TestSwagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TestSwagger.InlineResponse2008();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2008', function() {
    it('should create an instance of InlineResponse2008', function() {
      // uncomment below and update the code to test InlineResponse2008
      //var instane = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be.a(TestSwagger.InlineResponse2008);
    });

    it('should have the property _id (base name: "_id")', function() {
      // uncomment below and update the code to test the property _id
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property humanFriendlyId (base name: "humanFriendlyId")', function() {
      // uncomment below and update the code to test the property humanFriendlyId
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property shipId (base name: "shipId")', function() {
      // uncomment below and update the code to test the property shipId
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property attachedDocuments (base name: "attachedDocuments")', function() {
      // uncomment below and update the code to test the property attachedDocuments
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property finalWeightAsOneBox (base name: "finalWeightAsOneBox")', function() {
      // uncomment below and update the code to test the property finalWeightAsOneBox
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property finalWeightSumEachBoxAmount (base name: "finalWeightSumEachBoxAmount")', function() {
      // uncomment below and update the code to test the property finalWeightSumEachBoxAmount
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property boxes (base name: "boxes")', function() {
      // uncomment below and update the code to test the property boxes
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property calculationMethod (base name: "calculationMethod")', function() {
      // uncomment below and update the code to test the property calculationMethod
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property volumeWeightDivide (base name: "volumeWeightDivide")', function() {
      // uncomment below and update the code to test the property volumeWeightDivide
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property finalWeight (base name: "finalWeight")', function() {
      // uncomment below and update the code to test the property finalWeight
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property storekeeper (base name: "storekeeper")', function() {
      // uncomment below and update the code to test the property storekeeper
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property lastModifiedBy (base name: "lastModifiedBy")', function() {
      // uncomment below and update the code to test the property lastModifiedBy
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new TestSwagger.InlineResponse2008();
      //expect(instance).to.be();
    });

  });

}));
