export const permissionsKeys = {
  supervisor: {
    SHOW_PAYMENTS_SUPERVISOR: 'SHOW_PAYMENTS_SUPERVISOR',
    SHOW_USERS_SUPERVISOR: 'SHOW_USERS_SUPERVISOR',
    SHOW_PRODUCTS_SUPERVISOR: 'SHOW_PRODUCTS_SUPERVISOR',
    SHOW_VAC_PRODUCTS_SUPERVISOR: 'SHOW_VAC_PRODUCTS_SUPERVISOR',
    SHOW_SETTINGS_SUPERVISOR: 'SHOW_SETTINGS_SUPERVISOR',

    SHOW_VAC_BY_RES_SUPERVISOR: 'SHOW_VAC_BY_RES_SUPERVISOR',
    SHOW_VAC_BY_CLIENT_SUPERVISOR: 'SHOW_VAC_BY_CLIENT_SUPERVISOR',
    SHOW_DASHOBARD_SUPERVISOR: 'SHOW_DASHOBARD_SUPERVISOR',
    SHOW_CHAT_SUPERVISOR: 'SHOW_CHAT_SUPERVISOR',
  },

  buyer: {
    SHOW_PAYMENTS_BUYER: 'SHOW_PAYMENTS_BUYER',
    SHOW_USERS_BUYER: 'SHOW_USERS_BUYER',

    SHOW_VAC_ORDERS_BUYER: 'SHOW_VAC_ORDERS_BUYER',
    SHOW_ORDERS_BUYER: 'SHOW_ORDERS_BUYER',

    SHOW_ORDERS_CLOSED_AND_CANCELED_BUYER: 'SHOW_ORDERS_CLOSED_AND_CANCELED_BUYER',
    SHOW_ORDERS_CONFIRMATION_REQUIRED_BUYER: 'SHOW_ORDERS_CONFIRMATION_REQUIRED_BUYER',
    SHOW_ORDERS_INBOUND_BUYER: 'SHOW_ORDERS_INBOUND_BUYER',
    SHOW_ORDERS_NEED_TRACK_NUMBER_BUYER: 'SHOW_ORDERS_NEED_TRACK_NUMBER_BUYER',
    SHOW_ORDERS_NOT_PAID_BUYER: 'SHOW_ORDERS_NOT_PAID_BUYER',
    SHOW_ORDERS_READY_FOR_PAYMENT_BUYER: 'SHOW_ORDERS_READY_FOR_PAYMENT_BUYER',
    SHOW_ORDERS_PARTIALLY_PAID_BUYER: 'SHOW_ORDERS_PARTIALLY_PAID_BUYER',
    SHOW_PENDING_ORDERS_BUYER: 'SHOW_PENDING_ORDERS_BUYER',

    SHOW_PRODUCTS_BUYER: 'SHOW_PRODUCTS_BUYER',
    SHOW_VAC_BY_CLIENT_BUYER: 'SHOW_VAC_BY_CLIENT_BUYER',
    SHOW_VAC_BY_SUP_BUYER: 'SHOW_VAC_BY_SUP_BUYER',
    SHOW_DASHBOARD_BUYER: 'SHOW_DASHBOARD_BUYER',
    SHOW_CHAT_BUYER: 'SHOW_CHAT_BUYER',

    SHOW_NOTIFICATIONS_BUYER: 'SHOW_NOTIFICATIONS_BUYER',
  },
  storekeeper: {
    SHOW_PAYMENTS_STOREKEEPER: 'SHOW_PAYMENTS_STOREKEEPER',
    SHOW_USERS_STOREKEEPER: 'SHOW_USERS_STOREKEEPER',
    SHOW_BATCHES_STOREKEEPER: 'SHOW_BATCHES_STOREKEEPER',
    SHOW_WAREHOUSE_STOREKEEPER: 'SHOW_WAREHOUSE_STOREKEEPER',
    SHOW_MANAGEMENT_STOREKEEPER: 'SHOW_MANAGEMENT_STOREKEEPER',
    SHOW_MY_TASKS_STOREKEEPER: 'SHOW_MY_TASKS_STOREKEEPER',
    SHOW_DASHBOARD_STOREKEEPER: 'SHOW_DASHBOARD_STOREKEEPER',
    SHOW_CHAT_STOREKEEPER: 'SHOW_CHAT_STOREKEEPER',
  },
  client: {
    SHOW_VACANT_CLIENT: 'SHOW_VACANT_CLIENT',
    SHOW_INVENTORY_CLIENT: 'SHOW_INVENTORY_CLIENT',
    SHOW_REQUESTS_CLIENT: 'SHOW_REQUESTS_CLIENT',

    SHOW_ORDERS_CLIENT: 'SHOW_ORDERS_CLIENT',
    SHOW_PENDING_ORDERS_CLIENT: 'SHOW_PENDING_ORDERS_CLIENT',

    SHOW_WAREHOUSE_CLIENT: 'SHOW_WAREHOUSE_CLIENT',
    SHOW_BATCHES_CLIENT: 'SHOW_BATCHES_CLIENT',
    SHOW_USERS_CLIENT: 'SHOW_USERS_CLIENT',
    SHOW_INTEGRATIONS_CLIENT: 'SHOW_INTEGRATIONS_CLIENT',
    SHOW_USER_SETTINGS_CLIENT: 'SHOW_USER_SETTINGS_CLIENT',
    SHOW_PAYMENTS_CLIENT: 'SHOW_PAYMENTS_CLIENT',
    SHOW_NOTIFICATIONS_CLIENT: 'SHOW_NOTIFICATIONS_CLIENT',
    SHOW_SHOPS_CLIENT: 'SHOW_SHOPS_CLIENT',
    SHOW_FREELANCE_CLIENT: 'SHOW_FREELANCE_CLIENT',
    SHOW_TRADING_SHOPS_CLIENT: 'SHOW_TRADING_SHOPS_CLIENT',
    SHOW_DASHBOARD_CLIENT: 'SHOW_DASHBOARD_CLIENT',
    SHOW_CHAT_CLIENT: 'SHOW_CHAT_CLIENT',

    ideas: {
      SHOW_NEW_IDEAS_CLIENT: 'SHOW_NEW_IDEAS_CLIENT',
      SHOW_ON_CHECKING_IDEAS_CLIENT: 'SHOW_ON_CHECKING_IDEAS_CLIENT',
      SHOW_SEARCH_SUPPLIER_IDEAS_CLIENT: 'SHOW_SEARCH_SUPPLIER_IDEAS_CLIENT',
      SHOW_CREATE_CARD_IDEAS_CLIENT: 'SHOW_CREATE_CARD_IDEAS_CLIENT',
      SHOW_ADD_ASIN_IDEAS_CLIENT: 'SHOW_ADD_ASIN_IDEAS_CLIENT',
      SHOW_REALIZED_IDEAS_CLIENT: 'SHOW_REALIZED_IDEAS_CLIENT',
      SHOW_CLOSED_IDEAS_CLIENT: 'SHOW_CLOSED_IDEAS_CLIENT',
      SHOW_ALL_IDEAS_CLIENT: 'SHOW_ALL_IDEAS_CLIENT',
    },
  },
  researcher: {
    SHOW_PAYMENTS_RESEARCHER: 'SHOW_PAYMENTS_RESEARCHER',
    SHOW_SETTINGS_RESEARCHER: 'SHOW_SETTINGS_RESEARCHER',
    SHOW_USERS_RESEARCHER: 'SHOW_USERS_RESEARCHER',
    SHOW_VAC_REQUESTS_RESEARCHER: 'SHOW_VAC_REQUESTS_RESEARCHER',
    SHOW_REQUESTS_RESEARCHER: 'SHOW_REQUESTS_RESEARCHER',
    SHOW_PRODUCTS_RESEARCHER: 'SHOW_PRODUCTS_RESEARCHER',
    SHOW_DASHBOARD_RESEARCHER: 'SHOW_DASHBOARD_RESEARCHER',
    SHOW_CHAT_RESEARCHER: 'SHOW_CHAT_RESEARCHER',
  },

  freelancer: {
    SHOW_DASHBOARD_FREELANCER: 'SHOW_DASHBOARD_FREELANCER',
    SHOW_USERS_FREELANCER: 'SHOW_USERS_FREELANCER',
    SHOW_PAYMENTS_FREELANCER: 'SHOW_PAYMENTS_FREELANCER',
    SHOW_CHAT_FREELANCER: 'SHOW_CHAT_FREELANCER',

    SHOW_SOURCES_FREELANCER: 'SHOW_SOURCES_FREELANCER',
    SHOW_ANNOUNCEMENTS_FREELANCER: 'SHOW_ANNOUNCEMENTS_FREELANCER',
    SHOW_PROPOSALS_FREELANCER: 'SHOW_PROPOSALS_FREELANCER',
    SHOW_VAC_REQUESTS_FREELANCER: 'SHOW_VAC_REQUESTS_FREELANCER',

    SHOW_NOTIFICATIONS_FREELANCER: 'SHOW_NOTIFICATIONS_FREELANCER',
  },

  shared: {
    GENERAL_NOTIFICATIONS: 'GENERAL_NOTIFICATIONS',
  },
}
