export const RequestType = {
  CUSTOM: 'CUSTOM',
  SEARCH_NICHE: 'SEARCH_NICHE',
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',
}

export const RequestSubType = {
  VACANT: 'VACANT',
  MY: 'MY',
  ASSIGNED_TO_ME: 'ASSIGNED_TO_ME',
  PICKUPED_BY_ME: 'PICKUPED_BY_ME',
  LINKED_TO_ME: 'LINKED_TO_ME',
  ALL: 'ALL',
}
