export const amazonImageUrlPrefix = 'https://images-na.ssl-images-amazon.com/images/I/'
export const amazonImageUrlBigPostfix = '._SL1400_.jpg'
export const amazonImageUrlMiddlePostfix = '._SL120_.jpg'
export const amazonImageUrlSmallPostfix = '._SS64_.jpg'
export const amazonImageUrlPostfix = '.preview.webp'
