import { action, computed, observable } from 'mobx'

export const observerConfig = {
  // Observables
  batches: observable,
  baseBoxesMy: observable,
  destinations: observable,
  uploadedTrackNumber: observable,
  curBox: observable,
  curBoxToMove: observable,
  sourceBoxForBatch: observable,
  storekeepersData: observable,
  modalRedistributeBoxAddNewBox: observable,
  unitsOption: observable,
  curOpenedTask: observable,
  toCancelData: observable,
  showBoxViewModal: observable,
  showBoxMoveToBatchModal: observable,
  showAddBatchModal: observable,
  showAddOrEditHsCodeInBox: observable,
  showEditBoxModal: observable,
  showFullEditBoxModal: observable,
  showMergeBoxModal: observable,
  showRedistributeBoxModal: observable,
  showGroupingBoxesModal: observable,
  showEditBoxModalR: observable,
  showEditMultipleBoxesModal: observable,
  uploadedImages: observable,
  uploadedFiles: observable,
  uploadedTransparencyFiles: observable,

  // Computed properties
  userInfo: computed,
  destinationsFavourites: computed,
  platformSettings: computed,

  // action.bounds
  setDestinationsFavouritesItem: action.bound,
  onTriggerShowEditBoxModalR: action.bound,
  onClickSavePrepId: action.bound,
  onClickSaveStorage: action.bound,
  uploadImageIfNotUploaded: action.bound,
  uploadSharedFieldFile: action.bound,
  onClickSubmitEditMultipleBoxes: action.bound,
  onClickSubmitEditBox: action.bound,
  onClickEditBtn: action.bound,
  getDataToMoveBatch: action.bound,
  moveBox: action.bound,
  setHsCode: action.bound,
  onEditBox: action.bound,
  onClickMergeBtn: action.bound,
  onClickConfirmSplit: action.bound,
  splitBoxes: action.bound,
  onClickConfirmMerge: action.bound,
  mergeBoxes: action.bound,
  onRemoveBoxFromSelected: action.bound,
  onClickSplitBtn: action.bound,
  onModalRedistributeBoxAddNewBox: action.bound,
  onClickSubmitGroupingBoxes: action.bound,
  onClickGroupingBtn: action.bound,
  setDimensions: action.bound,
  onSubmitEditBox: action.bound,
  onSubmitAddBatch: action.bound,
  onSubmitAddOrEditHsCode: action.bound,
  onSubmitMoveBoxToBatch: action.bound,
  setCurrentOpenedBox: action.bound,
  onSubmitCreateBatch: action.bound,
  onTriggerShowEditBoxModal: action.bound,
  onChangeUnitsOption: action.bound,
}
