export const updateBoxWhiteList = [
  'shippingLabel',
  'lengthCmWarehouse',
  'widthCmWarehouse',
  'heightCmWarehouse',
  'weighGrossKgWarehouse',
  'isShippingLabelAttachedByStorekeeper',
  'fbaShipment',
  'images',
  'destinationId',
  'items',
  'storekeeperComment',
  'logicsTariffId',
  'variationTariffId',
  'referenceId',
  'storekeeperTaskComment',
  'trackNumberFile',
  'trackNumberText',
  'upsTrackNumber',
  'fbaNumber',
  'prepId',
  'storage',
]

export const updateManyBoxesWhiteList = [
  '_id',
  'logicsTariffId',
  'fbaShipment',
  'fbaNumber',
  'destinationId',
  'variationTariffId',
  'isShippingLabelAttachedByStorekeeper',
  'items',
]

export const sharedFieldsWhiteList = [
  'barCode',
  'logicsTariffId',
  'shippingLabel',
  'fbaShipment',
  'fbaNumber',
  'destinationId',
  'transparencyFile',
  'variationTariffId',
  'isShippingLabelAttachedByStorekeeper',
  'isTransparencyFileAttachedByTheStorekeeper',
  'isTransparencyFileAlreadyAttachedByTheSupplier',
  'isBarCodeAlreadyAttachedByTheSupplier',
  'isBarCodeAttachedByTheStorekeeper',
]

export const filtersFields = [
  'xid',
  'orderIdsItems',
  'orders',
  'amount',
  'warehouse',
  'client',
  'batchXid',
  'dimansions',
  'action',
  'prepId',
  'orderXid',
  'item',
  'asin',
  'skuByClient',
  'amazonTitle',
  'destination',
  'logicsTariff',
  'redFlags',
  'storage',
  'clientComment',
]
