import { action, observable, override } from 'mobx'

export const observerConfig = {
  isArchive: observable,
  product: observable,
  ordersDataStateToSubmit: observable,
  ideasData: observable,
  sellerBoardDailyData: observable,
  storekeepers: observable,
  destinations: observable,
  ideaId: observable,
  batchesData: observable,
  presetsData: observable,
  receivedFiles: observable,
  paymentMethods: observable,
  hsCodeData: observable,
  curProduct: observable,
  productsToLaunch: observable,
  productVariations: observable,
  selectedProductToLaunch: observable,
  existingProducts: observable,
  selectedRowId: observable,
  yuanToDollarRate: observable,
  platformSettings: observable,
  selectedProduct: observable,
  isTransfer: observable,

  showOrderModal: observable,
  showSuccessModal: observable,
  showCheckPendingOrderFormModal: observable,
  showSetBarcodeModal: observable,
  showSelectionSupplierModal: observable,
  showAddOrEditSupplierModal: observable,
  showSendOwnProductModal: observable,
  showBindInventoryGoodsToStockModal: observable,
  showAddSupplierToIdeaFromInventoryModal: observable,
  showInfoModal: observable,
  showConfirmModal: observable,
  showSetChipValueModal: observable,
  showBarcodeOrHscodeModal: observable,
  showSetFourMonthsStockValueModal: observable,
  showCircularProgressModal: observable,
  showAddSuppliersModal: observable,
  showSetStockUsValueModal: observable,
  showProductLotDataModal: observable,
  showGetFilesModal: observable,
  showEditHSCodeModal: observable,
  productCardModal: observable,
  showProductLaunch: observable,
  showIdeaModal: observable,
  showProductVariationsForm: observable,

  readyImages: observable,
  progressValue: observable,
  showProgress: observable,

  setSelectedProduct: action.bound,
  onSubmitBindStockGoods: action.bound,
  getStockGoodsByFilters: action.bound,
  onDeleteHsCode: action.bound,
  onDeleteBarcode: action.bound,
}
