import { action, computed, observable } from 'mobx'

export const observerConfig = {
  _requestStatus: observable,
  _rowCount: observable,
  _sortModel: observable,
  _densityModel: observable,
  _paginationModel: observable,
  _filterModel: observable,
  _columnVisibilityModel: observable,
  _selectedRows: observable,
  _tableKey: observable,
  _tableData: observable,
  _getMainDataMethod: observable,
  _columnsModel: observable,
  _defaultGetDataMethodOptions: observable,
  _unserverSearchValue: observable,

  requestStatus: computed,
  rowCount: computed,
  sortModel: computed,
  densityModel: computed,
  paginationModel: computed,
  selectedRows: computed,
  tableData: computed,
  getMainDataMethod: computed,
  columnsModel: computed,
  defaultGetDataMethodOptions: computed,
  unserverSearchValue: computed,

  setDataGridState: action.bound,
  getDataGridState: action.bound,
  onChangeSortingModel: action.bound,
  onColumnVisibilityModelChange: action.bound,
  onSelectionModel: action.bound,
  onPaginationModelChange: action.bound,
  onChangeFilterModel: action.bound,
  getMainTableData: action.bound,
  onChangeUnserverSearchValue: action.bound,
  setRequestStatus: action.bound,
}
