import { action, computed, observable } from 'mobx'

export const observerConfig = {
  sortModel: observable,
  densityModel: observable,
  paginationModel: observable,
  filterModel: observable,
  columnVisibilityModel: observable,
  selectedRows: observable,
  tableKey: observable,
  columnsModel: observable,
  pinnedColumns: observable,
  currentSearchValue: observable,
  fieldsForSearch: observable,
  presetsTableData: observable,
  defaultSortModel: observable,
  defaultColumnsModel: observable,
  showPresetsSelect: observable,

  filteredData: computed,
  isSomeFilterOn: computed,

  setDataGridState: action.bound,
  getDataGridState: action.bound,
  onChangeSortingModel: action.bound,
  onColumnVisibilityModelChange: action.bound,
  onSelectionModel: action.bound,
  onPaginationModelChange: action.bound,
  onChangeFilterModel: action.bound,
  onChangeUnserverSearchValue: action.bound,
  handlePinColumn: action.bound,
  handleHideColumns: action.bound,
  onClickResetFilters: action.bound,
  handleCreateTableSettingsPreset: action.bound,
  getTableSettingsPreset: action.bound,
  handleSetPresetActive: action.bound,
  handleDeleteTableSettingsPreset: action.bound,
  handleUpdateTableSettingsPreset: action.bound,
  setSettingsFromActivePreset: action.bound,
  getActivePreset: action.bound,
  handleSetActivePreset: action.bound,
  handleUnsetAllPresets: action.bound,
  getPresetSettingForSave: action.bound,
  checkNestedFields: action.bound,
  onChangeShowPresetsSelect: action.bound,
}
