import { action, observable } from 'mobx'

export const observerConfig = {
  requestStatus: observable,
  rowCount: observable,
  sortModel: observable,
  densityModel: observable,
  paginationModel: observable,
  filterModel: observable,
  columnVisibilityModel: observable,
  selectedRows: observable,
  tableKey: observable,
  tableData: observable,
  getMainDataMethod: observable,
  columnsModel: observable,
  defaultGetDataMethodOptions: observable,
  unserverSearchValue: observable,

  setDataGridState: action.bound,
  getDataGridState: action.bound,
  onChangeSortingModel: action.bound,
  onColumnVisibilityModelChange: action.bound,
  onSelectionModel: action.bound,
  onPaginationModelChange: action.bound,
  onChangeFilterModel: action.bound,
  getMainTableData: action.bound,
  onChangeUnserverSearchValue: action.bound,
  setRequestStatus: action.bound,
  handleHideColumns: action.bound,
}
