export const intervalFields: string[] = [
  'intervalStatusNew',
  'intervalStatusOnCheck',
  'intervalStatusSupplierSearch',
  'intervalStatusSupplierFound',
  'intervalStatusProductCreating',
  'intervalStatusAddingAsin',
  'intervalStatusFinished',
  'intervalsSum',
]

export const filtersFields = [
  'parentProductSkuByClient',
  'parentProductAmazonTitle',
  'parentProductAsin',
  'childProductAmazonTitle',
  'childProductSkuByClient',
  'childProductAsin',
  'title',
  // 'shopId',
  'childProductShopId',
  'parentProductShopId',
  'comments',
  'createdAt',
  'dateStatusOnCheck',
  'suppliers',
  'minlot',
  'productionTerm',
  'dateStatusProductCreating',
  'buyerComment',
  'dateStatusAddingAsin',
  'amount',
  'intervalStatusNew',
  'intervalStatusOnCheck',
  'intervalStatusSupplierSearch',
  'intervalStatusSupplierFound',
  'intervalStatusProductCreating',
  'intervalStatusAddingAsin',
  'intervalStatusFinished',
  'intervalsSum',
  'updatedAt',
  'amazonTitle',
  'asin',
  'skuByClient',
  'status',
]
