/**
 * amazonapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiV1AdminsGetProductsByStatusClientId from './model/ApiV1AdminsGetProductsByStatusClientId';
import ApiV1AdminsGetProductsByStatusCurrentSupplier from './model/ApiV1AdminsGetProductsByStatusCurrentSupplier';
import ApiV1AdminsOrdersCreatedBy from './model/ApiV1AdminsOrdersCreatedBy';
import ApiV1AdminsPaymentsCreatedBy from './model/ApiV1AdminsPaymentsCreatedBy';
import ApiV1BatchesBatch from './model/ApiV1BatchesBatch';
import ApiV1BatchesBoxes from './model/ApiV1BatchesBoxes';
import ApiV1BatchesItems from './model/ApiV1BatchesItems';
import ApiV1BoxesApproveAdditionalBoxes from './model/ApiV1BoxesApproveAdditionalBoxes';
import ApiV1BoxesItems from './model/ApiV1BoxesItems';
import BadRequestError from './model/BadRequestError';
import ConflictInTheState from './model/ConflictInTheState';
import DefaultHeaders from './model/DefaultHeaders';
import ForbiddenError from './model/ForbiddenError';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InlineObject10 from './model/InlineObject10';
import InlineObject11 from './model/InlineObject11';
import InlineObject12 from './model/InlineObject12';
import InlineObject13 from './model/InlineObject13';
import InlineObject14 from './model/InlineObject14';
import InlineObject15 from './model/InlineObject15';
import InlineObject16 from './model/InlineObject16';
import InlineObject17 from './model/InlineObject17';
import InlineObject18 from './model/InlineObject18';
import InlineObject19 from './model/InlineObject19';
import InlineObject2 from './model/InlineObject2';
import InlineObject20 from './model/InlineObject20';
import InlineObject21 from './model/InlineObject21';
import InlineObject22 from './model/InlineObject22';
import InlineObject23 from './model/InlineObject23';
import InlineObject24 from './model/InlineObject24';
import InlineObject25 from './model/InlineObject25';
import InlineObject26 from './model/InlineObject26';
import InlineObject27 from './model/InlineObject27';
import InlineObject28 from './model/InlineObject28';
import InlineObject29 from './model/InlineObject29';
import InlineObject3 from './model/InlineObject3';
import InlineObject30 from './model/InlineObject30';
import InlineObject31 from './model/InlineObject31';
import InlineObject32 from './model/InlineObject32';
import InlineObject33 from './model/InlineObject33';
import InlineObject34 from './model/InlineObject34';
import InlineObject35 from './model/InlineObject35';
import InlineObject4 from './model/InlineObject4';
import InlineObject5 from './model/InlineObject5';
import InlineObject6 from './model/InlineObject6';
import InlineObject7 from './model/InlineObject7';
import InlineObject8 from './model/InlineObject8';
import InlineObject9 from './model/InlineObject9';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse20010 from './model/InlineResponse20010';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse2009 from './model/InlineResponse2009';
import InlineResponse201 from './model/InlineResponse201';
import InlineResponse2011 from './model/InlineResponse2011';
import InlineResponse2012 from './model/InlineResponse2012';
import InlineResponse2013 from './model/InlineResponse2013';
import InlineResponse2014 from './model/InlineResponse2014';
import InlineResponse2015 from './model/InlineResponse2015';
import InlineResponse2016 from './model/InlineResponse2016';
import InlineResponse2017 from './model/InlineResponse2017';
import InlineResponse400 from './model/InlineResponse400';
import InlineResponse403 from './model/InlineResponse403';
import InlineResponse404 from './model/InlineResponse404';
import InlineResponse409 from './model/InlineResponse409';
import InlineResponse500 from './model/InlineResponse500';
import InternalServerError from './model/InternalServerError';
import NotFoundError from './model/NotFoundError';
import PasteSuccessfully from './model/PasteSuccessfully';
import PayloadTooLarge from './model/PayloadTooLarge';
import UnauthorizedError from './model/UnauthorizedError';
import UpdatedSuccessfully from './model/UpdatedSuccessfully';
import UserSchema from './model/UserSchema';
import AdministratorApi from './api/AdministratorApi';
import BatchesApi from './api/BatchesApi';
import BoxesApi from './api/BoxesApi';
import BuyerApi from './api/BuyerApi';
import ClientApi from './api/ClientApi';
import OtherApi from './api/OtherApi';
import ProductForTestOnlyApi from './api/ProductForTestOnlyApi';
import ResearcherApi from './api/ResearcherApi';
import StorekeepersApi from './api/StorekeepersApi';
import SupervisorApi from './api/SupervisorApi';
import SupplierApi from './api/SupplierApi';
import UserApi from './api/UserApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Amazonapi = require('index'); // See note below*.
* var xxxSvc = new Amazonapi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Amazonapi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Amazonapi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Amazonapi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiV1AdminsGetProductsByStatusClientId model constructor.
     * @property {module:model/ApiV1AdminsGetProductsByStatusClientId}
     */
    ApiV1AdminsGetProductsByStatusClientId,

    /**
     * The ApiV1AdminsGetProductsByStatusCurrentSupplier model constructor.
     * @property {module:model/ApiV1AdminsGetProductsByStatusCurrentSupplier}
     */
    ApiV1AdminsGetProductsByStatusCurrentSupplier,

    /**
     * The ApiV1AdminsOrdersCreatedBy model constructor.
     * @property {module:model/ApiV1AdminsOrdersCreatedBy}
     */
    ApiV1AdminsOrdersCreatedBy,

    /**
     * The ApiV1AdminsPaymentsCreatedBy model constructor.
     * @property {module:model/ApiV1AdminsPaymentsCreatedBy}
     */
    ApiV1AdminsPaymentsCreatedBy,

    /**
     * The ApiV1BatchesBatch model constructor.
     * @property {module:model/ApiV1BatchesBatch}
     */
    ApiV1BatchesBatch,

    /**
     * The ApiV1BatchesBoxes model constructor.
     * @property {module:model/ApiV1BatchesBoxes}
     */
    ApiV1BatchesBoxes,

    /**
     * The ApiV1BatchesItems model constructor.
     * @property {module:model/ApiV1BatchesItems}
     */
    ApiV1BatchesItems,

    /**
     * The ApiV1BoxesApproveAdditionalBoxes model constructor.
     * @property {module:model/ApiV1BoxesApproveAdditionalBoxes}
     */
    ApiV1BoxesApproveAdditionalBoxes,

    /**
     * The ApiV1BoxesItems model constructor.
     * @property {module:model/ApiV1BoxesItems}
     */
    ApiV1BoxesItems,

    /**
     * The BadRequestError model constructor.
     * @property {module:model/BadRequestError}
     */
    BadRequestError,

    /**
     * The ConflictInTheState model constructor.
     * @property {module:model/ConflictInTheState}
     */
    ConflictInTheState,

    /**
     * The DefaultHeaders model constructor.
     * @property {module:model/DefaultHeaders}
     */
    DefaultHeaders,

    /**
     * The ForbiddenError model constructor.
     * @property {module:model/ForbiddenError}
     */
    ForbiddenError,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject10 model constructor.
     * @property {module:model/InlineObject10}
     */
    InlineObject10,

    /**
     * The InlineObject11 model constructor.
     * @property {module:model/InlineObject11}
     */
    InlineObject11,

    /**
     * The InlineObject12 model constructor.
     * @property {module:model/InlineObject12}
     */
    InlineObject12,

    /**
     * The InlineObject13 model constructor.
     * @property {module:model/InlineObject13}
     */
    InlineObject13,

    /**
     * The InlineObject14 model constructor.
     * @property {module:model/InlineObject14}
     */
    InlineObject14,

    /**
     * The InlineObject15 model constructor.
     * @property {module:model/InlineObject15}
     */
    InlineObject15,

    /**
     * The InlineObject16 model constructor.
     * @property {module:model/InlineObject16}
     */
    InlineObject16,

    /**
     * The InlineObject17 model constructor.
     * @property {module:model/InlineObject17}
     */
    InlineObject17,

    /**
     * The InlineObject18 model constructor.
     * @property {module:model/InlineObject18}
     */
    InlineObject18,

    /**
     * The InlineObject19 model constructor.
     * @property {module:model/InlineObject19}
     */
    InlineObject19,

    /**
     * The InlineObject2 model constructor.
     * @property {module:model/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject20 model constructor.
     * @property {module:model/InlineObject20}
     */
    InlineObject20,

    /**
     * The InlineObject21 model constructor.
     * @property {module:model/InlineObject21}
     */
    InlineObject21,

    /**
     * The InlineObject22 model constructor.
     * @property {module:model/InlineObject22}
     */
    InlineObject22,

    /**
     * The InlineObject23 model constructor.
     * @property {module:model/InlineObject23}
     */
    InlineObject23,

    /**
     * The InlineObject24 model constructor.
     * @property {module:model/InlineObject24}
     */
    InlineObject24,

    /**
     * The InlineObject25 model constructor.
     * @property {module:model/InlineObject25}
     */
    InlineObject25,

    /**
     * The InlineObject26 model constructor.
     * @property {module:model/InlineObject26}
     */
    InlineObject26,

    /**
     * The InlineObject27 model constructor.
     * @property {module:model/InlineObject27}
     */
    InlineObject27,

    /**
     * The InlineObject28 model constructor.
     * @property {module:model/InlineObject28}
     */
    InlineObject28,

    /**
     * The InlineObject29 model constructor.
     * @property {module:model/InlineObject29}
     */
    InlineObject29,

    /**
     * The InlineObject3 model constructor.
     * @property {module:model/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineObject30 model constructor.
     * @property {module:model/InlineObject30}
     */
    InlineObject30,

    /**
     * The InlineObject31 model constructor.
     * @property {module:model/InlineObject31}
     */
    InlineObject31,

    /**
     * The InlineObject32 model constructor.
     * @property {module:model/InlineObject32}
     */
    InlineObject32,

    /**
     * The InlineObject33 model constructor.
     * @property {module:model/InlineObject33}
     */
    InlineObject33,

    /**
     * The InlineObject34 model constructor.
     * @property {module:model/InlineObject34}
     */
    InlineObject34,

    /**
     * The InlineObject35 model constructor.
     * @property {module:model/InlineObject35}
     */
    InlineObject35,

    /**
     * The InlineObject4 model constructor.
     * @property {module:model/InlineObject4}
     */
    InlineObject4,

    /**
     * The InlineObject5 model constructor.
     * @property {module:model/InlineObject5}
     */
    InlineObject5,

    /**
     * The InlineObject6 model constructor.
     * @property {module:model/InlineObject6}
     */
    InlineObject6,

    /**
     * The InlineObject7 model constructor.
     * @property {module:model/InlineObject7}
     */
    InlineObject7,

    /**
     * The InlineObject8 model constructor.
     * @property {module:model/InlineObject8}
     */
    InlineObject8,

    /**
     * The InlineObject9 model constructor.
     * @property {module:model/InlineObject9}
     */
    InlineObject9,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The InlineResponse2011 model constructor.
     * @property {module:model/InlineResponse2011}
     */
    InlineResponse2011,

    /**
     * The InlineResponse2012 model constructor.
     * @property {module:model/InlineResponse2012}
     */
    InlineResponse2012,

    /**
     * The InlineResponse2013 model constructor.
     * @property {module:model/InlineResponse2013}
     */
    InlineResponse2013,

    /**
     * The InlineResponse2014 model constructor.
     * @property {module:model/InlineResponse2014}
     */
    InlineResponse2014,

    /**
     * The InlineResponse2015 model constructor.
     * @property {module:model/InlineResponse2015}
     */
    InlineResponse2015,

    /**
     * The InlineResponse2016 model constructor.
     * @property {module:model/InlineResponse2016}
     */
    InlineResponse2016,

    /**
     * The InlineResponse2017 model constructor.
     * @property {module:model/InlineResponse2017}
     */
    InlineResponse2017,

    /**
     * The InlineResponse400 model constructor.
     * @property {module:model/InlineResponse400}
     */
    InlineResponse400,

    /**
     * The InlineResponse403 model constructor.
     * @property {module:model/InlineResponse403}
     */
    InlineResponse403,

    /**
     * The InlineResponse404 model constructor.
     * @property {module:model/InlineResponse404}
     */
    InlineResponse404,

    /**
     * The InlineResponse409 model constructor.
     * @property {module:model/InlineResponse409}
     */
    InlineResponse409,

    /**
     * The InlineResponse500 model constructor.
     * @property {module:model/InlineResponse500}
     */
    InlineResponse500,

    /**
     * The InternalServerError model constructor.
     * @property {module:model/InternalServerError}
     */
    InternalServerError,

    /**
     * The NotFoundError model constructor.
     * @property {module:model/NotFoundError}
     */
    NotFoundError,

    /**
     * The PasteSuccessfully model constructor.
     * @property {module:model/PasteSuccessfully}
     */
    PasteSuccessfully,

    /**
     * The PayloadTooLarge model constructor.
     * @property {module:model/PayloadTooLarge}
     */
    PayloadTooLarge,

    /**
     * The UnauthorizedError model constructor.
     * @property {module:model/UnauthorizedError}
     */
    UnauthorizedError,

    /**
     * The UpdatedSuccessfully model constructor.
     * @property {module:model/UpdatedSuccessfully}
     */
    UpdatedSuccessfully,

    /**
     * The UserSchema model constructor.
     * @property {module:model/UserSchema}
     */
    UserSchema,

    /**
    * The AdministratorApi service constructor.
    * @property {module:api/AdministratorApi}
    */
    AdministratorApi,

    /**
    * The BatchesApi service constructor.
    * @property {module:api/BatchesApi}
    */
    BatchesApi,

    /**
    * The BoxesApi service constructor.
    * @property {module:api/BoxesApi}
    */
    BoxesApi,

    /**
    * The BuyerApi service constructor.
    * @property {module:api/BuyerApi}
    */
    BuyerApi,

    /**
    * The ClientApi service constructor.
    * @property {module:api/ClientApi}
    */
    ClientApi,

    /**
    * The OtherApi service constructor.
    * @property {module:api/OtherApi}
    */
    OtherApi,

    /**
    * The ProductForTestOnlyApi service constructor.
    * @property {module:api/ProductForTestOnlyApi}
    */
    ProductForTestOnlyApi,

    /**
    * The ResearcherApi service constructor.
    * @property {module:api/ResearcherApi}
    */
    ResearcherApi,

    /**
    * The StorekeepersApi service constructor.
    * @property {module:api/StorekeepersApi}
    */
    StorekeepersApi,

    /**
    * The SupervisorApi service constructor.
    * @property {module:api/SupervisorApi}
    */
    SupervisorApi,

    /**
    * The SupplierApi service constructor.
    * @property {module:api/SupplierApi}
    */
    SupplierApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
