export const BoxStatus = {
  IN_STOCK: 'IN_STOCK',
  REQUESTED_SEND_TO_BATCH: 'REQUESTED_SEND_TO_BATCH',
  NEED_CONFIRMING_TO_DELIVERY_PRICE_CHANGE: 'NEED_CONFIRMING_TO_DELIVERY_PRICE_CHANGE',
  IN_BATCH: 'IN_BATCH',
  NEED_TO_UPDATE_THE_TARIFF: 'NEED_TO_UPDATE_THE_TARIFF',
}
