export const columnnsKeys = {
  supervisor: {},
  buyer: {
    MY_ORDERS_STATUS: 'MY_ORDERS_STATUS',
  },
  storekeeper: {},
  client: {
    WAREHOUSE_IN_STOCK_SHOPS: 'WAREHOUSE_IN_STOCK_SHOPS',
    WAREHOUSE_IN_STOCK_IS_FORMED: 'WAREHOUSE_IN_STOCK_IS_FORMED',
    WAREHOUSE_ID: 'WAREHOUSE_ID',
    INVENTORY_PURCHASE_QUANTITY: 'INVENTORY_PURCHASE_QUANTITY',
    ORDERS_STATUS: 'ORDERS_STATUS',
    // Добавил
    WAREHOUSE_IN_STOCK_PRODUCT: 'WAREHOUSE_IN_STOCK_PRODUCT',
    WAREHOUSE_IN_STOCK_ORDER_IDS_ITEMS: 'WAREHOUSE_IN_STOCK_ORDER_IDS_ITEMS',
    WAREHOUSE_IN_STOCK_DESTINATION: 'WAREHOUSE_IN_STOCK_DESTINATION',
  },
  researcher: {},
  shared: {
    DATE: 'DATE',
  },
}
