export const columnnsKeys = {
  supervisor: {},
  buyer: {
    MY_ORDERS_STATUS: 'MY_ORDERS_STATUS',
  },
  storekeeper: {},
  client: {
    WAREHOUSE_IN_STOCK_SHOPS: 'WAREHOUSE_IN_STOCK_SHOPS',
    WAREHOUSE_IN_STOCK_IS_FORMED: 'WAREHOUSE_IN_STOCK_IS_FORMED',
    WAREHOUSE_ID: 'WAREHOUSE_ID',
    INVENTORY_PURCHASE_QUANTITY: 'INVENTORY_PURCHASE_QUANTITY',
    ORDERS_STATUS: 'ORDERS_STATUS',

    WAREHOUSE_IN_STOCK_PRODUCT: 'WAREHOUSE_IN_STOCK_PRODUCT',
    WAREHOUSE_IN_STOCK_ORDER_IDS_ITEMS: 'WAREHOUSE_IN_STOCK_ORDER_IDS_ITEMS',
    WAREHOUSE_IN_STOCK_DESTINATION: 'WAREHOUSE_IN_STOCK_DESTINATION',

    INVENTORY_PRODUCT: 'INVENTORY_PRODUCT',
    INVENTORY_SHOPS: 'INVENTORY_SHOPS',
    INVENTORY_STRATEGY_STATUS: 'INVENTORY_STRATEGY_STATUS',
    INVENTORY_STATUS: 'INVENTORY_STATUS',
    INVENTORY_IN_STOCK: 'INVENTORY_IN_STOCK',
  },
  researcher: {},
  shared: {
    DATE: 'DATE',
    QUANTITY: 'QUANTITY',
    PRODUCT_ORDERS_STATUS: 'PRODUCT_ORDERS_STATUS',
  },
}
