export const inventorySection = {
  title: 'Инвентарь',
  items: [
    {value: 7, title: 'Товаров в инвентаре', color: '#20a8d8'},
    {value: 5, title: 'Общая стоимость склада', color: '#63c2de'},
    {value: 0, title: 'Товаров с повторной закупкой', color: '#4dbd74'},
  ],
}

export const ordersSection = {
  title: 'Заказы',
  items: [
    {value: 2, title: 'Неоплаченные заказы', color: '#ffc107'},
    {value: 0, title: 'Оплаченные заказы', color: '#f86c6b'},
    {value: 24, title: 'Отмененные заказы', color: '#20a8d8'},
  ],
}
export const exchangeSection = {
  title: 'Товары',
  items: [
    {value: 53, title: 'Продано товаров на бирже', color: '#63c2de'},
    {value: 1, title: 'Начислено ресерчерам', color: '#4dbd74'},
    {value: 17, title: 'Споров по товарам', color: '#f86c6b'},
  ],
}

export const adminUsername = 'Admin'
export const clientUsername = 'Client'
export const buyerUsername = 'Buyer'
export const storekeeperUsername = 'Storekeeper'

export const clientExchangeRequestsViewTable = {
  headCells: [
    {id: 'img', label: 'Budget'},
    {id: 'img', label: 'Target date'},
    {id: 'img', label: 'Status'},
    {id: 'img', label: 'Strategy'},
  ],
  tableKeys: ['budget', 'deadline', 'status', 'strategy'],
  requestsListRaw: [
    {budget: 50000, deadline: '20/04/2022', status: 'Обрабатывается', strategy: 'Flipping'},
    {budget: 27420.42, deadline: '19/11/2021', status: 'Обрабатано', strategy: 'PrivateLabel'},
  ],
}

export const clientWarehouseViewTable = {
  headCells: [
    {id: 'img', label: '#'},
    {id: 'img', label: ''},
    {id: 'img', label: 'Product'},
    {id: 'img', label: 'Order'},
    {id: 'img', label: 'Barcode'},
    {id: 'img', label: 'ASIN'},
    {id: 'img', label: 'Qty'},
    {id: 'img', label: 'Material'},
    {id: 'img', label: 'Warehouse'},
    {id: 'img', label: 'Boxes'},
    {id: 'img', label: 'Price'},
    {id: 'img', label: 'Weight'},
    {id: 'img', label: 'Gross Weight'},
    {id: 'img', label: 'Track ID'},
  ],
}

export const buyerWarehouseViewTable = {
  headCells: [
    {id: 'img', label: '#'},
    {id: 'img', label: ''},
    {id: 'img', label: 'Product'},
    {id: 'img', label: 'Order'},
    {id: 'img', label: 'Barcode'},
    {id: 'img', label: 'ASIN'},
    {id: 'img', label: 'Qty'},
    {id: 'img', label: 'Material'},
    {id: 'img', label: 'Warehouse'},
    {id: 'img', label: 'Boxes'},
    {id: 'img', label: 'Price'},
    {id: 'img', label: 'Weight'},
    {id: 'img', label: 'Gross Weight'},
    {id: 'img', label: 'Weight ??'},
    {id: 'img', label: 'Track ID'},
  ],
}

export const userPopperItems = {
  client: [
    {label: 'Ваш счёт $4 352', color: '#5a6169', route: null},
    {label: 'Пополнить баланс', color: '#5a6169', route: null},
    {label: 'Сообщения', color: '#5a6169', route: null},
    {label: 'Профиль', color: '#5a6169', route: '/user'},
    {label: 'Выйти', color: '#d22323', route: '/auth'},
  ],
  buyer: [
    {label: 'Ваш счёт $4 352', color: '#5a6169', route: null},
    {label: 'Пополнить баланс', color: '#5a6169', route: null},
    {label: 'Сообщения', color: '#5a6169', route: null},
    {label: 'Профиль', color: '#5a6169', route: '/buyer/user'},
    {label: 'Выйти', color: '#d22323', route: '/auth'},
  ],
  researcher: [
    {label: 'Ваш счёт $4 352', color: '#5a6169', route: null},
    {label: 'Пополнить баланс', color: '#5a6169', route: null},
    {label: 'Сообщения', color: '#5a6169', route: null},
    {label: 'Профиль', color: '#5a6169', route: null},
    {label: 'Выйти', color: '#d22323', route: '/auth'},
  ],
  supervisor: [
    {label: 'Ваш счёт $4 352', color: '#5a6169', route: null},
    {label: 'Пополнить баланс', color: '#5a6169', route: null},
    {label: 'Сообщения', color: '#5a6169', route: null},
    {label: 'Профиль', color: '#5a6169', route: null},
    {label: 'Выйти', color: '#d22323', route: '/auth'},
  ],
}
export const userRoutes = {
  client: {
    0: null,
    1: null,
    2: null,
    3: '/user',
    4: 'auth',
  },
  buyer: {},
  researcher: {},
}

export const PRODUCT_INITIAL_PRODUCT = {
  images: {},
  csCode:
    'Leaf Style Door Stopper Set - Silicone Rubber Stoppers Colorful Door Stop Wedge Cute Finger Guard Door Stoppers with Silicone Holders Window / Door Stopper for Home and Office',
  asin: 'B07RKM1PSD',
  linkAmazon: 'https://www.amazon.com/dp/B07RKM1PSD',
  fba: true,
  bsr: 23.309,
  buyBoxPrice: 5.99,
  width: 5.2756,
  height: 7.0472,
  length: 1.7717,
  weight: 2.5,
  minPrice: 0.541,
  supplier: 5,
  express: true,
  maxDeliveryPrice: 0.6512,
  refferalFee: 0.8894,
  fbaFee: 5.02,
  totalFba: 5.02,
  recConsignmentQty: 10,
  revenue: 10.412,
  margin: 12,
  status: 'status',
  summary: 'some summary',
  description:
    'Product information Size:Leaf Technical Details Manufacturer HYQO Brand HYQO Item Weight 4.7 ounces Package Dimensions 7.05 x 5.28 x 1.77 inches Color Green, Yellow, Blue, Brown Material Type Silicone Size Leaf Manufacturer Part Number Leaf Additional Information ASIN B08CH6J8NF Customer Reviews 4.1 out of 5 stars 69 ratings 4.1 out of 5 stars Best Sellers Rank #23,309 in Office Products (See Top 100 in Office Products) #173 in Door Stops Date First Available July 7, 2020 Warranty & Support Product Warranty: For warranty information about this product, please click here Feedback Would you like to tell us about a lower price?',
  commentManager: "Manager's comment",
  commentSupervisor: "Supervisor's comment",
  commentBuyer: "Buyer's comment",
}

export const RESEARCHER_HEAD_CELLS = [
  {title: 'ASIN'},
  {title: 'Status'},
  {title: 'Created'},
  {title: 'Amazon price'},
  {title: 'BSR'},
]

//  это еще используется в баере
export const BATCHES_BOXES_EXAMPLES = [
  [
    {
      id: '1',
      status: 'test1',
      created: '12/12/2018',
      updated: '12/12/2018',
      deliveryMethod: 'Sea',
      clientId: 'clientID0001',

      csCode: 'Вкладыш для холодильника',
      img: 'https://images-na.ssl-images-amazon.com/images/I/61PgqkN76dL._AC_SX679_.jpg',
      orderId: 'ID590101',
      asin: 'B0878YDFMK',
      qty: 100,
      material: 'metal',
      destination: 'Не назначен',
      product: 'Product',
      boxId: ['509991', '509992', '509993', '509994'],
      boxQty: 4,
      price: 2000,
      weight: 105,
      grossWeight: 125,
      trackId: '91023891273812738111',
      chip: '27381111',
    },
    {
      id: '2',
      status: 'test1',
      created: '12/12/2018',
      updated: '12/12/2018',
      deliveryMethod: 'Sea',

      csCode: 'Xолодильника',
      img: 'https://images-na.ssl-images-amazon.com/images/I/51ZEDgERzPL._AC_SX679_.jpg',
      orderId: 'ID590102',
      asin: 'C1878YDFMK',
      qty: 100,
      material: 'plastic',
      destination: 'Не назначен',
      product: 'Product',
      boxId: ['509991', '509992', '509993', '509994'],
      boxQty: 4,
      price: 5000,
      weight: 50,
      grossWeight: null,
      trackId: '91023891273812738111',
      chip: null,
    },
  ],
  [
    {
      id: '3',
      status: 'test4',
      created: '24/11/2020',
      updated: '25/11/2020',
      deliveryMethod: 'Sea',
      clientId: 'clientID0002',

      csCode: 'Упаковка батареек АА 48 шт.',
      img: 'https://images-na.ssl-images-amazon.com/images/I/71IdKRlm8%2BL._AC_SX569_.jpg',
      orderId: 'ID590322',
      asin: 'B00MNV8E0C',
      qty: 75,
      material: 'Alkaline',
      destination: 'Не назначен',
      product: 'Product',
      boxId: ['EnergyID'],
      boxQty: 1,
      price: 2500,
      weight: 25,
      grossWeight: null,
      trackId: '91023891273812738142',
      chip: null,
    },
  ],
  [
    {
      id: '4',
      status: 'test2',
      created: '16/02/2020',
      updated: '16/02/2020',
      deliveryMethod: 'Air',
      clientId: 'clientID0007',

      csCode: 'Настенное крепление',
      img: 'https://images-na.ssl-images-amazon.com/images/I/71jcxZXEaGL._AC_SL1500_.jpg',
      orderId: 'ID590101',
      asin: 'F1578YDFMK',
      qty: 10,
      material: 'metal',
      destination: 'ONT 8 AMAZON',
      product: 'Product',
      boxId: ['boxId3'],
      boxQty: 1,
      price: 2000,
      weight: 105,
      grossWeight: 125,
      trackId: '91023891273812738111',
      chip: '63514941',
    },
    {
      id: '5',
      status: 'test2',
      created: '16/02/2020',
      updated: '16/02/2020',
      deliveryMethod: 'Air',

      csCode: 'Книжный шкаф',
      img: 'https://images-na.ssl-images-amazon.com/images/I/818idL5RrlL._AC_SL1500_.jpg',
      orderId: 'ID590101',
      asin: 'CMYK0YDFMK',
      qty: 150,
      material: 'plastic',
      destination: 'ONT 8 AMAZON',
      product: 'Product',
      boxId: ['boxId3'],
      boxQty: 1,
      price: 5000,
      weight: 50,
      grossWeight: null,
      trackId: '91023891273812738111',
      chip: null,
    },
  ],
]

export const BATCHES = [
  {
    batch: {deliveryMethod: 3, warehouse: 40},
    boxes: [
      {
        _id: '60de158e638c0d3917ec776c',
        lengthCm: 0,
        widthCm: 0,
        heightCm: 0,
        warehouse: 40,
        deliveryMethod: 3,
        lengthCmSupplier: 1,
        widthCmSupplier: 1,
        heightCmSupplier: 1,
        weighGrossKgSupplier: 1,
        volumeWeightKgSupplier: 0.0002,
        weightFinalAccountingKgSupplier: 1,
        status: 0,
        createdBy: '60aabf69b2f06d5a147ba009',
        lastModifiedBy: '60aabf69b2f06d5a147ba009',
        items: [
          {
            product: {
              _id: '60ddedaf638c0d3917ec775c',
              id: 'B08FCWM1LF',
              material: 'default_material',
              category: 'gl_office_product',
              lamazon:
                'https://www.amazon.com/Premium-Rainbow-Color-Embroidery-Floss/dp/B08FCWM1LF/ref=sr_1_2?dchild=1&qid=1625047838&s=arts-crafts-intl-ship&sr=1-2',
              bsr: 340,
              fba: false,
              express: false,
              amazon: 4.99,
              height: 7.8,
              width: 5.9,
              length: 1.3,
              weight: 0.1359868816,
              supplier: [],
              reffee: 15,
              fbafee: 3.02,
              delivery: 0,
              status: 70,
              icomment: 'ok',
              images: [
                '81SB-tQ0baL',
                '61jCkna2_2ByL',
                '51LEuOc-2PL',
                '61-w_2BmGSONL',
                '51A2iIHhZML',
                '612jjd8UhtL',
                '51LGBKfwH4L',
                '51LN86Gn0pL',
              ],
              checkednotes: 'okok',
              dirdecision: 0,
              amazonDescription:
                ' Add vibrant colors to your craft projects with this Embroidery Floss. There are 50 skein embroidery floss, each skein contains 8 meters long, which allows for easy separating and creating designs in thin or thick lines. Whether you are doing hand work, cross-stitching or needlecraft project, this polyester-cotton embroidery floss giving you 50 colors to choose from, making it a diverse and versatile assortment. ',
              amazonDetail:
                ' Product information Product Dimensions 3.94 x 1.57 x 0.39 inches Item Weight 4.8 ounces Manufacturer Vabogu ASIN B08FCWM1LF Customer Reviews 5.0 out of 5 stars 2 ratings 5.0 out of 5 stars Best Sellers Rank #340 in Arts, Crafts & Sewing (See Top 100 in Arts, Crafts & Sewing) #2 in Embroidery Floss Date First Available August 7, 2020 Warranty & Support Product Warranty: For warranty information about this product, please click here Feedback Would you like to tell us about a lower price? ',
              amazonTitle:
                'Premium Rainbow Color Embroidery Floss - Cross Stitch Threads - Friendship Bracelets Floss - Crafts Floss - 50 Skeins Per Pack',
              minpurchase: 0.7329000000000001,
              profit: 0,
              margin: 0,
              createdby: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              createdat: '2021-07-01T16:30:39.000Z',
              updateDate: '2021-07-01T16:32:39.000Z',
              checkedat: '2021-07-01T16:31:56.000Z',
              buyer: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              buyerscomment: 'ok',
            },
            amount: 10,
            order: '60ddee27638c0d3917ec7760',
          },
        ],
        isDraft: false,
        images: [],
      },
    ],
  },
  {
    batch: {deliveryMethod: 2, warehouse: 35},
    boxes: [
      {
        _id: '60de0abf638c0d3917ec7762',
        lengthCm: 0,
        widthCm: 0,
        heightCm: 0,
        warehouse: 35,
        deliveryMethod: 2,
        lengthCmSupplier: 2,
        widthCmSupplier: 3,
        heightCmSupplier: 34,
        weighGrossKgSupplier: 43,
        volumeWeightKgSupplier: 0.0408,
        weightFinalAccountingKgSupplier: 43,
        status: 0,
        createdBy: '60aabf69b2f06d5a147ba009',
        lastModifiedBy: '60aabf69b2f06d5a147ba009',
        items: [
          {
            product: {
              _id: '60ddedaf638c0d3917ec775c',
              id: 'B08FCWM1LF',
              material: 'default_material',
              category: 'gl_office_product',
              lamazon:
                'https://www.amazon.com/Premium-Rainbow-Color-Embroidery-Floss/dp/B08FCWM1LF/ref=sr_1_2?dchild=1&qid=1625047838&s=arts-crafts-intl-ship&sr=1-2',
              bsr: 340,
              fba: false,
              express: false,
              amazon: 4.99,
              height: 7.8,
              width: 5.9,
              length: 1.3,
              weight: 0.1359868816,
              supplier: [],
              reffee: 15,
              fbafee: 3.02,
              delivery: 0,
              status: 70,
              icomment: 'ok',
              images: [
                '81SB-tQ0baL',
                '61jCkna2_2ByL',
                '51LEuOc-2PL',
                '61-w_2BmGSONL',
                '51A2iIHhZML',
                '612jjd8UhtL',
                '51LGBKfwH4L',
                '51LN86Gn0pL',
              ],
              checkednotes: 'okok',
              dirdecision: 0,
              amazonDescription:
                ' Add vibrant colors to your craft projects with this Embroidery Floss. There are 50 skein embroidery floss, each skein contains 8 meters long, which allows for easy separating and creating designs in thin or thick lines. Whether you are doing hand work, cross-stitching or needlecraft project, this polyester-cotton embroidery floss giving you 50 colors to choose from, making it a diverse and versatile assortment. ',
              amazonDetail:
                ' Product information Product Dimensions 3.94 x 1.57 x 0.39 inches Item Weight 4.8 ounces Manufacturer Vabogu ASIN B08FCWM1LF Customer Reviews 5.0 out of 5 stars 2 ratings 5.0 out of 5 stars Best Sellers Rank #340 in Arts, Crafts & Sewing (See Top 100 in Arts, Crafts & Sewing) #2 in Embroidery Floss Date First Available August 7, 2020 Warranty & Support Product Warranty: For warranty information about this product, please click here Feedback Would you like to tell us about a lower price? ',
              amazonTitle:
                'Premium Rainbow Color Embroidery Floss - Cross Stitch Threads - Friendship Bracelets Floss - Crafts Floss - 50 Skeins Per Pack',
              minpurchase: 0.7329000000000001,
              profit: 0,
              margin: 0,
              createdby: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              createdat: '2021-07-01T16:30:39.000Z',
              updateDate: '2021-07-01T16:32:39.000Z',
              checkedat: '2021-07-01T16:31:56.000Z',
              buyer: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              buyerscomment: 'ok',
            },
            amount: 13,
            order: '60ddee27638c0d3917ec7760',
          },
        ],
        isDraft: false,
        images: [],
      },
      {
        _id: '60de0f44638c0d3917ec7764',
        lengthCm: 0,
        widthCm: 0,
        heightCm: 0,
        warehouse: 35,
        deliveryMethod: 2,
        lengthCmSupplier: 3,
        widthCmSupplier: 3,
        heightCmSupplier: 3,
        weighGrossKgSupplier: 3,
        volumeWeightKgSupplier: 0.0054,
        weightFinalAccountingKgSupplier: 3,
        status: 0,
        createdBy: '60aabf69b2f06d5a147ba009',
        lastModifiedBy: '60aabf69b2f06d5a147ba009',
        items: [
          {
            product: {
              _id: '60dde007638c0d3917ec7757',
              id: 'B01D3ZU5I0',
              material: 'default_material',
              category: 'gl_home',
              lamazon:
                'https://www.amazon.com/eBoot-Inch-Wooden-Bent-Latch/dp/B01D3ZU5I0/ref=sr_1_24?dchild=1&qid=1625047838&s=arts-crafts-intl-ship&sr=1-24',
              bsr: 3,
              fba: false,
              express: false,
              amazon: 7.99,
              height: 8.46,
              width: 4.53,
              length: 1.06,
              weight: 0.131995272,
              supplier: [],
              reffee: 15,
              fbafee: 3.02,
              delivery: 0,
              fbaamount: 102,
              status: 70,
              icomment: 'нашел штуковину',
              images: [
                '41XJDPBQjaL',
                '31lOSWNvBQL',
                '412A5g5mUyL',
                '41Jjj5Ey_2BPL',
                '61n87x1vPlL',
                '61kwyovi_2BCL',
                '718H7g671qL',
              ],
              checkednotes: 'ничего такая штука\nнорм поставщик',
              dirdecision: 0,
              amazonDescription: '',
              amazonDetail:
                ' Product information Product Dimensions 6.3 x 0.79 x 0.79 inches Item model number 3400875 ASIN B01D3ZU5I0 Customer Reviews 4.7 out of 5 stars 1,257 ratings 4.7 out of 5 stars Best Sellers Rank #3,163 in Arts, Crafts & Sewing (See Top 100 in Arts, Crafts & Sewing) #1 in Latch Hook Supplies Is Discontinued By Manufacturer No Item Weight 2.12 ounces Manufacturer eBoot Date First Available March 18, 2016 Warranty & Support Product Warranty: For warranty information about this product, please click here Feedback Would you like to tell us about a lower price? ',
              amazonTitle: 'eBoot 6.5 Inch Wooden Bent Latch Hook Tool, Set of 3',
              minpurchase: 2.2629,
              profit: 0,
              margin: 0,
              createdby: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              createdat: '2021-07-01T15:32:23.000Z',
              updateDate: '2021-07-01T16:10:10.000Z',
              checkedat: '2021-07-01T15:40:57.000Z',
              buyer: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              buyerscomment: 'нашел поставщика',
            },
            amount: 16,
            order: '60dde8e2638c0d3917ec775b',
          },
        ],
        isDraft: false,
        images: [],
      },
      {
        _id: '60de1129638c0d3917ec7766',
        lengthCm: 0,
        widthCm: 0,
        heightCm: 0,
        warehouse: 35,
        deliveryMethod: 2,
        lengthCmSupplier: 1,
        widthCmSupplier: 4,
        heightCmSupplier: 3,
        weighGrossKgSupplier: 8,
        volumeWeightKgSupplier: 0.0024,
        weightFinalAccountingKgSupplier: 8,
        status: 0,
        createdBy: '60aabf69b2f06d5a147ba009',
        lastModifiedBy: '60aabf69b2f06d5a147ba009',
        items: [
          {
            product: {
              _id: '60ddedaf638c0d3917ec775c',
              id: 'B08FCWM1LF',
              material: 'default_material',
              category: 'gl_office_product',
              lamazon:
                'https://www.amazon.com/Premium-Rainbow-Color-Embroidery-Floss/dp/B08FCWM1LF/ref=sr_1_2?dchild=1&qid=1625047838&s=arts-crafts-intl-ship&sr=1-2',
              bsr: 340,
              fba: false,
              express: false,
              amazon: 4.99,
              height: 7.8,
              width: 5.9,
              length: 1.3,
              weight: 0.1359868816,
              supplier: [],
              reffee: 15,
              fbafee: 3.02,
              delivery: 0,
              status: 70,
              icomment: 'ok',
              images: [
                '81SB-tQ0baL',
                '61jCkna2_2ByL',
                '51LEuOc-2PL',
                '61-w_2BmGSONL',
                '51A2iIHhZML',
                '612jjd8UhtL',
                '51LGBKfwH4L',
                '51LN86Gn0pL',
              ],
              checkednotes: 'okok',
              dirdecision: 0,
              amazonDescription:
                ' Add vibrant colors to your craft projects with this Embroidery Floss. There are 50 skein embroidery floss, each skein contains 8 meters long, which allows for easy separating and creating designs in thin or thick lines. Whether you are doing hand work, cross-stitching or needlecraft project, this polyester-cotton embroidery floss giving you 50 colors to choose from, making it a diverse and versatile assortment. ',
              amazonDetail:
                ' Product information Product Dimensions 3.94 x 1.57 x 0.39 inches Item Weight 4.8 ounces Manufacturer Vabogu ASIN B08FCWM1LF Customer Reviews 5.0 out of 5 stars 2 ratings 5.0 out of 5 stars Best Sellers Rank #340 in Arts, Crafts & Sewing (See Top 100 in Arts, Crafts & Sewing) #2 in Embroidery Floss Date First Available August 7, 2020 Warranty & Support Product Warranty: For warranty information about this product, please click here Feedback Would you like to tell us about a lower price? ',
              amazonTitle:
                'Premium Rainbow Color Embroidery Floss - Cross Stitch Threads - Friendship Bracelets Floss - Crafts Floss - 50 Skeins Per Pack',
              minpurchase: 0.7329000000000001,
              profit: 0,
              margin: 0,
              createdby: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              createdat: '2021-07-01T16:30:39.000Z',
              updateDate: '2021-07-01T16:32:39.000Z',
              checkedat: '2021-07-01T16:31:56.000Z',
              buyer: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              buyerscomment: 'ok',
            },
            amount: 10,
            order: '60ddee27638c0d3917ec7760',
          },
        ],
        isDraft: false,
        images: [],
      },
      {
        _id: '60de1147638c0d3917ec7768',
        lengthCm: 0,
        widthCm: 0,
        heightCm: 0,
        warehouse: 35,
        deliveryMethod: 2,
        lengthCmSupplier: 3,
        widthCmSupplier: 3,
        heightCmSupplier: 1,
        weighGrossKgSupplier: 3,
        volumeWeightKgSupplier: 0.0018,
        weightFinalAccountingKgSupplier: 3,
        status: 0,
        createdBy: '60aabf69b2f06d5a147ba009',
        lastModifiedBy: '60aabf69b2f06d5a147ba009',
        items: [
          {
            product: {
              _id: '60dde007638c0d3917ec7757',
              id: 'B01D3ZU5I0',
              material: 'default_material',
              category: 'gl_home',
              lamazon:
                'https://www.amazon.com/eBoot-Inch-Wooden-Bent-Latch/dp/B01D3ZU5I0/ref=sr_1_24?dchild=1&qid=1625047838&s=arts-crafts-intl-ship&sr=1-24',
              bsr: 3,
              fba: false,
              express: false,
              amazon: 7.99,
              height: 8.46,
              width: 4.53,
              length: 1.06,
              weight: 0.131995272,
              supplier: [],
              reffee: 15,
              fbafee: 3.02,
              delivery: 0,
              fbaamount: 102,
              status: 70,
              icomment: 'нашел штуковину',
              images: [
                '41XJDPBQjaL',
                '31lOSWNvBQL',
                '412A5g5mUyL',
                '41Jjj5Ey_2BPL',
                '61n87x1vPlL',
                '61kwyovi_2BCL',
                '718H7g671qL',
              ],
              checkednotes: 'ничего такая штука\nнорм поставщик',
              dirdecision: 0,
              amazonDescription: '',
              amazonDetail:
                ' Product information Product Dimensions 6.3 x 0.79 x 0.79 inches Item model number 3400875 ASIN B01D3ZU5I0 Customer Reviews 4.7 out of 5 stars 1,257 ratings 4.7 out of 5 stars Best Sellers Rank #3,163 in Arts, Crafts & Sewing (See Top 100 in Arts, Crafts & Sewing) #1 in Latch Hook Supplies Is Discontinued By Manufacturer No Item Weight 2.12 ounces Manufacturer eBoot Date First Available March 18, 2016 Warranty & Support Product Warranty: For warranty information about this product, please click here Feedback Would you like to tell us about a lower price? ',
              amazonTitle: 'eBoot 6.5 Inch Wooden Bent Latch Hook Tool, Set of 3',
              minpurchase: 2.2629,
              profit: 0,
              margin: 0,
              createdby: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              createdat: '2021-07-01T15:32:23.000Z',
              updateDate: '2021-07-01T16:10:10.000Z',
              checkedat: '2021-07-01T15:40:57.000Z',
              buyer: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              buyerscomment: 'нашел поставщика',
            },
            amount: 10,
            order: '60dde8e2638c0d3917ec775b',
          },
        ],
        isDraft: false,
        images: [],
      },
      {
        _id: '60de14db638c0d3917ec776a',
        lengthCm: 0,
        widthCm: 0,
        heightCm: 0,
        warehouse: 35,
        deliveryMethod: 2,
        lengthCmSupplier: 39,
        widthCmSupplier: 41,
        heightCmSupplier: 40,
        weighGrossKgSupplier: 42,
        volumeWeightKgSupplier: 12.792,
        weightFinalAccountingKgSupplier: 42,
        status: 0,
        createdBy: '60aabf69b2f06d5a147ba009',
        lastModifiedBy: '60aabf69b2f06d5a147ba009',
        items: [
          {
            product: {
              _id: '60dde007638c0d3917ec7757',
              id: 'B01D3ZU5I0',
              material: 'default_material',
              category: 'gl_home',
              lamazon:
                'https://www.amazon.com/eBoot-Inch-Wooden-Bent-Latch/dp/B01D3ZU5I0/ref=sr_1_24?dchild=1&qid=1625047838&s=arts-crafts-intl-ship&sr=1-24',
              bsr: 3,
              fba: false,
              express: false,
              amazon: 7.99,
              height: 8.46,
              width: 4.53,
              length: 1.06,
              weight: 0.131995272,
              supplier: [],
              reffee: 15,
              fbafee: 3.02,
              delivery: 0,
              fbaamount: 102,
              status: 70,
              icomment: 'нашел штуковину',
              images: [
                '41XJDPBQjaL',
                '31lOSWNvBQL',
                '412A5g5mUyL',
                '41Jjj5Ey_2BPL',
                '61n87x1vPlL',
                '61kwyovi_2BCL',
                '718H7g671qL',
              ],
              checkednotes: 'ничего такая штука\nнорм поставщик',
              dirdecision: 0,
              amazonDescription: '',
              amazonDetail:
                ' Product information Product Dimensions 6.3 x 0.79 x 0.79 inches Item model number 3400875 ASIN B01D3ZU5I0 Customer Reviews 4.7 out of 5 stars 1,257 ratings 4.7 out of 5 stars Best Sellers Rank #3,163 in Arts, Crafts & Sewing (See Top 100 in Arts, Crafts & Sewing) #1 in Latch Hook Supplies Is Discontinued By Manufacturer No Item Weight 2.12 ounces Manufacturer eBoot Date First Available March 18, 2016 Warranty & Support Product Warranty: For warranty information about this product, please click here Feedback Would you like to tell us about a lower price? ',
              amazonTitle: 'eBoot 6.5 Inch Wooden Bent Latch Hook Tool, Set of 3',
              minpurchase: 2.2629,
              profit: 0,
              margin: 0,
              createdby: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              createdat: '2021-07-01T15:32:23.000Z',
              updateDate: '2021-07-01T16:10:10.000Z',
              checkedat: '2021-07-01T15:40:57.000Z',
              buyer: {
                _id: '60aabf69b2f06d5a147ba009',
                name: 'buyer1',
                email: 'buyer1@gmail.com',
                role: 40,
                fba: false,
                active: true,
                rate: 1000,
              },
              buyerscomment: 'нашел поставщика',
            },
            amount: 69,
            order: '60dde8e2638c0d3917ec775b',
          },
        ],
        isDraft: false,
        images: [],
      },
    ],
  },
]

export const BUYER_USER_HEADER_LIST = {
  countInvestors: {value: '255', text: 'Количество инвесторов'},
  foundGoods: {value: '875', text: 'Товаров нашел'},
  volumeTrans: {value: '$ 7555', text: 'Объем сделок'},
  earned: {value: '$ 1255', text: 'Заработано'},
  addInSave: {value: '12 инвесторов', text: 'Добавили в избранное'},
  inBlocked: {value: '12 инвесторов', text: 'Заблокирован(-а)'},
  youBlocked: {value: '14 инвесторов', text: 'Заблокировал(-а)'},
  createAc: {value: '11 инвесторов', text: 'Аккаунт создан'},
}

export const BUYER_USER_MANAGERS_LIST = [
  {value: 'Дмитрий', text: 'Дмитрий'},
  {value: 'Георгий', text: 'Георгий'},
  {value: 'subuser0', text: 'subuser0'},
  {value: 'subuser1', text: 'subuser1'},
  {value: 'subuser2', text: 'subuser2'},
]

export const CLIENT_USER_MANAGERS_LIST = [
  {value: 'Дмитрий', text: 'Дмитрий'},
  {value: 'Георгий', text: 'Георгий'},
  {value: 'subuser0', text: 'subuser0'},
  {value: 'subuser1', text: 'subuser1'},
  {value: 'subuser2', text: 'subuser2'},
]

export const BUYER_MY_PRODUCTS_HEAD_CELLS = [
  {id: 'asin', align: 'center', disablePadding: true, label: 'ASIN'},
  {id: 'price', align: 'right', disablePadding: false, label: 'Price'},
  {id: 'fees', align: 'left', disablePadding: false, label: 'Fees & Net'},
  {id: 'profit', align: 'right', disablePadding: false, label: 'Profit'},
  {id: 'amazonPrice', align: 'right', disablePadding: false, label: 'Amazon $'},
  {id: 'bsr', align: 'right', disablePadding: false, label: 'BSR'},
  {id: 'fba', align: 'right', disablePadding: false, label: 'FBA'},
]

export const FREE_ORDERS_TABLE_HEADERS = [
  'Статус',
  'Товар',
  'Создан',
  'Изменён',
  'Склад',
  'Способ доставки',
  'Комментарий клиента',
  'Комментарий байера',
]

export const BUYER_EMPTY_SUPPLIER = {
  name: '',
  link: '',
  price: 0,
  deliveryPrice: 0,
  qty: 0,
  minQty: 0,
  comment: '',
}

export const BUYER_SUB_USERS_INITIAL_DATA = [
  {date: '12/09/2019', email: 'email@example.com'},
  {date: '29/11/2017', email: 'email@example.com'},
  {date: '03/02/2020', email: 'email@example.com'},
]

export const ADMIN_USERS_INITIAL_DATA = [
  {
    id: 1,
    date: '12/09/2019',
    email: 'email@example.com',
    bussinesUnit: 'YES',
    name: 'Anton',
    rate: 1,
  },
  {
    id: 2,
    date: '29/11/2017',
    email: 'email@example.com',
    bussinesUnit: '',
    name: 'Morty',
    rate: 1,
  },
  {
    id: 3,
    date: '03/02/2020',
    email: 'email@example.com',
    bussinesUnit: 'YES',
    name: 'Rick',
    rate: 1,
  },
  {
    id: 4,
    date: '12/09/2019',
    email: 'email@example.com',
    bussinesUnit: 'YES',
    name: 'Anton',
    rate: 1,
  },
  {
    id: 5,
    date: '29/11/2017',
    email: 'email@example.com',
    bussinesUnit: '',
    name: 'Morty',
    rate: 1,
  },
  {
    id: 6,
    date: '03/02/2020',
    email: 'email@example.com',
    bussinesUnit: 'YES',
    name: 'Rick',
    rate: 1,
  },
]

export const BUYER_SUB_USERS_TABLE_CELLS = [
  {id: 'created', label: 'Created'},
  {id: 'email', label: 'Email'},
  {id: 'bu', label: 'Bussines unit'},
  {id: 'admin', label: 'Admin'},
]

export const CLIENT_SUB_USERS_TABLE_CELLS = [
  {id: 'created', label: 'Created'},
  {id: 'email', label: 'Email'},
  {id: 'bu', label: 'Bussines unit'},
  {id: 'admin', label: 'Admin'},
]

export const BUYER_USER_INITIAL_LIST = [
  {
    categoryImg: '/assets/img/categories/homeAndKitchen.jpg',
    category: 'Home & Kitchen',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/sportsAndOutdoors.jpg',
    category: 'Sports & Outdoors',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/toysAndGames.jpg',
    category: 'Toys & Games',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/healthHouseholdAndBabyCare.jpg',
    category: 'Health, Household & Baby Care',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/beautyAndPersonalCare.jpg',
    category: 'Beauty & Personal Care',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/kitchenAndDining.jpg',
    category: 'Kitchen & Dining',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/clothingShoesAndJewelry.jpg',
    category: 'Clothing, Shoes & Jewelry',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/baby.jpg',
    category: 'Baby',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/gardenAndOutdoor.jpg',
    category: 'Garden & Outdoor',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/toolsAndHomeImprovement.jpg',
    category: 'Tools & Home Improvement',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
]

export const CLIENT_USER_INITIAL_LIST = [
  {
    categoryImg: '/assets/img/categories/homeAndKitchen.jpg',
    category: 'Home & Kitchen',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/sportsAndOutdoors.jpg',
    category: 'Sports & Outdoors',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/toysAndGames.jpg',
    category: 'Toys & Games',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/healthHouseholdAndBabyCare.jpg',
    category: 'Health, Household & Baby Care',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/beautyAndPersonalCare.jpg',
    category: 'Beauty & Personal Care',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/kitchenAndDining.jpg',
    category: 'Kitchen & Dining',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/clothingShoesAndJewelry.jpg',
    category: 'Clothing, Shoes & Jewelry',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/baby.jpg',
    category: 'Baby',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/gardenAndOutdoor.jpg',
    category: 'Garden & Outdoor',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
  {
    categoryImg: '/assets/img/categories/toolsAndHomeImprovement.jpg',
    category: 'Tools & Home Improvement',
    price: 9.99,
    deliveryPrice: 34.99,
    avgPrice: 9.99,
    recConsignmentQty: 500,
    recConsignmentWeight: 450,
    avgBSR: 1900,
    avgReviews: 255,
    avgRevenue: 1000,
    qty: 450,
  },
]

export const BUYER_USER_INITIAL_USER = {
  img: 'https://fl-club.com/wp-content/uploads/2016/10/Igrovoy-noutbuk-2016-za-40000-rubley-kakoy-luchshe-720x380.jpg',
  username: 'Username',
  status: 'Принимаю заказы на ресерч',
}

export const CLIENT_USER_INITIAL_USER = {
  img: 'https://fl-club.com/wp-content/uploads/2016/10/Igrovoy-noutbuk-2016-za-40000-rubley-kakoy-luchshe-720x380.jpg',
  username: 'Username',
  status: 'Принимаю заказы на ресерч',
}

export const USER_HEAD_CELL = [
  {id: 'image', label: 'Image'},
  {id: 'image', label: 'Category'},
  {id: 'image', label: 'Цена'},
  {id: 'image', label: 'Кол-во'},
  {id: 'image', label: 'Средняя цена'},
  {id: 'image', label: 'Рекомендуемая партия'},
  {id: 'image', label: 'Вес'},
  {id: 'image', label: 'avg BSR'},
  {id: 'image', label: 'avg Reviews'},
  {id: 'image', label: 'avg Revenue'},
  {id: 'image', label: 'Стоимость запуска'},
  {id: 'image', label: 'Аккаунт менеджер'},
]

export const DELIVERY_TYPES = [
  {value: 'road', label: 'Автомобильный'},
  {value: 'sea', label: 'Морской'},
  {value: 'train', label: 'Железнодорожный'},
  {value: 'air', label: 'Авиационный'},
  {value: 'multiple', label: 'Мультимодальный'},
]

export const CLIENT_INVENTORY_MY_PRODUCTS_HEAD_CELLS = [
  {id: 'asin', align: 'center', disablePadding: true, label: 'ASIN'},
  {id: 'price', align: 'right', disablePadding: false, label: 'Price'},
  {id: 'createDate', align: 'left', disablePadding: false, label: 'Create date'},
  {id: 'checkDate', align: 'right', disablePadding: false, label: 'Check date'},
  {id: 'profit', align: 'center', disablePadding: false, label: 'Profit'},
  {id: 'margin', align: 'right', disablePadding: false, label: 'Margin'},
  {id: 'bsr', align: 'center', disablePadding: false, label: 'BSR'},
  {id: 'fbaAmount', align: 'right', disablePadding: false, label: 'Fba amount'},
]

export const SUPERVISOR_PRODUCTS_HEAD_CELLS = [
  {id: 'asin', align: 'center', disablePadding: true, label: 'ASIN'},
  {id: 'price', align: 'right', disablePadding: false, label: 'Price'},
  {id: 'fees', align: 'left', disablePadding: false, label: 'Fees & Net'},
  {id: 'rank', align: 'right', disablePadding: false, label: 'Rank'},
  {id: 'rating', align: 'center', disablePadding: false, label: 'Rating'},
  {id: 'sales', align: 'right', disablePadding: false, label: 'Sales'},
  {id: 'salersTotal', align: 'center', disablePadding: false, label: 'Salers total'},
  {id: 'type', align: 'right', disablePadding: false, label: 'Type'},
  {id: 'revenue', align: 'right', disablePadding: false, label: 'Revenue'},
  {id: 'amazonPrice', align: 'right', disablePadding: false, label: 'Amazon $'},
  {id: 'bsr', align: 'right', disablePadding: false, label: 'BSR'},
  {id: 'fba', align: 'right', disablePadding: false, label: 'FBA'},
]

export const HISTORY_DATA = [
  {
    date: '13-12-2020 20:50',
    type: 'task/merge',
    orders: ['ID590101', 'ID590102'],
    status: true,
  },
  {date: '13-12-2020 20:50', type: 'change/status/Оплачен', orders: ['ID590101'], status: null},
  {
    date: '13-12-2020 20:50',
    type: 'task/divide',
    orders: ['ID590101', 'ID590102'],
    status: false,
  },
]

export const VACANT_TASKS_DATA = [
  {
    taskId: '001',
    date: '13-12-2020 20:50',
    type: 'divide',
    status: false,
    incomingBoxes: [
      {
        _id: 'sdf3sa3df4sf234hdf',
        lengthCm: 10,
        widthCm: 10,
        heightCm: 10,
        weighGrossKg: 15.5,
        volumeWeightKg: 25.5,
        weightFinalAccountingKg: 25.5,
        shippingLabel: 'https://www.mf.com/sdkfjasldf.pdf',
        shipmentPlanId: '12WEER234',
        warehouse: 25,
        deliveryMethod: 25,
        isActual: true,
        lengthCmSupplier: 25,
        widthCmSupplier: 35,
        heightCmSupplier: 45,
        weighGrossKgSupplier: 45,
        volumeWeightKgSupplier: 15,
        weightFinalAccountingKgSupplier: 25,
        status: 25,

        boxId: '346',
        chip: '432445d324fv1',
        lengthCmWarehouse: 3,
        widthCmWarehouse: 4,
        heightCmWarehouse: 1,
        volumeWeightKgWarehouse: 5,
        weightFinalAccountingKgWarehouse: 40,
        images: ['/assets/img/categories/homeAndKitchen.jpg', '/assets/img/categories/healthHouseholdAndBabyCare.jpg'],
        barCode: '432445d324fv1',
        amount: '42',
        product: {
          img: '/assets/img/categories/homeAndKitchen.jpg',
          amazonTitle: 'Чудо штука!',
          material: 'steel',
        },
      },
    ],
    desiredBoxes: [
      {
        _id: 'sdf3sa3df4sf234hdf',
        lengthCm: 10,
        widthCm: 10,
        heightCm: 10,
        weighGrossKg: 15.5,
        volumeWeightKg: 25.5,
        weightFinalAccountingKg: 25.5,
        shippingLabel: 'https://www.mf.com/sdkfjasldf.pdf',
        shipmentPlanId: '12WEER234',
        warehouse: 25,
        deliveryMethod: 25,
        isActual: true,
        lengthCmSupplier: 25,
        widthCmSupplier: 35,
        heightCmSupplier: 45,
        weighGrossKgSupplier: 45,
        volumeWeightKgSupplier: 15,
        weightFinalAccountingKgSupplier: 25,
        status: 25,

        boxId: '347',
        chip: false,
        lengthCmWarehouse: 0,
        widthCmWarehouse: 0,
        heightCmWarehouse: 0,
        volumeWeightKgWarehouse: 0,
        weightFinalAccountingKgWarehouse: 0,
        images: ['/assets/img/categories/homeAndKitchen.jpg', '/assets/img/categories/healthHouseholdAndBabyCare.jpg'],
        barCode: 'barcode-none',
        amount: '22',
        product: {
          img: '/assets/img/categories/homeAndKitchen.jpg',
          amazonTitle: 'Чудо штука!',
          material: 'steel',
        },
      },
      {
        _id: 'sdf3sa3df4sf234hdf',
        lengthCm: 10,
        widthCm: 10,
        heightCm: 10,
        weighGrossKg: 15.5,
        volumeWeightKg: 25.5,
        weightFinalAccountingKg: 25.5,
        shippingLabel: 'https://www.mf.com/sdkfjasldf.pdf',
        shipmentPlanId: '12WEER234',
        warehouse: 25,
        deliveryMethod: 25,
        isActual: true,
        lengthCmSupplier: 25,
        widthCmSupplier: 35,
        heightCmSupplier: 45,
        weighGrossKgSupplier: 45,
        volumeWeightKgSupplier: 15,
        weightFinalAccountingKgSupplier: 25,
        status: 25,

        boxId: '348',
        chip: false,
        lengthCmWarehouse: 0,
        widthCmWarehouse: 0,
        heightCmWarehouse: 0,
        volumeWeightKgWarehouse: 0,
        weightFinalAccountingKgWarehouse: 0,
        images: ['/assets/img/categories/homeAndKitchen.jpg', '/assets/img/categories/healthHouseholdAndBabyCare.jpg'],
        barCode: 'barcode-none',
        amount: '20',
        product: {
          img: '/assets/img/categories/homeAndKitchen.jpg',
          amazonTitle: 'Чудо штука!',
          material: 'steel',
        },
      },
    ],
  },

  {
    taskId: '002',
    date: '14-12-2020 20:50',
    type: 'merge',
    status: false,
    incomingBoxes: [
      {
        _id: 'sdf3sa3df4sf234hdf',
        lengthCm: 10,
        widthCm: 10,
        heightCm: 10,
        weighGrossKg: 15.5,
        volumeWeightKg: 25.5,
        weightFinalAccountingKg: 25.5,
        shippingLabel: 'https://www.mf.com/sdkfjasldf.pdf',
        shipmentPlanId: '12WEER234',
        warehouse: 25,
        deliveryMethod: 25,
        isActual: true,
        lengthCmSupplier: 25,
        widthCmSupplier: 35,
        heightCmSupplier: 45,
        weighGrossKgSupplier: 45,
        volumeWeightKgSupplier: 15,
        weightFinalAccountingKgSupplier: 25,
        status: 25,

        boxId: '347',
        chip: false,
        lengthCmWarehouse: 4,
        widthCmWarehouse: 3,
        heightCmWarehouse: 5,
        volumeWeightKgWarehouse: 4,
        weightFinalAccountingKgWarehouse: 20,
        images: ['/assets/img/categories/homeAndKitchen.jpg', '/assets/img/categories/healthHouseholdAndBabyCare.jpg'],
        barCode: 'barcode-none',
        amount: '22',
        product: {
          img: '/assets/img/categories/homeAndKitchen.jpg',
          amazonTitle: 'Чудо штука!',
          material: 'steel',
        },
      },
      {
        _id: 'sdf3sa3df4sf234hdf',
        lengthCm: 10,
        widthCm: 10,
        heightCm: 10,
        weighGrossKg: 15.5,
        volumeWeightKg: 25.5,
        weightFinalAccountingKg: 25.5,
        shippingLabel: 'https://www.mf.com/sdkfjasldf.pdf',
        shipmentPlanId: '12WEER234',
        warehouse: 25,
        deliveryMethod: 25,
        isActual: true,
        lengthCmSupplier: 25,
        widthCmSupplier: 35,
        heightCmSupplier: 45,
        weighGrossKgSupplier: 45,
        volumeWeightKgSupplier: 15,
        weightFinalAccountingKgSupplier: 25,
        status: 25,

        boxId: '348',
        chip: false,
        lengthCmWarehouse: 3,
        widthCmWarehouse: 2,
        heightCmWarehouse: 5,
        volumeWeightKgWarehouse: 10,
        weightFinalAccountingKgWarehouse: 25,
        images: ['/assets/img/categories/homeAndKitchen.jpg', '/assets/img/categories/healthHouseholdAndBabyCare.jpg'],
        barCode: 'barcode-none',
        amount: '20',
        product: {
          img: '/assets/img/categories/homeAndKitchen.jpg',
          amazonTitle: 'Чудо штука!',
          material: 'steel',
        },
        createdBy: 25,
        buyerId: '60817661a451519a1f5b1492',
        lastModifiedBy: '60817661a451519a1f5b1492',
      },
    ],
    desiredBoxes: [
      {
        _id: 'sdf3sa3df4sf234hdf',
        lengthCm: 10,
        widthCm: 10,
        heightCm: 10,
        weighGrossKg: 15.5,
        volumeWeightKg: 25.5,
        weightFinalAccountingKg: 25.5,
        shippingLabel: 'https://www.mf.com/sdkfjasldf.pdf',
        shipmentPlanId: '12WEER234',
        warehouse: 25,
        deliveryMethod: 25,
        isActual: true,
        lengthCmSupplier: 25,
        widthCmSupplier: 35,
        heightCmSupplier: 45,
        weighGrossKgSupplier: 45,
        volumeWeightKgSupplier: 15,
        weightFinalAccountingKgSupplier: 25,
        status: 25,

        boxId: '346',
        chip: '432445d324fv1',
        lengthCmWarehouse: 0,
        widthCmWarehouse: 0,
        heightCmWarehouse: 0,
        volumeWeightKgWarehouse: 0,
        weightFinalAccountingKgWarehouse: 0,
        images: ['/assets/img/categories/homeAndKitchen.jpg', '/assets/img/categories/healthHouseholdAndBabyCare.jpg'],
        barCode: '432445d324fv1',
        amount: '42',
        product: {
          img: '/assets/img/categories/homeAndKitchen.jpg',
          amazonTitle: 'Чудо штука!',
          material: 'steel',
        },
        createdBy: 25,
        buyerId: '60817661a451519a1f5b1492',
        lastModifiedBy: '60817661a451519a1f5b1492',
      },
    ],
  },

  {
    taskId: '003',
    date: '15-12-2020 20:50',
    type: 'receive ',
    status: false,
    incomingBoxes: [
      {
        _id: 'sdf3sa3df4sf234hdf',
        lengthCm: 10,
        widthCm: 10,
        heightCm: 10,
        weighGrossKg: 15.5,
        volumeWeightKg: 25.5,
        weightFinalAccountingKg: 25.5,
        shippingLabel: 'https://www.mf.com/sdkfjasldf.pdf',
        shipmentPlanId: '12WEER234',
        warehouse: 25,
        deliveryMethod: 25,
        isActual: true,
        lengthCmSupplier: 25,
        widthCmSupplier: 35,
        heightCmSupplier: 45,
        weighGrossKgSupplier: 45,
        volumeWeightKgSupplier: 15,
        weightFinalAccountingKgSupplier: 25,
        status: 25,

        boxId: '400',
        chip: '432445d324fv1',
        lengthCmWarehouse: 8,
        widthCmWarehouse: 4,
        heightCmWarehouse: 7,
        volumeWeightKgWarehouse: 50,
        weightFinalAccountingKgWarehouse: 137,
        images: ['/assets/img/categories/homeAndKitchen.jpg', '/assets/img/categories/healthHouseholdAndBabyCare.jpg'],
        barCode: '432445d324fv1',
        amount: '17',
        product: {
          img: '/assets/img/categories/homeAndKitchen.jpg',
          amazonTitle: 'Мега дрель',
          material: 'steel',
        },
        createdBy: 25,
        buyerId: '60817661a451519a1f5b1492',
        lastModifiedBy: '60817661a451519a1f5b1492',
      },
    ],
    desiredBoxes: [
      {
        _id: 'sdf3sa3df4sf234hdf',
        lengthCm: 10,
        widthCm: 10,
        heightCm: 10,
        weighGrossKg: 15.5,
        volumeWeightKg: 25.5,
        weightFinalAccountingKg: 25.5,
        shippingLabel: 'https://www.mf.com/sdkfjasldf.pdf',
        shipmentPlanId: '12WEER234',
        warehouse: 25,
        deliveryMethod: 25,
        isActual: true,
        lengthCmSupplier: 25,
        widthCmSupplier: 35,
        heightCmSupplier: 45,
        weighGrossKgSupplier: 45,
        volumeWeightKgSupplier: 15,
        weightFinalAccountingKgSupplier: 25,
        status: 25,

        boxId: '400',
        chip: '432445d324fv1',
        lengthCmWarehouse: 0,
        widthCmWarehouse: 0,
        heightCmWarehouse: 0,
        volumeWeightKgWarehouse: 0,
        weightFinalAccountingKgWarehouse: 0,
        images: ['/assets/img/categories/homeAndKitchen.jpg', '/assets/img/categories/healthHouseholdAndBabyCare.jpg'],
        barCode: 'barcode-none',
        amount: '17',
        product: {
          img: '/assets/img/categories/homeAndKitchen.jpg',
          amazonTitle: 'Мега дрель',
          material: 'steel',
        },
        createdBy: 25,
        buyerId: '60817661a451519a1f5b1492',
        lastModifiedBy: '60817661a451519a1f5b1492',
      },
    ],
  },
  {
    taskId: '004',
    date: '16-12-2020 20:50',
    type: 'receive ',
    status: true,
    incomingBoxes: [
      {
        _id: 'sdf3sa3df4sf234hdf',
        lengthCm: 10,
        widthCm: 10,
        heightCm: 10,
        weighGrossKg: 15.5,
        volumeWeightKg: 25.5,
        weightFinalAccountingKg: 25.5,
        shippingLabel: 'https://www.mf.com/sdkfjasldf.pdf',
        shipmentPlanId: '12WEER234',
        warehouse: 25,
        deliveryMethod: 25,
        isActual: true,
        lengthCmSupplier: 25,
        widthCmSupplier: 35,
        heightCmSupplier: 45,
        weighGrossKgSupplier: 45,
        volumeWeightKgSupplier: 15,
        weightFinalAccountingKgSupplier: 25,
        status: 25,

        boxId: '401',
        chip: '432445d324fv1',
        lengthCmWarehouse: 8,
        widthCmWarehouse: 4,
        heightCmWarehouse: 7,
        volumeWeightKgWarehouse: 50,
        weightFinalAccountingKgWarehouse: 137,
        images: ['/assets/img/categories/homeAndKitchen.jpg', '/assets/img/categories/healthHouseholdAndBabyCare.jpg'],
        barCode: '432445d324fv1',
        amount: '50',
        product: {
          img: '/assets/img/categories/homeAndKitchen.jpg',
          amazonTitle: 'Набор молотков',
          material: 'steel',
        },
        createdBy: 25,
        buyerId: '60817661a451519a1f5b1492',
        lastModifiedBy: '60817661a451519a1f5b1492',
      },
    ],
    desiredBoxes: [
      {
        _id: 'sdf3sa3df4sf234hdf',
        lengthCm: 10,
        widthCm: 10,
        heightCm: 10,
        weighGrossKg: 15.5,
        volumeWeightKg: 25.5,
        weightFinalAccountingKg: 25.5,
        shippingLabel: 'https://www.mf.com/sdkfjasldf.pdf',
        shipmentPlanId: '12WEER234',
        warehouse: 25,
        deliveryMethod: 25,
        isActual: true,
        lengthCmSupplier: 25,
        widthCmSupplier: 35,
        heightCmSupplier: 45,
        weighGrossKgSupplier: 45,
        volumeWeightKgSupplier: 15,
        weightFinalAccountingKgSupplier: 25,
        status: 25,

        boxId: '401',
        chip: false,
        lengthCmWarehouse: 8,
        widthCmWarehouse: 4,
        heightCmWarehouse: 7,
        volumeWeightKgWarehouse: 50,
        weightFinalAccountingKgWarehouse: 137,
        images: ['/assets/img/categories/homeAndKitchen.jpg', '/assets/img/categories/healthHouseholdAndBabyCare.jpg'],
        barCode: 'barcode-none',
        amount: '50',
        product: {
          img: '/assets/img/categories/homeAndKitchen.jpg',
          amazonTitle: 'Набор молотков',
          material: 'steel',
        },
        createdBy: 25,
        buyerId: '60817661a451519a1f5b1492',
        lastModifiedBy: '60817661a451519a1f5b1492',
      },
    ],
  },
]

export const WAREHOUSE_TASKS_HEAD_CELLS = [
  // {title: 'Id'},
  {title: 'Дата'},
  {title: 'Тип задачи'},
  {title: 'Описание'},
  {title: 'Действия'},
  {title: 'Статус'},
]

export const DELIVERY_LIST = [
  {value: 'road', text: 'Автомобильный'},
  {value: 'sea', text: 'Морской'},
  {value: 'train', text: 'Железнодорожный'},
  {value: 'air', text: 'Авиационный'},
  {value: 'multiple', text: 'Мультимодальный'},
]

export const ADMIN_BALANCE_HISTORY_DATA = [
  {
    date: 'Дата',
    amount: '142',
    type: 'replenish',
    comment: 'Комментарий',
    reason: 'Причина',
    username: 'Имя пользователя',
  },
  {
    date: 'Дата2',
    amount: '512',
    type: 'withdraw',
    comment: 'Комментарий',
    reason: 'Причина',
    username: 'Имя пользователя',
  },
]

export const ADMIN_ORDERS = [
  {
    deliveryCostToTheWarehouse: 0,
    isBarCodeAlreadyAttachedByTheSupplier: false,
    amountPaymentPerConsignmentAtDollars: 0,
    status: 15,
    id: '60c917263e61ce683c68f66c',
    amount: 2,
    deliveryMethod: 2,
    warehouse: 42,
    clientComment: '',
    barCode: '123',
    product: {
      material: 'default_material',
      fba: false,
      express: false,
      supplier: ['60c917013e61ce683c68f668'],
      reffee: 15,
      status: 70,
      dirdecision: 0,
      images: [],
      _id: '60c916d53e61ce683c68f667',
      id: 'B07Z7MF3HQ',
      lamazon:
        'https://www.amazon.com/dp/B07Z7MF3HQ/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B07Z7MF3HQ&pd_rd_w=lNtu6&pf_rd_p=5d846283-ed3e-4512-a744-a30f97c5d738&pd_rd_wg=zdyHk&pf_rd_r=HN1GVMXCZYM4P6T356Q6&pd_rd_r=e238354b-440d-4b54-bf15-5c3e36f7ba11&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFLUEU0RTdJVUdaMEomZW5jcnlwdGVkSWQ9QTA0NTkwNzkyN0VDREtUM0VJOTcyJmVuY3J5cHRlZEFkSWQ9QTAzNTM5NjIzUUIxNkFONFlUNjgxJndpZGdldE5hbWU9c3BfZGV0YWlsX3RoZW1hdGljJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==',
      lsupplier: '',
      bsr: 0,
      amazon: 0,
      fbafee: 0,
      delivery: 0,
      icomment: '',
      createdat: '2021-06-15T21:08:37.000Z',
      createdby: '60aabf69b2f06d5a147ba009',
      __v: 0,
      checkedby: '60aabf69b2f06d5a147ba009',
      checkedat: '2021-06-15T21:09:45.000Z',
      checkednotes: 'Test super',
      buyer: '60aabf69b2f06d5a147ba009',
      buyerscomment: 'Test',
      dircheckedby: '60aabf69b2f06d5a147ba009',
      paidby: '60aabf69b2f06d5a147ba009',
      paidat: '2021-06-15T21:09:58.000Z',
    },
    createdBy: '60aabf69b2f06d5a147ba009',
    lastModifiedBy: '60aabf69b2f06d5a147ba009',
    createDate: '2021-06-15T21:09:58.724Z',
    lastModifiedDate: '2021-06-15T22:26:29.330Z',
    __v: 0,
    buyerId: '60aabf69b2f06d5a147ba009',
  },
  {
    deliveryCostToTheWarehouse: 0,
    isBarCodeAlreadyAttachedByTheSupplier: false,
    amountPaymentPerConsignmentAtDollars: 0,
    status: 15,
    id: '60ca48863e61ce683c68f67c',
    amount: 1,
    deliveryMethod: 2,
    warehouse: 42,
    clientComment: '',
    barCode: '1233',
    product: {
      material: 'default_material',
      fba: false,
      express: false,
      supplier: ['60ca47ee3e61ce683c68f678'],
      reffee: 15,
      status: 70,
      dirdecision: 0,
      images: [],
      _id: '60ca47ac3e61ce683c68f677',
      id: 'B0817QLT89',
      lamazon:
        'https://www.amazon.com/TOCESS-Clips-Nonslip-Strong-Available/dp/B0817QLT89/ref=sr_1_8?dchild=1&fst=as%3Aoff&pf_rd_i=16225006011&pf_rd_m=ATVPDKIKX0DER&pf_rd_p=fd971cf1-cdbc-4301-8c91-0a56b1c1e13f&pf_rd_r=VCEK46M8C1RBMZ3K6VBQ&pf_rd_s=merchandised-search-4&pf_rd_t=101&qid=1623868977&rnid=16225006011&s=beauty-intl-ship&sr=1-8',
      lsupplier: 'http://test.com',
      bsr: 0,
      amazon: 0,
      fbafee: 0,
      delivery: 1,
      icomment: 'Super',
      createdat: '2021-06-16T18:49:16.000Z',
      createdby: '60aabf69b2f06d5a147ba009',
      __v: 0,
      checkedby: '60aabf69b2f06d5a147ba009',
      checkedat: '2021-06-16T18:51:29.000Z',
      checkednotes: 'Good, perfect',
      buyer: '60aabf69b2f06d5a147ba009',
      buyerscomment: 'Found',
      fbaamount: 2,
      dircheckedby: '60aabf69b2f06d5a147ba009',
      paidby: '60aabf69b2f06d5a147ba009',
      paidat: '2021-06-16T18:52:54.000Z',
    },
    createdBy: '60aabf69b2f06d5a147ba009',
    lastModifiedBy: '60aabf69b2f06d5a147ba009',
    createDate: '2021-06-16T18:52:54.646Z',
    lastModifiedDate: '2021-06-16T19:04:34.347Z',
    __v: 0,
    buyerId: '60aabf69b2f06d5a147ba009',
  },
  {
    deliveryCostToTheWarehouse: 0,
    isBarCodeAlreadyAttachedByTheSupplier: false,
    amountPaymentPerConsignmentAtDollars: 0,
    status: 15,
    id: '60ce3cca71d98c2508f91b73',
    amount: 4,
    deliveryMethod: 2,
    warehouse: 42,
    clientComment: '',
    barCode: '',
    product: {
      material: 'default_material',
      fba: false,
      express: false,
      supplier: ['60ce397471d98c2508f91b6f'],
      reffee: 15,
      status: 70,
      dirdecision: 0,
      images: [
        '31M9SoICXyL',
        '41FBOfQXu9L',
        '31IT598L1BL',
        '41dnJGxu_2B1L',
        '51zg0mgsrRL',
        '41T75YqQQnL',
        '41F37WZaPLL',
        '51WaY1BLs8L',
      ],
      _id: '60ce383171d98c2508f91b6e',
      id: 'B01M2U8JU9',
      lamazon:
        'https://www.amazon.com/Watcher-Programmable-Buttons-Ergonomic-Computer/dp/B01M2U8JU9/ref=sr_1_1_sspa?dchild=1&keywords=gaming+mouse&pd_rd_r=4c230c00-7790-43eb-a2b5-1f4df2c05ce1&pd_rd_w=EkCiB&pd_rd_wg=QUs80&pf_rd_p=5811f97a-f703-4231-aa5f-c344167bfe13&pf_rd_r=F5R6A0YC5NSKRQSNF40H&qid=1624127436&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzSkxJMlBWOEU2U1IzJmVuY3J5cHRlZElkPUEwMTQwNzM2MjVPMUNWSjY0NkgxQiZlbmNyeXB0ZWRBZElkPUEwNDg3NDIwMjZRQlA2RUs0MVBJMSZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=',
      lsupplier: 'http://test.com',
      bsr: 1,
      amazon: 19.99,
      fbafee: 0,
      delivery: 1,
      icomment: 'Интересный товар',
      createdat: '2021-06-19T18:32:17.000Z',
      createdby: '60aabf69b2f06d5a147ba009',
      __v: 0,
      profit: 1000,
      margin: 10,
      checkedby: '60aabf69b2f06d5a147ba009',
      checkedat: '2021-06-19T18:39:46.000Z',
      checkednotes: 'Работаем, отличный поставщик',
      buyer: '60aabf69b2f06d5a147ba009',
      fbaamount: 1,
      dircheckedby: '60aabf69b2f06d5a147ba009',
      paidby: '60aabf69b2f06d5a147ba009',
      paidat: '2021-06-19T18:51:54.000Z',
    },
    createdBy: '60aabf69b2f06d5a147ba009',
    lastModifiedBy: '60aabf69b2f06d5a147ba009',
    createDate: '2021-06-19T18:51:54.671Z',
    lastModifiedDate: '2021-06-19T18:51:54.671Z',
    __v: 0,
    buyerId: '60aabf69b2f06d5a147ba009',
  },
  {
    deliveryCostToTheWarehouse: 0,
    isBarCodeAlreadyAttachedByTheSupplier: false,
    amountPaymentPerConsignmentAtDollars: 0,
    status: 15,
    id: '60c917263e61ce683c68f644c',
    amount: 2,
    deliveryMethod: 2,
    warehouse: 42,
    clientComment: '',
    barCode: '123',
    product: {
      material: 'default_material',
      fba: false,
      express: false,
      supplier: ['60c917013e61ce683c68f668'],
      reffee: 15,
      status: 70,
      dirdecision: 0,
      images: [],
      _id: '60c916d53e61ce683c68f667',
      id: 'B07Z7MF3HQ',
      lamazon:
        'https://www.amazon.com/dp/B07Z7MF3HQ/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B07Z7MF3HQ&pd_rd_w=lNtu6&pf_rd_p=5d846283-ed3e-4512-a744-a30f97c5d738&pd_rd_wg=zdyHk&pf_rd_r=HN1GVMXCZYM4P6T356Q6&pd_rd_r=e238354b-440d-4b54-bf15-5c3e36f7ba11&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFLUEU0RTdJVUdaMEomZW5jcnlwdGVkSWQ9QTA0NTkwNzkyN0VDREtUM0VJOTcyJmVuY3J5cHRlZEFkSWQ9QTAzNTM5NjIzUUIxNkFONFlUNjgxJndpZGdldE5hbWU9c3BfZGV0YWlsX3RoZW1hdGljJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==',
      lsupplier: '',
      bsr: 0,
      amazon: 0,
      fbafee: 0,
      delivery: 0,
      icomment: '',
      createdat: '2021-06-15T21:08:37.000Z',
      createdby: '60aabf69b2f06d5a147ba009',
      __v: 0,
      checkedby: '60aabf69b2f06d5a147ba009',
      checkedat: '2021-06-15T21:09:45.000Z',
      checkednotes: 'Test super',
      buyer: '60aabf69b2f06d5a147ba009',
      buyerscomment: 'Test',
      dircheckedby: '60aabf69b2f06d5a147ba009',
      paidby: '60aabf69b2f06d5a147ba009',
      paidat: '2021-06-15T21:09:58.000Z',
    },
    createdBy: '60aabf69b2f06d5a147ba009',
    lastModifiedBy: '60aabf69b2f06d5a147ba009',
    createDate: '2021-06-15T21:09:58.724Z',
    lastModifiedDate: '2021-06-15T22:26:29.330Z',
    __v: 0,
    buyerId: '60aabf69b2f06d5a147ba009',
  },
  {
    deliveryCostToTheWarehouse: 0,
    isBarCodeAlreadyAttachedByTheSupplier: false,
    amountPaymentPerConsignmentAtDollars: 0,
    status: 15,
    id: '51c917263e61ce683c68f66c',
    amount: 2,
    deliveryMethod: 2,
    warehouse: 42,
    clientComment: '',
    barCode: '123',
    product: {
      material: 'default_material',
      fba: false,
      express: false,
      supplier: ['60c917013e61ce683c68f668'],
      reffee: 15,
      status: 70,
      dirdecision: 0,
      images: [],
      _id: '60c916d53e61ce683c68f667',
      id: 'B07Z7MF3HQ',
      lamazon:
        'https://www.amazon.com/dp/B07Z7MF3HQ/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B07Z7MF3HQ&pd_rd_w=lNtu6&pf_rd_p=5d846283-ed3e-4512-a744-a30f97c5d738&pd_rd_wg=zdyHk&pf_rd_r=HN1GVMXCZYM4P6T356Q6&pd_rd_r=e238354b-440d-4b54-bf15-5c3e36f7ba11&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFLUEU0RTdJVUdaMEomZW5jcnlwdGVkSWQ9QTA0NTkwNzkyN0VDREtUM0VJOTcyJmVuY3J5cHRlZEFkSWQ9QTAzNTM5NjIzUUIxNkFONFlUNjgxJndpZGdldE5hbWU9c3BfZGV0YWlsX3RoZW1hdGljJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==',
      lsupplier: '',
      bsr: 0,
      amazon: 0,
      fbafee: 0,
      delivery: 0,
      icomment: '',
      createdat: '2021-06-15T21:08:37.000Z',
      createdby: '60aabf69b2f06d5a147ba009',
      __v: 0,
      checkedby: '60aabf69b2f06d5a147ba009',
      checkedat: '2021-06-15T21:09:45.000Z',
      checkednotes: 'Test super',
      buyer: '60aabf69b2f06d5a147ba009',
      buyerscomment: 'Test',
      dircheckedby: '60aabf69b2f06d5a147ba009',
      paidby: '60aabf69b2f06d5a147ba009',
      paidat: '2021-06-15T21:09:58.000Z',
    },
    createdBy: '60aabf69b2f06d5a147ba009',
    lastModifiedBy: '60aabf69b2f06d5a147ba009',
    createDate: '2021-06-15T21:09:58.724Z',
    lastModifiedDate: '2021-06-15T22:26:29.330Z',
    __v: 0,
    buyerId: '60aabf69b2f06d5a147ba009',
  },
  {
    deliveryCostToTheWarehouse: 0,
    isBarCodeAlreadyAttachedByTheSupplier: false,
    amountPaymentPerConsignmentAtDollars: 0,
    status: 15,
    id: '60c917263e61wh683c68f66c',
    amount: 2,
    deliveryMethod: 2,
    warehouse: 42,
    clientComment: '',
    barCode: '123',
    product: {
      material: 'default_material',
      fba: false,
      express: false,
      supplier: ['60c917013e61ce683c68f668'],
      reffee: 15,
      status: 70,
      dirdecision: 0,
      images: [],
      _id: '60c916d53e61ce683c68f667',
      id: 'B07Z7MF3HQ',
      lamazon:
        'https://www.amazon.com/dp/B07Z7MF3HQ/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B07Z7MF3HQ&pd_rd_w=lNtu6&pf_rd_p=5d846283-ed3e-4512-a744-a30f97c5d738&pd_rd_wg=zdyHk&pf_rd_r=HN1GVMXCZYM4P6T356Q6&pd_rd_r=e238354b-440d-4b54-bf15-5c3e36f7ba11&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFLUEU0RTdJVUdaMEomZW5jcnlwdGVkSWQ9QTA0NTkwNzkyN0VDREtUM0VJOTcyJmVuY3J5cHRlZEFkSWQ9QTAzNTM5NjIzUUIxNkFONFlUNjgxJndpZGdldE5hbWU9c3BfZGV0YWlsX3RoZW1hdGljJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==',
      lsupplier: '',
      bsr: 0,
      amazon: 0,
      fbafee: 0,
      delivery: 0,
      icomment: '',
      createdat: '2021-06-15T21:08:37.000Z',
      createdby: '60aabf69b2f06d5a147ba009',
      __v: 0,
      checkedby: '60aabf69b2f06d5a147ba009',
      checkedat: '2021-06-15T21:09:45.000Z',
      checkednotes: 'Test super',
      buyer: '60aabf69b2f06d5a147ba009',
      buyerscomment: 'Test',
      dircheckedby: '60aabf69b2f06d5a147ba009',
      paidby: '60aabf69b2f06d5a147ba009',
      paidat: '2021-06-15T21:09:58.000Z',
    },
    createdBy: '60aabf69b2f06d5a147ba009',
    lastModifiedBy: '60aabf69b2f06d5a147ba009',
    createDate: '2021-06-15T21:09:58.724Z',
    lastModifiedDate: '2021-06-15T22:26:29.330Z',
    __v: 0,
    buyerId: '60aabf69b2f06d5a147ba009',
  },
]
