import {Block, DoneOutline, LocalConvenienceStore, Work} from '@material-ui/icons'
import AllInboxIcon from '@material-ui/icons/AllInbox'
import ArchiveOutlinedIcon from '@material-ui/icons/ArchiveOutlined'
import AssignmentIcon from '@material-ui/icons/Assignment'
import ChatBubbleOutlineOutlinedIcon from '@material-ui/icons/ChatBubbleOutlineOutlined'
import GavelIcon from '@material-ui/icons/Gavel'
import InboxOutlinedIcon from '@material-ui/icons/InboxOutlined'
import InfoOutlinedIcon from '@material-ui/icons/InfoOutlined'
import MonetizationOnOutlinedIcon from '@material-ui/icons/MonetizationOnOutlined'
import PeopleIcon from '@material-ui/icons/People'
import SettingsIcon from '@material-ui/icons/Settings'

import {isMasterUser} from '@utils/checks'

import {navBarActiveCategory} from './navbar-active-category'
import {UserRole} from './user-roles'

export const navbarConfig = {
  [UserRole.CLIENT]: [
    {
      icon: InfoOutlinedIcon,
      title: 'Главная страница',
      route: '/client/dashboard',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_DASHBOARD,
      checkHideBlock: () => true,
    },
    {
      icon: GavelIcon,
      title: 'Биржа товаров',
      route: '/client/exchange',
      subtitles: [
        {subtitle: 'Биржа вилок', subRoute: '/client/exchange'},
        {subtitle: 'Private Label', subRoute: '/client/exchange/private-label'},
      ],
      key: navBarActiveCategory.NAVBAR_EXCHANGE,
      checkHideBlock: () => true,
    },
    {
      icon: InboxOutlinedIcon,
      title: 'Инвентарь',
      route: '/client/inventory',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_INVENTORY,
      checkHideBlock: () => true,
    },
    {
      icon: Work,
      title: 'Мои заявки',
      route: '/client/exchange/requests/products',
      subtitles: [
        {subtitle: 'На поиск продукта', subRoute: '/client/exchange/requests/products'},
        {subtitle: 'На поиск ниши', subRoute: '/client/exchange/requests/niches'},
        {subtitle: 'Универсальные', subRoute: '/client/exchange/requests/custom'},
      ],
      key: navBarActiveCategory.NAVBAR_REQUESTS,
      checkHideBlock: () => true,
    },
    {
      icon: AssignmentIcon,
      title: 'Мои заказы',
      route: '/client/orders',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_MY_ORDERS,
      checkHideBlock: () => true,
    },
    {
      icon: ArchiveOutlinedIcon,
      title: 'Мой склад',
      route: '/client/warehouse',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_WAREHOUSE,
      checkHideBlock: () => true,
    },
    {
      icon: AllInboxIcon,
      title: 'Мои отправления',
      route: '/client/batches',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_BATCHES,
      checkHideBlock: () => true,
    },
    {
      icon: PeopleIcon,
      title: 'Пользователи',
      route: '/client/users/sub-users',
      subtitles: [{subtitle: 'Мои пользователи', subRoute: '/client/users/sub-users'}],
      key: navBarActiveCategory.NAVBAR_USERS,
      checkHideBlock: () => true,
    },
    {
      icon: SettingsIcon,
      title: 'Интеграции',
      route: '/client/integrations/daily',
      subtitles: [
        {subtitle: 'Отчет со склада', subRoute: '/client/integrations/daily'},
        {subtitle: 'Дашборд по товарам/дням', subRoute: '/client/integrations/last-30-day'},
      ],
      key: navBarActiveCategory.NAVBAR_INTEGRATIONS,
      checkHideBlock: () => true,
    },
    {
      icon: SettingsIcon,
      title: 'Настройки',
      route: '/client/settings',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_SETTINGS,
      checkHideBlock: () => true,
    },
    {
      icon: ChatBubbleOutlineOutlinedIcon,
      title: 'Сообщения',
      route: '/client/messages',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_MESSAGES,
      checkHideBlock: () => true,
    },
    {
      icon: MonetizationOnOutlinedIcon,
      title: 'Финансы',
      route: '/client/finances',
      subtitles: [
        {subtitle: 'Пополнения', subRoute: '/client/finances'},
        {subtitle: 'Списания', subRoute: '/client/finances'},
      ],
      key: navBarActiveCategory.NAVBAR_FINANCES,
      checkHideBlock: () => true,
    },
    {
      icon: ChatBubbleOutlineOutlinedIcon,
      title: 'Уведомления по заказам',
      route: '/client/orders-notifications',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_ORDERS_NOTIFICATIONS,
      checkHideBlock: () => true,
    },
  ],
  [UserRole.RESEARCHER]: [
    {
      icon: InfoOutlinedIcon,
      title: 'Главная страница',
      subtitles: null,
      route: '/researcher/dashboard',
      key: navBarActiveCategory.NAVBAR_DASHBOARD,
      checkHideBlock: () => true,
    },
    {
      icon: AssignmentIcon,
      title: 'Мои товары',
      subtitles: null,
      route: '/researcher/products',
      key: navBarActiveCategory.NAVBAR_MY_PRODUCTS,
      checkHideBlock: () => true,
    },
    {
      icon: AssignmentIcon,
      title: 'Заявки в работе',
      route: '/researcher/my-requests/products',
      subtitles: [
        {subtitle: 'На поиск продукта', subRoute: '/researcher/my-requests/products'},
        {subtitle: 'На поиск ниши', subRoute: '/researcher/my-requests/niches'},
        {subtitle: 'Универсальные', subRoute: '/researcher/my-requests/custom'},
      ],
      key: navBarActiveCategory.NAVBAR_MY_REQUESTS,
      checkHideBlock: () => true,
    },
    {
      icon: AssignmentIcon,
      title: 'Вакантные заявки',
      route: '/researcher/requests/products',
      subtitles: [
        {subtitle: 'На поиск продукта', subRoute: '/researcher/requests/products'},
        {subtitle: 'На поиск ниши', subRoute: '/researcher/requests/niches'},
        {subtitle: 'Универсальные', subRoute: '/researcher/requests/custom'},
      ],
      key: navBarActiveCategory.NAVBAR_VACANT_REQUESTS,
      checkHideBlock: () => true,
    },
    {
      icon: PeopleIcon,
      title: 'Пользователи',
      route: '/researcher/users/sub-users',
      subtitles: [{subtitle: 'Мои пользователи', subRoute: '/researcher/users/sub-users'}],
      key: navBarActiveCategory.NAVBAR_USERS,
      checkHideBlock: () => true,
    },
    {
      icon: SettingsIcon,
      title: 'Настройки',
      subtitles: null,
      route: '/researcher/settings',
      key: navBarActiveCategory.NAVBAR_SETTINGS,
      checkHideBlock: () => true,
    },
    {
      icon: MonetizationOnOutlinedIcon,
      title: 'Финансы',
      route: '/researcher/finances',
      subtitles: [
        {subtitle: 'Пополнения', subRoute: '/researcher/finances'},
        {subtitle: 'Списания', subRoute: '/researcher/finances'},
      ],
      key: navBarActiveCategory.NAVBAR_FINANCES,
      checkHideBlock: () => true,
    },
  ],
  [UserRole.FREELANCER]: [
    {
      icon: InfoOutlinedIcon,
      title: 'Главная страница',
      subtitles: null,
      route: '/freelancer/dashboard',
      key: navBarActiveCategory.NAVBAR_DASHBOARD,
      checkHideBlock: () => true,
    },
    {
      icon: AssignmentIcon,
      title: 'Заявки в работе',
      route: '/freelancer/my-requests/products',
      subtitles: [
        {subtitle: 'На поиск продукта', subRoute: '/freelancer/my-requests/products'},
        {subtitle: 'На поиск ниши', subRoute: '/freelancer/my-requests/niches'},
        {subtitle: 'Универсальные', subRoute: '/freelancer/my-requests/custom'},
      ],
      key: navBarActiveCategory.NAVBAR_MY_REQUESTS,
      checkHideBlock: user => !isMasterUser(user),
    },
    {
      icon: AssignmentIcon,
      title: 'Вакантные заявки',
      route: '/freelancer/requests/products',
      subtitles: [
        {subtitle: 'На поиск продукта', subRoute: '/freelancer/requests/products'},
        {subtitle: 'На поиск ниши', subRoute: '/freelancer/requests/niches'},
        {subtitle: 'Универсальные', subRoute: '/freelancer/requests/custom'},
      ],
      key: navBarActiveCategory.NAVBAR_VACANT_REQUESTS,
      checkHideBlock: () => true,
    },

    {
      icon: Work,
      title: 'Мои заявки',
      route: '/freelancer/exchange/requests/custom',
      subtitles: [{subtitle: 'Универсальные', subRoute: '/client/exchange/requests/custom'}],
      key: navBarActiveCategory.NAVBAR_REQUESTS,
      checkHideBlock: user => !isMasterUser(user),
    },
    {
      icon: MonetizationOnOutlinedIcon,
      title: 'Финансы',
      route: '/freelancer/finances',
      subtitles: [
        {subtitle: 'Пополнения', subRoute: '/freelancer/finances'},
        {subtitle: 'Списания', subRoute: '/freelancer/finances'},
      ],
      key: navBarActiveCategory.NAVBAR_FINANCES,
      checkHideBlock: () => true,
    },
  ],
  [UserRole.SUPERVISOR]: [
    {
      icon: InfoOutlinedIcon,
      title: 'Главная страница',
      subtitles: null,
      route: '/supervisor/dashboard',
      key: navBarActiveCategory.NAVBAR_DASHBOARD,
      checkHideBlock: () => true,
    },
    {
      icon: AssignmentIcon,
      title: 'Готовые к проверке',
      subtitles: null,
      route: '/supervisor/ready-to-check',
      key: navBarActiveCategory.NAVBAR_READY_TO_CHECK,
      checkHideBlock: () => true,
    },
    {
      icon: InboxOutlinedIcon,
      title: 'Мои товары',
      subtitles: null,
      route: '/supervisor/products',
      key: navBarActiveCategory.NAVBAR_MY_PRODUCTS,
      checkHideBlock: () => true,
    },
    {
      icon: PeopleIcon,
      title: 'Пользователи',
      route: '/supervisor/users/sub-users',
      subtitles: [{subtitle: 'Мои пользователи', subRoute: '/supervisor/users/sub-users'}],
      key: navBarActiveCategory.NAVBAR_USERS,
      checkHideBlock: () => true,
    },
    {
      icon: SettingsIcon,
      title: 'Настройки',
      subtitles: null,
      route: '/supervisor/settings',
      key: navBarActiveCategory.NAVBAR_SETTINGS,
      checkHideBlock: () => true,
    },
    {
      icon: MonetizationOnOutlinedIcon,
      title: 'Финансы',
      route: '/supervisor/finances',
      subtitles: [
        {subtitle: 'Пополнения', subRoute: '/supervisor/finances'},
        {subtitle: 'Списания', subRoute: '/supervisor/finances'},
      ],
      key: navBarActiveCategory.NAVBAR_FINANCES,
      checkHideBlock: () => true,
    },
  ],
  [UserRole.BUYER]: [
    {
      icon: InfoOutlinedIcon,
      title: 'Главная страница',
      subtitles: null,
      route: '/buyer/dashboard',
      key: navBarActiveCategory.NAVBAR_DASHBOARD,
      checkHideBlock: () => true,
    },

    {
      icon: InboxOutlinedIcon,
      title: 'Новые товары',
      route: '/buyer/products',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_NEW_PRODUCTS,
      checkHideBlock: () => true,
    },
    {
      icon: InboxOutlinedIcon,
      title: 'Мои товары',
      route: '/buyer/my-products',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_MY_PRODUCTS,
      checkHideBlock: () => true,
    },

    {
      icon: Work,
      title: 'Мои заказы',
      route: '/buyer/my-orders',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_MY_ORDERS,
      checkHideBlock: () => true,
    },
    {
      icon: AssignmentIcon,
      title: 'Свободные заказы',
      route: '/buyer/free-orders',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_FREE_ORDERS,
      checkHideBlock: () => true,
    },
    {
      icon: PeopleIcon,
      title: 'Пользователи',
      route: '/buyer/users/sub-users',
      subtitles: [{subtitle: 'Мои пользователи', subRoute: '/buyer/users/sub-users'}],
      key: navBarActiveCategory.NAVBAR_USERS,
      checkHideBlock: () => true,
    },
    {
      icon: MonetizationOnOutlinedIcon,
      title: 'Финансы',
      route: '/buyer/finances',
      subtitles: [
        {subtitle: 'Пополнения', subRoute: '/buyer/finances'},
        {subtitle: 'Списания', subRoute: '/buyer/finances'},
      ],
      key: navBarActiveCategory.NAVBAR_FINANCES,
      checkHideBlock: () => true,
    },
  ],
  [UserRole.STOREKEEPER]: [
    {
      icon: InfoOutlinedIcon,
      title: 'Главная страница',
      subtitles: null,
      route: '/warehouse/dashboard',
      key: navBarActiveCategory.NAVBAR_DASHBOARD,
      checkHideBlock: () => true,
    },
    {
      icon: AssignmentIcon,
      title: 'Вакантные задачи',
      subtitles: null,
      route: '/warehouse/vacant-tasks',
      key: navBarActiveCategory.NAVBAR_VACANT_TASKS,
      checkHideBlock: () => true,
    },
    {
      icon: Work,
      title: 'Мои задачи',
      subtitles: null,
      route: '/warehouse/my-tasks',
      key: navBarActiveCategory.NAVBAR_MY_TASKS,
      checkHideBlock: () => true,
    },
    {
      icon: DoneOutline,
      title: 'Выполненые задачи',
      subtitles: null,
      route: '/warehouse/completed-tasks',
      key: navBarActiveCategory.NAVBAR_COMPLETED_TASKS,
      checkHideBlock: () => true,
    },
    {
      icon: Block,
      title: 'Отмененные задачи',
      subtitles: null,
      route: '/warehouse/canceled-tasks',
      key: navBarActiveCategory.NAVBAR_CANCELED_TASKS,
      checkHideBlock: () => true,
    },
    {
      icon: LocalConvenienceStore,
      title: 'Отправления',
      subtitles: null,
      route: '/warehouse/boxes',
      key: navBarActiveCategory.NAVBAR_BATCHES,
      checkHideBlock: () => true,
    },
    {
      icon: PeopleIcon,
      title: 'Пользователи',
      route: '/warehouse/users/sub-users',
      subtitles: [{subtitle: 'Мои пользователи', subRoute: '/warehouse/users/sub-users'}],
      key: navBarActiveCategory.NAVBAR_USERS,
      checkHideBlock: () => true,
    },
    {
      icon: MonetizationOnOutlinedIcon,
      title: 'Финансы',
      route: '/warehouse/finances',
      subtitles: [
        {subtitle: 'Пополнения', subRoute: '/warehouse/finances'},
        {subtitle: 'Списания', subRoute: '/warehouse/finances'},
      ],
      key: navBarActiveCategory.NAVBAR_FINANCES,
      checkHideBlock: () => true,
    },
  ],
  [UserRole.ADMIN]: [
    {
      icon: InfoOutlinedIcon,
      title: 'Главная страница',
      subtitles: null,
      route: '/admin/dashboard',
      key: navBarActiveCategory.NAVBAR_DASHBOARD,
      checkHideBlock: () => true,
    },
    {
      icon: GavelIcon,
      title: 'Биржа товаров',
      route: '/admin/exchange',
      subtitles: [
        {subtitle: 'Созданные', subRoute: '/admin/exchange'},
        {subtitle: 'Новые', subRoute: '/admin/exchange'},
        {subtitle: 'Поиск поставщика', subRoute: '/admin/exchange'},
        {subtitle: 'В работе у байера', subRoute: '/admin/exchange'},
        {subtitle: 'Поставщик найден байером', subRoute: '/admin/exchange'},
        {subtitle: 'Поставщик не найден байером', subRoute: '/admin/exchange'},
        {subtitle: 'Цена выше МЗЦ', subRoute: '/admin/exchange'},
        {subtitle: 'Опубликованные', subRoute: '/admin/exchange'},
        {subtitle: 'Отклоненные', subRoute: '/admin/exchange'},
        {subtitle: 'Нет поставщика (закончено супервизором)', subRoute: '/admin/exchange'},
      ],
      key: navBarActiveCategory.NAVBAR_EXCHANGE,
      checkHideBlock: () => true,
    },
    {
      icon: InboxOutlinedIcon,
      title: 'Инвентарь',
      route: '/admin/inventory',
      subtitles: null,
      key: navBarActiveCategory.NAVBAR_INVENTORY,
      checkHideBlock: () => true,
    },
    {
      icon: AssignmentIcon,
      title: 'Заказы',
      route: '/admin/orders',
      subtitles: [
        {subtitle: 'Доступен к обработке', subRoute: '/admin/orders'},
        {subtitle: 'Закупщик взял заказ', subRoute: '/admin/orders'},
        {subtitle: 'Закупщик оплатил заказ', subRoute: '/admin/orders'},

        {subtitle: 'Выдан трек номер', subRoute: '/admin/orders'},
        {subtitle: 'Пришёл на склад', subRoute: '/admin/orders'},
        {subtitle: 'Возврат заказа', subRoute: '/admin/orders'},

        {subtitle: 'Ожидает отправки', subRoute: '/admin/orders'},
        {subtitle: 'Отправлен', subRoute: '/admin/orders'},
        {subtitle: 'Закрыт', subRoute: '/admin/orders'},
      ],
      key: navBarActiveCategory.NAVBAR_ORDERS,
      checkHideBlock: () => true,
    },
    {
      icon: ArchiveOutlinedIcon,
      title: 'Склад',
      route: '/admin/warehouse/tasks',
      subtitles: [
        {subtitle: 'Задачи', subRoute: '/admin/warehouse/tasks'},
        {subtitle: 'Коробки', subRoute: '/admin/warehouse/boxes'},
        {subtitle: 'Партии', subRoute: '/admin/warehouse/batches'},
      ],
      key: navBarActiveCategory.NAVBAR_WAREHOUSE,
      checkHideBlock: () => true,
    },
    {
      icon: MonetizationOnOutlinedIcon,
      title: 'Финансы',
      route: '/admin/finances',
      subtitles: [
        {subtitle: 'Пополнения', subRoute: '/admin/finances'},
        {subtitle: 'Списания', subRoute: '/admin/finances'},
      ],
      key: navBarActiveCategory.NAVBAR_FINANCES,
      checkHideBlock: () => true,
    },
    {
      icon: PeopleIcon,
      title: 'Пользователи',
      route: '/admin/users',
      key: navBarActiveCategory.NAVBAR_USERS,
      checkHideBlock: () => true,
    },

    {
      icon: PeopleIcon,
      title: 'Разрешения пользователей',
      route: '/admin/permissions',
      key: navBarActiveCategory.NAVBAR_PERMISSIONS,
      checkHideBlock: () => true,
    },
    {
      icon: SettingsIcon,
      title: 'Настройки',
      subtitles: null,
      route: '/admin/settings',
      key: navBarActiveCategory.NAVBAR_SETTINGS,
      checkHideBlock: () => true,
    },
  ],
}
