/* 20, 70, 80, 90 - эти статусы запускают процесс выплат. После того как поставлен
  один из таких статусов - больше нельзя така как появилась запись об оплате.
*/
import {objectFlip} from '@utils/object'

export const ProductStatus = {
  NEW_PRODUCT: 'NEW_PRODUCT',
  RESEARCHER_FOUND_SUPPLIER: 'RESEARCHER_FOUND_SUPPLIER',
  RESEARCHER_CREATED_PRODUCT: 'RESEARCHER_CREATED_PRODUCT',
  CHECKED_BY_SUPERVISOR: 'CHECKED_BY_SUPERVISOR',
  REJECTED_BY_SUPERVISOR_AT_FIRST_STEP: 'REJECTED_BY_SUPERVISOR_AT_FIRST_STEP',
  BUYER_PICKED_PRODUCT: 'BUYER_PICKED_PRODUCT',
  TO_BUYER_FOR_RESEARCH: 'TO_BUYER_FOR_RESEARCH',
  BUYER_FOUND_SUPPLIER: 'BUYER_FOUND_SUPPLIER',
  SUPPLIER_WAS_NOT_FOUND_BY_BUYER: 'SUPPLIER_WAS_NOT_FOUND_BY_BUYER',
  SUPPLIER_PRICE_WAS_NOT_ACCEPTABLE: 'SUPPLIER_PRICE_WAS_NOT_ACCEPTABLE',
  COMPLETE_SUCCESS: 'COMPLETE_SUCCESS',
  COMPLETE_SUPPLIER_WAS_NOT_FOUND: 'COMPLETE_SUPPLIER_WAS_NOT_FOUND',
  COMPLETE_PRICE_WAS_NOT_ACCEPTABLE: 'COMPLETE_PRICE_WAS_NOT_ACCEPTABLE',
  PURCHASED_PRODUCT: 'PURCHASED_PRODUCT',
  NO_PUBLISHED: 'NO_PUBLISHED',

  CREATED_BY_CLIENT: 'CREATED_BY_CLIENT',
  FROM_CLIENT_READY_TO_BE_CHECKED_BY_SUPERVISOR: 'FROM_CLIENT_READY_TO_BE_CHECKED_BY_SUPERVISOR',
  FROM_CLIENT_TO_BUYER_FOR_RESEARCH: 'FROM_CLIENT_TO_BUYER_FOR_RESEARCH',
  FROM_CLIENT_BUYER_PICKED_PRODUCT: 'FROM_CLIENT_BUYER_PICKED_PRODUCT',
  FROM_CLIENT_BUYER_FOUND_SUPPLIER: 'FROM_CLIENT_BUYER_FOUND_SUPPLIER',
  FROM_CLIENT_SUPPLIER_WAS_NOT_FOUND_BY_BUYER: 'FROM_CLIENT_SUPPLIER_WAS_NOT_FOUND_BY_BUYER',
  FROM_CLIENT_SUPPLIER_PRICE_WAS_NOT_ACCEPTABLE: 'FROM_CLIENT_SUPPLIER_PRICE_WAS_NOT_ACCEPTABLE',
  FROM_CLIENT_COMPLETE_SUCCESS: 'FROM_CLIENT_COMPLETE_SUCCESS',
  FROM_CLIENT_PAID_BY_CLIENT: 'FROM_CLIENT_PAID_BY_CLIENT',
  FROM_CLIENT_COMPLETE_SUPPLIER_WAS_NOT_FOUND: 'FROM_CLIENT_COMPLETE_SUPPLIER_WAS_NOT_FOUND',
  FROM_CLIENT_COMPLETE_PRICE_WAS_NOT_ACCEPTABLE: 'FROM_CLIENT_COMPLETE_PRICE_WAS_NOT_ACCEPTABLE',
}

export const ProductStatusByCode = {
  // Товар после заведения в базе ресерчером получает этот статус. Ресечер может дополнительно сменить его на статус 30
  0: ProductStatus.NEW_PRODUCT,
  5: ProductStatus.RESEARCHER_CREATED_PRODUCT,
  10: ProductStatus.RESEARCHER_FOUND_SUPPLIER,
  // Статусы, которые поставит супервайзер по итогам проверки
  15: ProductStatus.CHECKED_BY_SUPERVISOR,
  20: ProductStatus.REJECTED_BY_SUPERVISOR_AT_FIRST_STEP, // Если ставит этот статус - должны заплатить супервайзеру.
  30: ProductStatus.TO_BUYER_FOR_RESEARCH,
  35: ProductStatus.BUYER_PICKED_PRODUCT, // статус проставляется автоматически после того как баер взял товар в работу
  // Статусы которые поставит байер по результатам своей работы.
  40: ProductStatus.BUYER_FOUND_SUPPLIER,
  50: ProductStatus.SUPPLIER_WAS_NOT_FOUND_BY_BUYER,
  60: ProductStatus.SUPPLIER_PRICE_WAS_NOT_ACCEPTABLE,
  // Статус которые проставит супервайзер по результатам второй проверки.
  70: ProductStatus.COMPLETE_SUCCESS, // если был поставлен статус 70 то нужно учитывать предыдущий статус товара. если переходили с 10->70 оплачиваем ресечеру и супервайзеру. если переходили с 40->70 оплачиваем ресечеру, байеру и супервайзеру.
  75: ProductStatus.PURCHASED_PRODUCT, // продукт куплен
  80: ProductStatus.COMPLETE_SUPPLIER_WAS_NOT_FOUND,
  // оплачиваем супервайзеру
  90: ProductStatus.COMPLETE_PRICE_WAS_NOT_ACCEPTABLE,
  // оплачиваем супервайзеру
  100: ProductStatus.NO_PUBLISHED, // статус для скрытия товара с биржи товаров админом (создана задача на бек)

  200: ProductStatus.CREATED_BY_CLIENT,
  205: ProductStatus.FROM_CLIENT_READY_TO_BE_CHECKED_BY_SUPERVISOR,
  230: ProductStatus.FROM_CLIENT_TO_BUYER_FOR_RESEARCH,
  235: ProductStatus.FROM_CLIENT_BUYER_PICKED_PRODUCT,
  240: ProductStatus.FROM_CLIENT_BUYER_FOUND_SUPPLIER,
  250: ProductStatus.FROM_CLIENT_SUPPLIER_WAS_NOT_FOUND_BY_BUYER,
  260: ProductStatus.FROM_CLIENT_SUPPLIER_PRICE_WAS_NOT_ACCEPTABLE,
  270: ProductStatus.FROM_CLIENT_COMPLETE_SUCCESS,
  275: ProductStatus.FROM_CLIENT_PAID_BY_CLIENT,
  280: ProductStatus.FROM_CLIENT_COMPLETE_SUPPLIER_WAS_NOT_FOUND,
  290: ProductStatus.FROM_CLIENT_COMPLETE_PRICE_WAS_NOT_ACCEPTABLE,
}

export const ProductStatusByKey = objectFlip(ProductStatusByCode, parseInt)
