export const RequestStatus = {
  CREATED: 'CREATED',
  IN_PROCESS: 'IN_PROCESS',
  READY_TO_VERIFY: 'READY_TO_VERIFY',
  VERIFYING: 'VERIFYING',
  TO_CORRECT: 'TO_CORRECT',
  COMPLETE: 'COMPLETE',
  CANCELED: 'CANCELED',
}
