export const ShopStatus = {
  DRAFT: 'DRAFT',
  DELETED: 'DELETED',
  MODERATING: 'MODERATING',
  PUBLISHED: 'PUBLISHED',
  BOOKED: 'BOOKED',

  MODERATOR_CALLED: 'MODERATOR_CALLED',
  SOLD: 'SOLD',
}
