export const texts = {
  en: {
    dashboardBalance: {
      balance: 'My balance',
    },
    entryLeftPanel: {
      companyName: 'Amazontop',
      greetingTitle: 'Hello, nice to meet you',
      greetingSubtitle: 'Just register to join with us',
      footer: 'Footer',
    },
    rangeInput: {
      start: 'from',
      end: 'to',
    },
    privateLabelCard: {
      price: 'Price',
      qty: 'Qty',
      avgPrice: 'Average price',
      recConsignmentQty: 'Рекомендуемая партия к запуску Private Label',
      recConsignmentWeight: 'Вес рекомендованной партии',
      avgBSR: 'Average BSR',
      avgReviews: 'Average Reviews',
      avgRevenue: 'Average Revenue',
      launchBtn: 'Запустить Private Label',
      addBtnPrefix: 'Добавить за',
    },
    authView: {
      title: 'Sign in',
      redirect: 'Create account',

      emailLabel: 'Your Email',
      emailPlaceholder: 'example@mail.com',
      passwordLabel: 'Your Password',
      passwordPlaceholder: 'password',
      checkboxLabel: 'Remember me',
      forgotPassword: 'Forgot password',
      button: 'Login',
    },
    registerScreen: {
      title: 'Register',
      redirect: 'Already have account?',

      emailLabel: 'Your Email',
      emailPlaceholder: 'example@mail.com',
      passwordLabel: 'Your Password',
      passwordPlaceholder: 'password',
      rePasswordLabel: 'Re-type Password',
      rePasswordPlaceholder: 'password',
      checkboxLabel: 'Agree with ',
      termsAndConditions: 'Terms & Conditions',
      button: 'Register',

      successRegistration: 'Успешная регистрация',
      errorRegistration: 'Ошибка регистрации',
      okBtn: 'Ок',
    },

    termsScreen: {
      soon: 'Coming soon...',
    },

    clientDashboardView: {
      appbarTitle: 'Dashboard',
      balance: 'My balance',
      withdraw: 'Withdraw money',
      replenish: 'Add money',
      inventoryTitle: 'Inventory',
      ordersTitle: 'Orders',
      exchangeTitle: 'Exchange',
      withdrawFunds: 'Вывод средств',
      fillAccount: 'Пополнить счёт',
      itemsInInventorySectionItemTitle: 'Товаров в инвентаре',
      fullCostOfWarehouseSectionItemTitle: 'Общая стоимость склада',
      repurchaseItemsSectionItemTitle: 'Товаров с повторной закупкой',
      notPaidOrdersSectionItemTitle: 'Неоплаченные заказы',
      paidOrdersSectionItemTitle: 'Оплаченные заказы',
      canceledOrdersSectionItemTitle: 'Отмененные заказы',
      soldItemsOnExchangeSectionItemTitle: 'Продано товаров на бирже',
      accuredToReserchersSectionItemTitle: 'Начислено ресерчерам',
      disputsForProductsSectionItemTitle: 'Споров по товарам',
    },

    clientWarehouseView: {
      appbarTitle: 'Warehouse',
      mainTitle: 'Boxes in warehouse',
      sendProductBtn: 'Send own product',
      sendBatchBtn: 'Send batch',
      mergeBtn: 'Merge',
      redistributeBtn: 'Redistribute',
      editBtn: 'Edit',
      closeBtn: 'Close',
      resetBtn: 'Сбросить',
      warehouseHistoryTitle: 'Задачи склада',

      modalSendOwnProductTitle: 'Send own product',
      modalEditBoxTitle: 'Box editing',
      modalRedistributionTitle: 'Box redistributing',
      modalRedistributionAddNewBoxTitle: 'Attention!',
      modalRedistributionAddNewBoxMessage:
        'Увеличение количества коробок будет требовать дополнительной оплаты в зависимости от тарифов склада на котором находиться товар',
      modalRedistributionSuccessTitle: 'Success!',
      modalRedistributionSuccessMessage: 'Box redistribution was successful',
      modalRedistributionFailTitle: 'Fail',
      modalRedistributionFailMessage: 'Новые коробки должны отличаться от старых',

      modalMergeTitle: 'Соединение коробок',
      modalMergeFieldLabel: 'Комментарий клиента к задаче',
      modalMergeMergeBtn: 'Соединить',
      modalMergeCancelBtn: 'Отменить',

      confirmTitle: 'Внимание',
      confirmMessage: 'Вы точно хотите отменить задачу?',
      yesBtn: 'Да',
      noBtn: 'Нет',
    },

    adminWarehouseView: {
      appbarTitle: 'Warehouse',
      mainTitle: 'Boxes in warehouse',
      sendProductBtn: 'Send own product',
      sendBatchBtn: 'Send batch',
      mergeBtn: 'Merge',
      redistributeBtn: 'Redistribute',
      editBtn: 'Edit',
      closeBtn: 'Close',

      modalSendOwnProductTitle: 'Send own product',
      modalEditBoxTitle: 'Box editing',
      modalRedistributionTitle: 'Box redistributing',
      modalRedistributionAddNewBoxTitle: 'Attention!',
      modalRedistributionAddNewBoxMessage:
        'Увеличение количества коробок будет требовать дополнительной оплаты в зависимости от тарифов склада на котором находиться товар',
      modalRedistributionSuccessTitle: 'Success!',
      modalRedistributionSuccessMessage: 'Box redistribution was successful',
    },
    clientBoxRedistribution: {
      redistributionTitle: 'Redistribution',
      newBoxesTitle: 'New boxes',
      productsLeftToRedistribute: 'Left to redistribute',
      qtyLabel: 'Qty',
      toRedistributeBtn: 'To redistribute',
      newBoxBtn: 'New box',
      cancelBtn: 'Cancel',

      warehouse: 'Склад',
      valueNone: 'none',
      deliveryMethod: 'Доставка',
      shippingLabel: 'Шиппинг лейбл',
    },
    clientSendOwnProductForm: {
      productNameLabel: 'Product name',
      linkAmazonLabel: 'Amazon Link',
      linkImgLabel: 'Image link',
      productWeightLabel: 'Product weight',
      productSizeLabel: 'Product size',
      providerLabel: 'Provider',
      clientCommentsLabel: 'Comments',
      clientCommentsPlaceholder: 'Укажите всю информацию к вашему заказу',

      parseBtn: 'Parse',
      downloadBtn: 'Download',
      addProductBtn: 'Add product',
    },
    clientEditBoxForm: {
      newBoxTitle: 'Создание новых коробок!',
      updateBoxTitle: 'Update box',
      boxTitle: 'Box',
      warehouseLabel: 'Warehouse',
      deliveryMethodLabel: 'Delivery method',
      statusLabel: 'Status',
      lengthCmSupplier: 'lengthCmSupplier',
      widthCmSupplier: 'widthCmSupplier',
      heightCmSupplier: 'heightCmSupplier',
      weighGrossKgSupplier: 'weighGrossKgSupplier',
      volumeWeightKgSupplier: 'volumeWeightKgSupplier',
      weightFinalAccountingKgSupplier: 'weightFinalAccountingKgSupplier',

      lengthCmWarehouse: 'lengthCmWarehouse',
      widthCmWarehouse: 'widthCmWarehouse',
      heightCmWarehouse: 'heightCmWarehouse',
      weighGrossKgWarehouse: 'weighGrossKgWarehouse',
      volumeWeightKgWarehouse: 'volumeWeightKgWarehouse',
      weightFinalAccountingKgWarehouse: 'weightFinalAccountingKgWarehouse',

      amountLabel: 'Amount',
      materialLabel: 'Material',
      amountOfSubBoxes: 'amountOfSubBoxes',
      amountIfItemsInBox: 'Items in box *',

      warehouseDemensions: 'Warehouse demensions',

      saveChangesBtn: 'Save',
      cancelChangesBtn: 'Cancel',
      addBoxBtn: 'Добавить еще коробку',
      removeBtn: 'Убрать коробку',

      showBoxes: 'Показать коробки связанные с заказом...',
      hideBoxes: 'Скрыть коробки связанные с заказом...',
    },

    buyerCreateBoxForm: {
      newBoxTitle: 'Создание новых коробок!',
      updateBoxTitle: 'Update box',
      boxTitle: 'Box',
      warehouseLabel: 'Warehouse',
      deliveryMethodLabel: 'Delivery method',
      statusLabel: 'Status',
      lengthCmSupplier: 'lengthCmSupplier',
      widthCmSupplier: 'widthCmSupplier',
      heightCmSupplier: 'heightCmSupplier',
      weighGrossKgSupplier: 'weighGrossKgSupplier',
      volumeWeightKgSupplier: 'volumeWeightKgSupplier',
      weightFinalAccountingKgSupplier: 'weightFinalAccountingKgSupplier',

      lengthCmWarehouse: 'lengthCmWarehouse',
      widthCmWarehouse: 'widthCmWarehouse',
      heightCmWarehouse: 'heightCmWarehouse',
      weighGrossKgWarehouse: 'weighGrossKgWarehouse',
      volumeWeightKgWarehouse: 'volumeWeightKgWarehouse',
      weightFinalAccountingKgWarehouse: 'weightFinalAccountingKgWarehouse',

      amountLabel: 'Amount',
      materialLabel: 'Material',
      amountOfSubBoxes: 'amountOfSubBoxes',
      amountIfItemsInBox: 'Items in box *',

      warehouseDemensions: 'Warehouse demensions',

      saveChangesBtn: 'Добавить',
      cancelChangesBtn: 'Cancel',
      addBoxBtn: 'Добавить еще коробку',
      removeBtn: 'Убрать коробку',

      showBoxes: 'Показать коробки связанные с заказом...',
      hideBoxes: 'Скрыть коробки связанные с заказом...',
    },

    warehouseEditBoxForm: {
      amountLabel: 'Qty',
      materialLabel: 'Material',
      shippingLabel: 'shippingLabel:',
      setShippingLabel: 'Set shipping label',
      deleteAlert: 'delete',
    },

    adminDashboardView: {
      appbarTitle: 'Dashboard',
      dashboardTitle: 'Dashboard',
      productsTitle: 'Товары',
      accrualsAndFinesTitle: 'Начисления и штрафы',
      prodcutsWaitingToCheckBySupervisorsTitle: 'Ожидают проверку',
      productsBeingCheckedBySupervisorsTitle: 'Взяты на проверку супервайзерами',
      productsCheckedBySupervisorsTitle: 'Подтверждены супервайзерами',
      productsRejectedBySupervisorsTitle: 'Отклонены супервайзерами',
      accruedToManagersTitle: 'Начислено менеджерам',
      accruedToSupervisorsTitle: 'Начислено супервайзерам',
      supervisorsFinesTitle: 'Штрафы супервайзеров',
      managersFinesTitle: 'Штрафы менеджеров',
    },

    adminProductsWaitingView: {
      appbarTitle: 'Exchange',
      mainTitle: 'Products',
    },
    adminInventoryView: {
      appbarTitle: 'Inventory',
      mainTitle: 'Inventory',
    },
    adminOrdersAllView: {
      appbarTitle: 'Orders - All',
      mainTitle: 'Заказы всех клиентов',
    },
    adminWarehouseOrdersView: {
      appbarTitle: 'Warehouse - Orders',
      mainTitle: 'Все поступившие на склад заказы',
    },
    adminFinancesReplenishmentsView: {
      appbarTitle: 'Replenish balance',
      mainTitle: 'Replenish balance',
    },
    adminUsersView: {
      appbarTitle: 'Users',
      mainTitle: 'Users',
      modalEditTitle: 'Edit user',
      modalEditBtn: 'Save',
      editBtn: 'Edit User',
      balanceBtn: 'Balance',
    },
    adminUserBalanceView: {
      balance: 'Balance',
      withdraw: 'Withdraw',
      replenish: 'Deposit',

      appbarTitle: 'User balance',
      mainTitle: 'Users',
      modalEditTitle: 'Edit user',
      modalEditBtn: 'Save',

      balanceHistoryTitle: 'Изменения баланса',
    },
    adminSettingsView: {
      appbarTitle: 'Settings',
      mainTitle: 'Settings',
    },
    adminBalanceModal: {
      titleReplenish: 'Replenish balance',
      titleWithdraw: 'Withdraw balance',
      balanceLabel: 'Balance change value',
      reasonLabel: 'Reason',
      commentLabel: 'Comment',
      msgSubject: 'Balance of user',
      msgPosPredicate: 'will be replenish by',
      msgNegPredicate: 'will be debited by',
      executeBtn: 'Execute',
      confirmBtn: 'Confirm',
      declineBtn: 'Decline',
      confirmMsgAreYouSureYouWantTo: 'Are you sure you want to',
      confirmMsgIncrease: 'increase',
      confirmMsgDecrease: 'decrease',
      confirmMsgTheBalanceOfTheUser: 'the balance of the user',
      confirmMsgBy: 'by',
      widthdrawOptionFine: 'Штраф',
      widthdrawOptionWithdraw: 'Вывод средств',
      replenishOptionReplenish: 'Пополнение',
      replenishOptionServicePayment: 'Оплата услуг',
    },

    userMoneyTransferModal: {
      titleAdd: 'Add money',
      titleWithdraw: 'Withdraw money',

      okBtn: 'Ок',
    },

    tableToolbar: {
      filter: 'Filter',
      searchPlaceholder: 'Search...',
      rowsPerPage: 'Rows per page',
    },
    clientExchangeView: {
      appbarTitle: 'Exchange',
      mainTitle: 'Active offers on exchange',
      confirmTitle: 'Вы покупаете товар, уверены?',
      confirmMessage: 'У вас будет списание ',
      confirmBtn: 'Да',
      cancelBtn: 'Отмена',
      successTitle: 'Заказ успешно создан!',
      successBtn: 'Ок!',
      warningModalTitle: 'Этот товар перемещён в Инвентарь',
      okBtn: 'Ок',
      byForBtn: 'Купить за',
    },
    exchangeBodyRow: {
      byForBtn: 'Купить за',
    },
    clientExchangePrivateLabelView: {
      appbarTitle: 'Exchange - PrivateLabel',
      mainTitle: 'Information about Private Label',

      confirmTitle: 'Вы покупаете товар, уверены?',
      confirmMessage: 'У вас будет списание ',
      confirmBtn: 'Да',
      cancelBtn: 'Отмена',
      successTitle: 'Товар оплачен',
      successBtn: 'Ок!',
    },
    clientExchangeRequestsView: {
      appbarTitle: 'Exchange - Requests',
      mainTitle: 'My requests on exchange',
      newRequest: 'New request',
      myRequests: 'Мои заявки',
      placeOrderBtn: 'Разместить заявку',

      modalNewRequestTitle: 'New request',
      modalEditRequestTitle: 'Edit request',
      modalCloseRequestTitle: 'Close request',

      modalBtnSendRequest: 'Send request',
      modalBtnSaveRequest: 'Save request',
      modalBtnCloseRequest: 'Send',

      formStrategyLabel: 'Strategy *',
      formMonthlySalesLabel: 'Monthly sales *',
      formBudgetLabel: 'Budget *',
      formAmazonPriceLabel: 'Amazon price *',
      formAvgBSRLabel: 'Average BSR *',
      formAvgReviewsLabel: 'Average Reviews *',
      formAvgRevenueLabel: 'Average Revenue *',
      formNotesLabel: 'Notes',
      formCheckboxForbidLabel:
        'Запрещено добавлять товары, которые когда-либо были проданы, либо опубликованы на площадке по данной стратегии.',
      formCheckboxNoPayLabel: 'Не оплачиваю повторно купленные товары',
      formDeadlineLabel: 'Target date *',
      formDeadlineErrorText: 'The deadline date cannot be later than the current date',
      formCheckboxNoCheckLabel: 'Сотрудники платформы будут участвовать в проверке качества найденного товара.',
      formCheckboxNoPurchasedNiches: 'Не предлагать ниши купленные мной',
      formCheckboxNoPurchasedProducts: 'Не предлагать продукты купленные мной',
      formCheckboxFindSupplier: 'Найти поставщика',
      formCloseReasonLabel: 'Describe the reason for closing request',

      requestProductBtn: 'Заявка на поиск продукта',
      requestNicheBtn: 'Заявка на поиск ниши',

      productTitle: 'Поиск продукта',
      nicheTitle: 'Поиск ниши',

      confirmTitle: 'Внимание',
      confirmMessage: 'Вы точно хотите отменить запрос на поиск?',
      yesBtn: 'Да',
      noBtn: 'Нет',

      countOfProposals: 'Count of proposals *',
      countOfOneProposals: 'Cost of one proposal *',
      minProductInProposals: 'Count of min product in proposals *',
      minKeywords: 'Count of min key words in proposals *',
      size: 'Size tier *',
      searchVolume: 'Search volume *',

      editBtn: 'Изменить',
      createBtn: 'Создать заявку',
      cancelBtn: 'Отмена',
    },

    productSearchRequestContent: {
      parameterFieldTypo: 'Параметр',
      valueFieldTypo: 'Значение',
      tableStrategyField: 'Strategy',
      tableMonthlySalesField: 'Monthly sales',
      tableBudgetField: 'Budget',
      tableMinProductsField: 'Min products',
      tableMinKeywordsField: 'Min keywords',
      tableAmazonPriceField: 'Amazone price',
      tableAverageBsrField: 'Average BSR',
      tableAverageReviewsField: 'Average reviews',
      tableAverageRevenueField: 'Average revenue',
      tableNotesField: 'Notes',
      tableTargetDateField: 'Target date',
      tableForbidProductField:
        'Запрещать добавлять товары, которые когда-либо были проданы, либо опубликованы на площадке по данной стратегии.',
      tableForbidNicheField:
        'Запрещено добавлять ниши которые когда либо были проданы либо опубликованы на площадке по данной стратегии',
      tableExaminationQualityField: 'Сотрудники платформы будут участвовать в проверке качества предложения',
    },

    addOrEditSinglePermissionForm: {
      addTitle: 'Новое разрешение',
      editTitle: 'Изменить разрешение',
      roleLabel: 'Роль',
      valueNone: 'None',
      keyLabel: 'Ключ',
      keyHolder: 'KEY_KEY_KEY...',
      titleLabel: 'Название',
      titleHolder: 'Разрешение №1 ',
      descriptionLabel: 'Описание',
      descriptionHolder: 'Доступ к редактированию товаров',
      allowUrlsLabel: 'Разрешенные эндпоинты',
      allowUrlsHolder: '/api/v1/permissions/...',
      keyFieldError: 'Значение должно содержать "_"',

      editBtn: 'Изменить',
      createBtn: 'Создать разрешение',
      cancelBtn: 'Отмена',
    },

    addOrEditUserPermissionsForm: {
      mainTitle: 'Назначить разрешения',
      roleLabel: 'Роль',
      valueNone: 'None',
      keyLabel: 'Ключ',
      keyHolder: 'KEY_KEY_KEY...',
      titleLabel: 'Название',
      titleHolder: 'Разрешение №1 ',
      descriptionLabel: 'Описание',
      descriptionHolder: 'Доступ к редактированию товаров',
      allowUrlsLabel: 'Разрешенные эндпоинты',
      allowUrlsHolder: '/api/v1/permissions/...',

      showBtn: 'Показать разрешения',
      hideBtn: 'Скрыть разрешения',
      permissionSubTitle: 'Разрешения:',

      choosePermissionGroups: 'Выбрать группы разрешений:',
      choosenPermissionGroups: 'Выбранные группы разрешений:',

      choosePermissions: 'Выбрать одиночные разрешения:',
      choosenPermission: 'Выбранные одиночные разрешения:',

      editBtn: 'Изменить',
      createBtn: 'Создать разрешение',
      cancelBtn: 'Отмена',
    },

    addOrEditGroupPermissionForm: {
      addTitle: 'Новоя группа разрешений',
      editTitle: 'Изменить группу разрешений',
      roleLabel: 'Роль',
      valueNone: 'None',
      keyLabel: 'Ключ',
      keyHolder: 'KEY_KEY_KEY...',
      titleLabel: 'Название',
      titleHolder: 'Группа №1 ',
      descriptionLabel: 'Описание',
      descriptionHolder: 'Доступ к редактированию товаров',
      allowPermissions: 'Разрешения',

      editBtn: 'Изменить группу',
      createBtn: 'Создать группу',
      cancelBtn: 'Отмена',

      currentPermissions: 'Существующие разрешения:',
      selectChooseTitle: 'Выбрать доступные:',
      permissionsWillbeCreated: 'Разрешения будут созданы:',
      keyFieldError: 'Значение должно содержать "_"',

      addNewPermBtn: 'Создать новое',

      keyPermInfo: 'Ключ:',
      descriptionPermInfo: 'Описание:',
      allowedUrlPermInfo: 'Разрешенные эндпоинты:',
    },

    exchangeInventoryColumns: {
      strategyStatusField: 'Strategy',
      createDateField: 'Created',
      updateDateField: 'Updated',
      asinField: 'ASIN',
      asinTypo: 'ASIN ',
      asinUpdateToday: ' | updated today',
      careChip: 'Beauty & Personal Care',
      priceField: 'Price',
      feesAndNetField: 'Fees & Net',
      calculateBtn: 'Calculate fees',
      feesTypo: 'Fees ',
      netTypo: 'Net ',
      supplierField: 'Supplier',
      supervisorField: 'Supervisor',
      researcherField: 'Researcher',
      buyerField: 'Buyer',
      rankField: 'Rank',
      ratingField: 'Rating',
      ratingTypo: ' reviews',
      salesField: 'Sales',
      salesTotalField: 'Sales Total',
      typeField: 'Type',
      revenueField: 'Revenue',
      amazonPriceField: 'Amazon $',
      bsrField: 'BSR',
      fbaField: 'FBA',
      barcodeField: 'Barcode',
      setBarcodeChipLabel: 'Set barcode',
      fbaAmountField: 'Recommend amount',
    },

    clientInventoryColumns: {
      strategyStatusField: 'Strategy',
      createDateField: 'Created',
      updateDateField: 'Updated',
      asinField: 'ASIN',
      asinTypo: 'ASIN ',
      asinUpdateToday: ' | updated today',
      careChip: 'Beauty & Personal Care',
      priceField: 'Price',
      feesAndNetField: 'Fees & Net',
      calculateBtn: 'Calculate fees',
      feesTypo: 'Fees ',
      netTypo: 'Net ',
      supplierField: 'Supplier',
      supervisorField: 'Supervisor',
      researcherField: 'Researcher',
      buyerField: 'Buyer',
      rankField: 'Rank',
      ratingField: 'Rating',
      ratingTypo: ' reviews',
      salesField: 'Sales',
      salesTotalField: 'Sales Total',
      typeField: 'Type',
      revenueField: 'Revenue',
      amazonPriceField: 'Amazon $',
      bsrField: 'BSR',
      fbaField: 'Fba fee',
      barcodeField: 'Barcode',
      setBarcodeChipLabel: 'Set barcode',
      fbaAmountField: 'Recommend amount',
      actionField: 'Actions',
    },

    exchangeAllColumns: {
      asinField: 'ASIN',
      priceField: 'Price',
      feesAndNetField: 'Fees & Net',
      supplierField: 'Supplier',
      supervisorField: 'Supervisor',
      supervisorDateCheckField: 'Date to check',
      supervisorDateFindField: 'Date to find',
      buyerDateFindField: 'Date to get in work',
      dateSupplierInfoField: 'Date get info supplier',
      researcherField: 'Researcher',
      buyerField: 'Buyer',
      rankField: 'Rank',
      ratingField: 'Rating',
      salesField: 'Sales',
      salesTotalField: 'Sales Total',
      typeField: 'Type',
      revenueField: 'Revenue',
      amazonPriceField: 'Amazon $',
      bsrField: 'BSR',
      fbaField: 'FBA',
      barcodeField: 'Barcode',
    },

    exchangeWaitingColumns: {
      asinField: 'ASIN',
      priceField: 'Price',
      feesAndNetField: 'Fees & Net',
      supplierField: 'Supplier',
      supervisorField: 'Supervisor',
      supervisorDateCheckField: 'Date to check',
      supervisorDateFindField: 'Date to find',
      buyerDateFindField: 'Date to get in work',
      dateSupplierInfoField: 'Date get info supplier',
      researcherField: 'Researcher',
      buyerField: 'Buyer',
      rankField: 'Rank',
      ratingField: 'Rating',
      salesField: 'Sales',
      salesTotalField: 'Sales Total',
      typeField: 'Type',
      revenueField: 'Revenue',
      amazonPriceField: 'Amazon $',
      bsrField: 'BSR',
      fbaField: 'FBA',
      barcodeField: 'Barcode',
    },
    exchangeCheckingColumns: {
      strategyStatusField: 'Strategy',
      asinField: 'ASIN',
      priceField: 'Price',
      feesAndNetField: 'Fees & Net',
      supplierField: 'Supplier',
      supervisorField: 'Supervisor',
      supervisorDateCheckField: 'Date to check',
      supervisorDateFindField: 'Date to find',
      buyerDateFindField: 'Date to get in work',
      dateSupplierInfoField: 'Date get info supplier',
      researcherField: 'Researcher',
      buyerField: 'Buyer',
      rankField: 'Rank',
      ratingField: 'Rating',
      salesField: 'Sales',
      salesTotalField: 'Sales Total',
      typeField: 'Type',
      profitField: 'Profit',
      marginField: 'Margin',
      amazonPriceField: 'Amazon $',
      bsrField: 'BSR',
      fbaField: 'FBA fee',
      fbaAmountField: 'FBA amount',
      barcodeField: 'Barcode',
      createDateField: 'Create date',
      checkDateField: 'Check date',
      updateDateField: 'Update date',
    },
    exchangeSupplierSearchColumns: {
      strategyStatusField: 'Strategy',
      asinField: 'ASIN',
      priceField: 'Price',
      feesAndNetField: 'Fees & Net',
      supplierField: 'Supplier',
      supervisorField: 'Supervisor',
      supervisorDateCheckField: 'Date to check',
      supervisorDateFindField: 'Date to find',
      buyerDateFindField: 'Date to get in work',
      dateSupplierInfoField: 'Date get info supplier',
      researcherField: 'Researcher',
      buyerField: 'Buyer',
      rankField: 'Rank',
      ratingField: 'Rating',
      salesField: 'Sales',
      salesTotalField: 'Sales Total',
      typeField: 'Type',
      revenueField: 'Revenue',
      amazonPriceField: 'Amazon $',
      bsrField: 'BSR',
      fbaField: 'FBA',
      barcodeField: 'Barcode',
    },

    exchangeBuyerWorkColumns: {
      strategyStatusField: 'Strategy',
      asinField: 'ASIN',
      priceField: 'Price',
      feesAndNetField: 'Fees & Net',
      supplierField: 'Supplier',
      supervisorField: 'Supervisor',
      supervisorDateCheckField: 'Date to check',
      supervisorDateFindField: 'Date to find',
      buyerDateFindField: 'Date to get in work',
      dateSupplierInfoField: 'Date get info supplier',
      researcherField: 'Researcher',
      buyerField: 'Buyer',
      rankField: 'Rank',
      ratingField: 'Rating',
      salesField: 'Sales',
      salesTotalField: 'Sales Total',
      typeField: 'Type',
      revenueField: 'Revenue',
      amazonPriceField: 'Amazon $',
      bsrField: 'BSR',
      fbaField: 'FBA',
      barcodeField: 'Barcode',
    },

    exchangeSupplierFoundedColumns: {
      strategyStatusField: 'Strategy',

      asinField: 'ASIN',
      priceField: 'Price',
      feesAndNetField: 'Fees & Net',
      supplierField: 'Supplier',
      supervisorField: 'Supervisor',
      supervisorDateCheckField: 'Date to check',
      supervisorDateFindField: 'Date to find',
      buyerDateFindField: 'Date to get in work',
      dateSupplierInfoField: 'Date get info supplier',
      researcherField: 'Researcher',
      buyerField: 'Buyer',
      rankField: 'Rank',
      ratingField: 'Rating',
      salesField: 'Sales',
      salesTotalField: 'Sales Total',
      typeField: 'Type',
      revenueField: 'Revenue',
      amazonPriceField: 'Amazon $',
      bsrField: 'BSR',
      fbaField: 'FBA',
      barcodeField: 'Barcode',
    },
    exchangeRequestsBodyRow: {
      editBtn: 'Edit',
      closeBtn: 'Close',
    },
    documentationView: {
      appBarTitle: 'Documentation',
      appBarUserName: 'User',
      mainTitle: 'Documentation Amazontop',
      mainCreated: 'Created: 12.01.2021',
      mainLastUpdate: '24.03.2021',
      authTitle: 'Аутентификация',
      authLink: 'https://stoic-northcutt-f04ad5.netlify.app/auth',
      authDescription: 'При нажатии на "Create account" перенесет на страницу Регистрации',
      registerTitle: 'Регистрация',
      registerLink: 'https://stoic-northcutt-f04ad5.netlify.app/register',
      registerDescription: 'При нажатии на "Already have account" перенесет на страницу Аутентификации',
    },
    inventoryView: {
      appbarTitle: 'Inventory',
      productsList: 'Products list',
      setBarCodeBtn: 'Set barcode',
      listingBtn: 'Listing',
      setBarcodeChipLabel: 'Set barcode',
      orderBtn: 'Заказать',
      showProductBtn: 'Смотреть подробно',
      resetBtn: 'Сбросить',
      productsInInventoryDashboardCard: 'Товаров в инвентаре',
      productsBoughtOnExchangeDashboardCard: 'Товаров купленных на бирже',
      productsAddedDashboardCard: 'Товаров добавлено',
      ordersChackoutDashboardCard: 'Заказов оформлено',
      productsBoughtLast30DaysDashboardCard: 'Куплено за 30 дней',
      addProductBtn: 'Добавить свой товар',
      addProductModal: 'Добавить свой товар',
      successTitle: 'Заказ создан',
      successBtn: 'Ок',
    },
    researcherDashboardView: {
      appBarTitle: 'Dashboard',
      appBarUsername: 'Researcher',
      appUser: 'researcher',
      mainTitle: 'Dashboard',
      myProductsCardTitle: 'Мои товары',
      curBalanceCardTitle: 'Текущий баланс',
      finesCardTitle: 'Штрафы',
      newProductsCardTitle: 'Новых товаров в базе',
      meCheckingCardTitle: 'У меня на проверке',
      accuredCardTitle: 'Начислено',
    },

    supervisorDashboardView: {
      appBarTitle: 'Dashboard',
      appBarUsername: 'Supervisor',
      appUser: 'supervisor',
      mainTitle: 'Dashboard',

      myProductsCardTitle: 'Мои товары',
      curBalanceCardTitle: 'Текущий баланс',

      newProductsCardTitle: 'Новых товаров к проверке',
      meCheckingCardTitle: 'Всего товаров',
      suplierFoundedCardTitle: 'Поставщик найден',
      completeSuccessCardTitle: 'Опубликованные на бирже',
      purchasedCardTitle: 'Купленные',

      finesCardTitle: 'Штрафы',
      accuredCardTitle: 'Начислено',
    },

    buyerDashboardView: {
      appBarTitle: 'Dashboard',
      appBarUsername: 'Buyer',
      appUser: 'buyer',
      mainTitle: 'Dashboard',
      myProductsCardTitle: 'Мои товары',
      curBalanceCardTitle: 'Текущий баланс',

      newProductsCardTitle: 'Новых товаров в базе',
      myProductCardTitle: 'Мои товары',
      myOrdersCardTitle: 'Мои заказы',
      freeOrdersCardTitle: 'Свободные заказы',
    },

    researcherProductsView: {
      appBarTitle: 'Products',
      mainTitle: 'Заявки на поиск товара/ниши',
    },

    researcherProductsRequestsView: {
      appBarTitle: 'Requests',
      mainTitle: 'Мои товары',
      cardMainTitle: 'Проверка товара на наличие в базе',

      confirmTitle: 'Вы готовы начать работу по формированию предложения?',
      confirmMessage: `На обработку заявки потребуется N часов. При 
        невыполнении заявки в установленное время, будет произведена автоотмена задачи и 
        назначен штраф в сумме N $`,
      yesBtn: 'Да',
      noBtn: 'Нет',
    },

    researcherSettingsView: {
      appBarTitle: 'Settings',
      appBarUsername: 'Researcher',
      appUser: 'researcher',
      mainTitle: 'Settings page',
      fieldName: 'Name',
      fieldEmail: 'Email',
      fieldRate: 'Rate',
      fieldRole: 'Role',
      fieldFba: 'FBA',
      saveBtn: 'Сохранить',
      cancelBtn: 'Отменить',
    },

    batchesModalEditBatch: {
      batchDestination: 'Не назначен',
      mainTitle: 'Просмотр/редактирование партии',
      saveBtn: 'Сохранить',
      cancelBtn: 'Отмена',
    },

    batchesModalEditBoxList: {
      listBoxes: 'Список коробок',
      checkBoxes: 'Убедитесь, что выбраны нужные коробки!',
      boxNum: 'Коробка №',
      typoWarehouse: 'warehouse:',
      typoStatus: 'status: Formed',
      typoDeliveryMethod: 'deliveryMethod:',
      typoShippingLabel: 'shippingLabel:',
      typoGabarits: ' L x W x H',
      typoWeight: 'Weight',
      typoVolumeWeight: 'volumeWeight',
      typoWeightFinal: 'weightFinal',
      count: 'Кол-во:',
    },
    batchesModalEditFillList: {
      listFills: 'Список полей для заполнения',
      setValues: 'Задайте нужные значения всем выбранным коробкам.',
      warehouse: 'Склад',
      valueNone: 'None',
      valueMem: 'MEM1 Memphis, TN',
      valueMdw: 'MDW2 Joliet, IL',
      valueLax: 'LAX9 FONTANA, CA',
      valueLgb: 'LGB8 Rialto, CA',
      valueOnt: 'ONT8 AMAZON',
      deliveryMathod: 'Способ доставки',
      valueSea: 'Sea',
      valueAir: 'Air',
      typoStarus: 'Статус:',
      valuePrepare: 'Подготовлена',
      valueSendFromWarehouse: 'Отправлена со склада',
      valueSend: 'Отправлена',
      valueReceived: 'Получена',
      treckerNum: 'Трек номер США:',
      typoCloseButch: 'needCloseButch',
    },
    ordersViewsModalSelectFields: {
      warehouse: 'Склад',
      valueNone: 'None',
      valueMem: 'MEM1 Memphis, TN',
      valueMdw: 'MDW2 Joliet, IL',
      valueLax: 'LAX9 FONTANA, CA',
      valueLgb: 'LGB8 Rialto, CA',
      valueOnt: 'ONT8 AMAZON',
      deliveryMethod: 'Способ доставки',
      valueSea: 'Sea',
      valueAir: 'Air',
      typoStatus: 'Статус:',
      valueFormed: 'Formed',
      valueNew: 'New',
      valuePrepare: 'Ready to process',
      valueAtProc: 'At process',
      valuePaid: 'Paid',
      valueTrack: 'Track number issued',
      valueInStock: 'In stock',
      valueReturnOrder: 'Return order',
      typoClientComment: 'Client comment',
      typoBuyerComment: 'Buyer comment',
      typoShipPrice: 'Стоимость доставки до склада $',
      supplierPaidDelivery: 'Поставщик отправил все за свой счет',
      supplierAddBarCode: 'Поставщик поклеил баркод при отправке',
      usePriceInDollars: 'Использовать цену в долларах',

      priceYuansForBatchTypo: 'Юаней за партию Ұ',
      yuansToDollarRateTypo: 'Курс юаня к доллару',
      totalPriceChanged: 'Долларов за партию фактически $',
      costPriceAmount: 'Себестоимость в закупке за шт.',
      trackNumberTypo: 'Track number',

      circularProgressTitle: 'Загрузка фотографий...',
      loadTitle: 'Прикрепить фото к задаче',
      orderImagesBtn: 'Имеющиеся изображения к заказу',

      totalPrice: 'Запланированная стоимость заказа',
      totalPriceInYuans: 'Запланированная стоимость в юанях',
      checkIsPlanningPriceText: 'Фактическая стоимость совпадает с запланированной',
      priceYuansDeliveryCostToTheWarehouse: 'Из них за доставку до склада Китая Ұ',
      deliveryCostToTheWarehouse: 'Из них за доставку до склада Китая $',
    },

    buyerProductView: {
      appBarTitle: 'Product',
      appBarUsername: 'Buyer',
      appUser: 'buyer',
      modalAddTitle: 'Добавить нового поставщика',
      modalEditTitle: 'Редактировать поставщика',
      showNoSuplierErrorTitle: 'Не выбран поставщик',
      errorBtn: 'Ок',
      confirmTitle: 'Внимание',
      yesBtn: 'Да',
      noBtn: 'Нет',
      okBtn: 'ок',
      deleteSupplierMessage: 'Вы точно хотите удалить поставщика?',
    },
    adminProductView: {
      appBarTitle: 'Product',
      appBarUsername: 'Admin',
      appUser: 'admin',
    },

    researcherProductView: {
      appBarTitle: 'Product',
      appBarUsername: 'Researcher',
      appUser: 'researcher',
      modalAddTitle: 'Добавить нового поставщика',
      modalEditTitle: 'Редактировать поставщика',
      confirmTitle: 'Внимание',
      confirmMessage: 'Товар будет отправлен на проверку к Supervisor. Вы уверены?',
      deleteMessage: 'Вы точно хотите удалить продукт?',
      deleteSupplierMessage: 'Вы точно хотите удалить поставщика?',
      yesBtn: 'Да',
      noBtn: 'Нет',

      okBtn: 'Ок',
    },
    supervisorProductView: {
      appBarTitle: 'Product',
      appBarUsername: 'Supervisor',
      appUser: 'supervisor',
      modalAddTitle: 'Добавить нового поставщика',
      modalEditTitle: 'Редактировать поставщика',
      confirmTitle: 'Внимание',
      yesBtn: 'Да',
      noBtn: 'Нет',
      okBtn: 'ок',
    },
    buyerProductsView: {
      appBarTitle: 'Products',
      appBarUsername: 'Buyer',
      appUser: 'buyer',
      mainTitle: 'Товары',
    },
    dataGridCells: {
      asinTypo: 'ASIN ',
      careChip: 'Beauty & Personal Care',
      calculateBtn: 'Calculate fees',
      feesTypo: 'Fees ',
      netTypo: 'Net ',
      ratingTypo: ' reviews',
      setBarcodeChipLabel: 'Set barcode',
      titleToolTip: 'Подсказка',

      operatioTypeMerge: 'Соединить',
      operatioTypeSplit: 'Разделить',
      operatioTypeReceive: 'Принять',
      operatioTypeEdit: 'Изменить',

      merge: 'Соединение в коробку',
      unMerge: 'Разъедененние в коробки',
      changeStatus: ' изменил статус на ',
      receive: 'Принять коробку',
      edit: 'Изменить коробку',

      cancelBtn: 'Отмена',
      resolveBtn: 'Решить',

      editBtn: 'Изменить',
      removeBtn: 'Удалить',

      superboxTypo: 'SB',
      confirmBtn: 'Подтвердить',
      rejectBtn: 'Отклонить',
      addPermissionsBtn: 'Назначить разрешения',
    },

    linkSubUserForm: {
      title: 'Добавить саб-юзера',
      addBtn: 'Добавить',
      cancelBtn: 'Отмена',
      email: 'Email',
    },

    subUsersModalContent: {
      name: 'Name',
      email: 'Email',
      password: 'Password',
      rePassword: 'Re-type password',
      role: 'Role',
      allowedRoles: 'Allowed Roles',
      fba: 'FBA',
      active: 'User status',
      rate: 'Rate',

      fieldSecurity: 'Security/Sharing options',
      manageBtn: 'Manage Permissions',
      fieldBalance: 'Balance',
      balanceReplenishBtn: 'Replenish',
      balanceWithdrawBtn: 'Withdraw',

      activeOption: 'Active',
      bannedOption: 'Banned',
      isWrongPermissionsSelect: 'Выбранные разрешения и текущая роль не совпадают!',

      closeBtn: 'cancel',
    },

    subUsersModalPermission: {
      title: 'Subuser permissions',
      permissionTitle: 'Permission',
      researcherTitle: 'Researcher',
      acManagerTitle: 'Account manager',
      warehouseManagerTitle: 'Warehouse manager',
      saveBtn: 'Save',
    },
    buyerSubUsersView: {
      addUserBtn: 'Add User',
      appBarTitle: 'SubUsers',
      appBarUsername: 'Buyer',
      appUser: 'buyer',
      mainTitle: 'SubUsers',
      modalAddTitle: 'Create new subuser',
      modalAddBtn: 'Add Subuser',
      modalEditTitle: 'Edit subuser',
      modalEditBtn: 'Save changes',

      successTitle: 'Саб-юзер добавлен',
      failTitle: 'Саб-юзер не добавлен!',

      okBtn: 'Ок',

      confirmTitle: 'Внимание',
      confirmRemoveMessage: 'Вы точно хотите отвязать сабюзера?',
      yesBtn: 'Да',
      noBtn: 'Нет',
    },

    warehouseSubUsersView: {
      addUserBtn: 'Add User',
      appBarTitle: 'SubUsers',
      appBarUsername: 'Warehouse',
      appUser: 'warehouse',
      mainTitle: 'SubUsers',
      modalAddTitle: 'Create new subuser',
      modalAddBtn: 'Add Subuser',
      modalEditTitle: 'Edit subuser',
      modalEditBtn: 'Save changes',

      successTitle: 'Саб-юзер добавлен',
      failTitle: 'Саб-юзер не добавлен!',

      okBtn: 'Ок',

      confirmTitle: 'Внимание',
      confirmRemoveMessage: 'Вы точно хотите отвязать сабюзера?',
      yesBtn: 'Да',
      noBtn: 'Нет',
    },

    researcherSubUsersView: {
      addUserBtn: 'Add User',
      appBarTitle: 'SubUsers',
      appBarUsername: 'Researcher',
      appUser: 'researcher',
      mainTitle: 'SubUsers',
      modalAddTitle: 'Create new subuser',
      modalAddBtn: 'Add Subuser',
      modalEditTitle: 'Edit subuser',
      modalEditBtn: 'Save changes',

      successTitle: 'Саб-юзер добавлен',
      failTitle: 'Саб-юзер не добавлен!',

      okBtn: 'Ок',

      confirmTitle: 'Внимание',
      confirmRemoveMessage: 'Вы точно хотите отвязать сабюзера?',
      yesBtn: 'Да',
      noBtn: 'Нет',
    },

    supervisorSubUsersView: {
      addUserBtn: 'Add User',
      appBarTitle: 'SubUsers',
      appBarUsername: 'Supervisor',
      appUser: 'supervisor',
      mainTitle: 'SubUsers',
      modalAddTitle: 'Create new subuser',
      modalAddBtn: 'Add Subuser',
      modalEditTitle: 'Edit subuser',
      modalEditBtn: 'Save changes',

      successTitle: 'Саб-юзер добавлен',
      failTitle: 'Саб-юзер не добавлен!',

      okBtn: 'Ок',

      confirmTitle: 'Внимание',
      confirmRemoveMessage: 'Вы точно хотите отвязать сабюзера?',
      yesBtn: 'Да',
      noBtn: 'Нет',
    },

    clientSubUsersView: {
      addUserBtn: 'Add User',
      appBarTitle: 'SubUsers',
      appBarUsername: 'Client',
      appUser: 'client',
      mainTitle: 'SubUsers',
      modalAddTitle: 'Create new subuser',
      modalAddBtn: 'Add Subuser',
      modalEditTitle: 'Edit subuser',
      modalEditBtn: 'Save changes',

      successTitle: 'Саб-юзер добавлен',
      failTitle: 'Саб-юзер не добавлен!',
      okBtn: 'Ок',

      confirmTitle: 'Внимание',
      confirmRemoveMessage: 'Вы точно хотите отвязать сабюзера?',
      yesBtn: 'Да',
      noBtn: 'Нет',
    },
    buyerUserView: {
      timer: '14 минут',
      appBarTitle: 'User page',
      appBarUsername: 'Buyer',
      appUser: 'buyer',
    },
    clientUserView: {
      timer: '14 минут',
      appBarTitle: 'User page',
      appBarUsername: 'Client',
      appUser: 'client',
    },
    buyerSubUsersBodyRow: {
      bussinesUnit: 'N/A',
      editBtn: 'Edit User',
      deleteBtn: 'Delete',
    },
    adminSubUsersBodyRow: {
      bussinesUnit: 'N/A',
      editBtn: 'Edit User',
      balanceBtn: 'Balance',
    },
    setBarcodeModalContent: {
      title: 'Установить штрихкод',
      saveBtn: 'Сохранить',
      close: 'Закрыть',
      inputLabel: 'Штрихкод товара:',
    },
    dashboardInfoCard: {
      viewMoreBtn: 'View more',
    },
    clientExchnageModalContent: {
      title: 'Order product',
      orderNowBtn: 'Заказать сразу',
      cancelBtn: 'Отменить',
    },
    supervisorProductsView: {
      appBarTitle: 'Products',
      appBarUsername: 'Supervisor',
      appUser: 'supervisor',
      mainTitle: 'Товары',
    },
    supervisorReadyToCheckView: {
      appBarTitle: 'Ready to check',
      appBarUsername: 'Supervisor',
      appUser: 'supervisor',
      mainTitle: 'Товары на проверку',
    },
    supervisorSettingsView: {
      appBarTitle: 'Settings',
      appBarUsername: 'Supervisor',
      appUser: 'supervisor',
      mainTitle: 'Settings page',
      fieldName: 'Name',
      fieldEmail: 'Email',
      fieldRate: 'Rate',
      fieldRole: 'Role',
      fieldFba: 'FBA',
      saveBtn: 'Сохранить',
      cancelBtn: 'Отменить',
    },
    researcherAddProductForm: {
      buttonCheck: 'Проверить',
      buttonAdd: 'Добавить',
      linkAmazon: 'Введите ссылку с амазона',
      codeOfGood: 'Код товара',
      successActionAlert: 'Operation complete',
    },
    productStatusButtonsConfigs: {
      searchForSupplier: 'Поиск поставщика',
      rejectedBySupervisor: 'Не подходит',
      supplierWasFound: 'Поставщик найден',
      supplierWasNotFound: 'Поставщик не найден',
      supplierPriceNotAccepted: 'Цена поставщика не приемлима',
      publish: 'Опубликовать на бирже',
    },
    deliveryType: {
      road: 'Road',
      sea: 'Sea',
      train: 'Train',
      multiple: 'Multiple',
      air: 'Air',
    },
    orderStatus: {
      formed: 'Formed',
      new: 'New',
      readyToProcess: 'Ready to process',
      atProcess: 'At process',
      paid: 'Paid to supplier',
      trackNumberIssued: 'Track number issued',
      inStock: 'In stock',
      returnOrder: 'Return order',

      closed: 'Closed',
      awaitingShipment: 'Awaiting shipment',
      shipped: 'Shipped',
    },
    productStatusButtons: {
      saveWithoutStatusBtn: 'Сохранить без статуса',
    },
    warehouseType: {
      warehouse0: 'Warehouse 0',
      ont8: 'ONT 8 AMAZON',
      lgb8: 'LGB8 Rialto, CA',
      mem1: 'MEM1 Memphis, TN',
      mdw2: 'MDW2 Joliet, IL',
      lax9: 'LAX9 FONTANA, CA',
      lgb82: 'LGB8 Rialto, CA',
    },
  },
  ru: {
    clientDashboardView: {
      appbarTitle: 'Dashboard',
      balance: 'My balance',
      withdraw: 'Withdraw money',
      replenish: 'Add money',
      inventoryTitle: 'Inventory',
      ordersTitle: 'Orders',
      exchangeTitle: 'Exchange',
      withdrawFunds: 'Вывод средств',
      fillAccount: 'Пополнить счёт',
      itemsInInventorySectionItemTitle: 'Товаров в инвентаре',
      fullCostOfWarehouseSectionItemTitle: 'Общая стоимость склада',
      repurchaseItemsSectionItemTitle: 'Товаров с повторной закупкой',
      notPaidOrdersSectionItemTitle: 'Неоплаченные заказы',
      paidOrdersSectionItemTitle: 'Оплаченные заказы',
      canceledOrdersSectionItemTitle: 'Отмененные заказы',
      soldItemsOnExchangeSectionItemTitle: 'Продано товаров на бирже',
      accuredToReserchersSectionItemTitle: 'Начислено ресерчерам',
      disputsForProductsSectionItemTitle: 'Споров по товарам',
    },
    productView: {
      appBarTitle: 'Product',
      appBarUsername: 'Client',
      appUser: 'client',
      addVendor: 'Добавить нового поставщика',
      editVendor: 'Редактировать поставщика',
    },
    entryLeftPanel: {
      companyName: 'Amazontop',
      greetingTitle: 'Hello, nice to meet you',
      greetingSubtitle: 'Just register to join with us',
      footer: 'Footer',
    },
    appbarComponent: {
      addGood: 'Добавлен новый товар у ресерчера на которого вы подписаны!',
      statusStart: 'Ваш запуск #77777 был ',
      statusEnd: 'обработан!',
      sendGood: 'Заказ #10391 был отправлен на склад платформы',
      allNotifications: 'View all Notifications',
    },
    researcherDashboardView: {
      appBarTitle: 'Dashboard',
      appBarUsername: 'Researcher',
      appUser: 'researcher',
      mainTitle: 'Dashboard',
      myProductsCardTitle: 'Мои товары',
      curBalanceCardTitle: 'Текущий баланс',
      finesCardTitle: 'Штрафы',
      newProductsCardTitle: 'Новых товаров в базе',
      meCheckingCardTitle: 'У меня на проверке',
      accuredCardTitle: 'Начислено',
    },
    buyerComponent: {
      goods: 'Байер - Продукты',
      myGoods: 'Байер - Мои продукты',
      myOrders: 'Байер - Заказы - Мои заказы',
      freeOrders: 'Байер - Заказы - Свободные заказы',
      myStore: 'Байер - Мой склад',
      clickSend: 'При нажатии на кнопку "Отправить свой товар" появляется модальное окно с формой.',
      clickSetBarcode:
        'При нажатии на кнопку "Set barcode" в поле таблицы "Штрихкод" появляется модальное окно с формой.',
      clickReallocate:
        'При нажатии на кнопку "Перераспределить" появляется модальное окно, в котором можно распределить коробки.',
      haveHistory: 'Имеется история действий, которые можно отменять.',
      batchGoods: 'Байер - Партии товаров',
      myProfile: 'Байер - Пользователи - Мой профиль',
      myUsers: 'Байер - Пользователи - Мои пользователи ',
    },
    clientExchangeRequestsView: {
      appbarTitle: 'Exchange - Requests',
      mainTitle: 'My requests on exchange',
      newRequest: 'New request',
      myRequests: 'Мои заявки',
      placeOrderBtn: 'Разместить заявку',

      modalNewRequestTitle: 'New request',
      modalEditRequestTitle: 'Edit request',
      modalCloseRequestTitle: 'Close request',

      modalBtnSendRequest: 'Send request',
      modalBtnSaveRequest: 'Save request',
      modalBtnCloseRequest: 'Send',

      formStrategyLabel: 'Strategy',
      formMonthlySalesLabel: 'Monthly sales',
      formBudgetLabel: 'Budget',
      formAmazonPriceLabel: 'Amazon price',
      formAvgBSRLabel: 'Average BSR',
      formAvgReviewsLabel: 'Average Reviews',
      formAvgRevenueLabel: 'Average Revenue',
      formNotesLabel: 'Notes',
      formCheckboxForbidLabel: 'Запрещать добавлять товары которые когда либо были проданы на площадке',
      formCheckboxNoPayLabel: 'Не оплачиваю повторно купленные товары',
      formDeadlineLabel: 'Target date',
      formCheckboxNoCheckLabel: 'Сотрудники платформы не будут участвовать в проверке качества найденого товара',

      formCloseReasonLabel: 'Describe the reason for closing request',

      selectOptionFlipping: 'Flipping',
      selectOptionDropshipping: 'Dropshipping',
      selectOptionOnlineArbitrage: 'OnlineArbitrage',
      selectOptionPrivateLabel: 'PrivateLabel',

      countOfProposals: 'Count of proposals *',
      countOfOneProposals: 'Cost of one proposal *',
      minProductInProposals: 'Count of min product in proposals *',
      minKeywords: 'Count of min key words in proposals *',
      size: 'Size tier *',
      searchVolume: 'Search volume *',

      editBtn: 'Изменить',
      createBtn: 'Создать заявку',
      cancelBtn: 'Отмена',
    },
    clientComponent: {
      mainPage: 'Клиент - Главная страница',
      nextPages: 'Возможно перейти на следующие страницы:',
      inventory: 'Инвентарь',
      myOrders: 'Мои заказы',
      marketOfGoods: 'Биржа товаров',
      viewMore: 'Переход на другие страницы осуществляется путем нажатие кнопки "View more".',

      marketForks: 'Клиент - Биржа товаров - Биржа вилок',
      clickName: 'При нажатии на имя ресерчера открывается его профиль.',
      privateLabel: 'Клиент - Биржа товаров - Private Label',
      marketGoodsMyOrders: 'Клиент - Биржа товаров - Мои заявки',

      clickMakeOrder: 'При нажатии на кнопку "Разместить заявку" появляется модальное окно с формой.',
      clickEdit: 'При нажатии на кнопки редактировать появляется модальное окно с формой.',

      clientInventory: 'Клиент - Инвентарь',
      clickAddMyGood: 'При нажатии на кнопку "Добавить свой товар" появляется модальное окно с формой.',
      clickExchange:
        'При нажатии на кнопку "Выставить" в поле таблицы "Exchange" появляется поле для ввода цены, за которую продукт будет выставлен на бирже.',
      clickMakeOrderModal: 'При нажатии на кнопку "Заказать"появляется модальное окно с выбранными товарами.',

      clientMyOrders: 'Клиент - Мои заказы',
      clickReallocate:
        'При нажатии на кнопку "Распределять" в поле таблицы "Коробка" перенаправляется на страницу "Мой склад".',
      clickSetBarcode:
        'При нажатии на кнопку "Set barcode" в поле таблицы "Штрихкод" появляется модальное окно с формой.',

      clientMyStore: 'Клиент - Мои склад',
      clickSendMyGood: 'При нажатии на кнопку "Отправить свой товар" появляется модальное окно с формой.',

      clickPereReallocateModal:
        'При нажатии на кнопку "Перераспределить" появляется модальное окно, в котором можно распределить коробки.',
      haveHistory: 'Имеется история действий, которые можно отменять.',
      clientUsersMyProfile: 'Клиент - Пользователи - Мой профиль',
      clickExeModal: 'При нажатии на кнопку "Запустить" появляется модальное окно с формой для запуска Private Label.',

      clientUsersMyUsers: 'Клиент - Пользователи - Мои пользователи',
      clickAddUser:
        'При нажатии на кнопку "Add User" появляется модальное окно с формой, при нажатии кнопки "Manage Premission" откроется еще одно модальное окно.',
      clickEditModal: 'При нажатии на кнопки редактировать появляется модальное окно с формой.',
      clientSettings: 'Клиент - Настройки',
      clientMessages: 'Клиент - Сообщения',

      clientFinances: 'Клиент - Финансы',
      clientProduct: 'Клиент - Продукт',
      clickAddButton: 'При нажатии на кнопку добавления появляется модальное окно с формой.',
      clickEditButton: 'При нажатии на кнопку редактирования появляется модальное окно с формой.',
      clickDeleteButton: 'При нажатии на кнопки удаления, поставщик исчезает из списка.',
    },
    researcherComponent: {
      mainPage: 'Ресерчер - Главная страница',
      moveToMyOrders: 'Возможно перейти на страницу "Мои заказы"',
      viewMore: 'Переход на другие страницы осуществляется путем нажатие кнопки "View more".',
      myOrders: 'Ресерчер - Мои заказы',
      settings: 'Ресерчер - Настройки',
    },
    supervisorComponent: {
      mainPage: 'Супервизор - Главная страница',
      makeMovePages: 'Возможно перейти на следующие страницы:',
      prepareToSend: 'Готовые к проверке',
      myGoods: 'Мои Товары',

      viewMore: 'Переход на другие страницы осуществляется путем нажатие кнопки "View more".',
      supervisorPrepares: 'Супервизор - Готовые к проверке',
      supervisorMyGoods: 'Супервизор - Мои товары',
      settings: 'Супервизор - Настройки',
      productVar1: 'Супервизор - Продукт вариант 1',
    },
    exchangeBodyRow: {
      launchBtn: 'Запустить',
      priceBtn: 'Add $9.99',
    },
    contentCardComponent: {
      time: 'Время осталось',
    },
    addOrEditSupplierModalContent: {
      name: 'Название*',
      link: 'Ссылка*',
      price: 'Цена за шт. $*',
      deliveryPrice: 'Доставка на 1 ед. $*',
      qty: 'Кол-во закупки*',
      minLot: 'Минимальная партия*',
      lotCost: 'Цена партии $*',
      csCode: 'Стоимость $',
      comment: 'Комментарий',
      saveBtn: 'Сохранить',
      cancelBtn: 'Отменить',
      loadTitle: 'Прикрепить фото к задаче',
      availablePhotos: 'Имеющиеся фотографии',
      circularProgressTitle: 'Загрузка фотографий...',
    },
    productWrapperComponent: {
      buttonParseAmazon: ' Parse Amazon ',
      buttonParseSellcentrall: 'Parse Seller central',
      alertSuccess: 'Запрос обработан',
      alertFailed: 'Запрос не был обработан',

      fieldAsin: 'ASIN*',
      fieldLinkAmazon: 'Ссылка на товар Amazon',
      checkboxFba: 'FBA',
      checkboxFbm: 'FBM',
      tableName: 'Имя',
      tableLink: 'Ссылка',
      tablePrice: 'Цена',
      tableSheep: 'Доставка',
      tableCount: 'Количество',
      tableMinBatch: 'Минимальная партия',
      tableBatchCost: 'Цена партии',
      tableCost: 'Стоимость',
      tableComment: 'Комментарий',
      tableCellNoVendors: 'Нет поставщиков',

      typographyComments: 'Комментарии',
      fieldResearcher: 'Ресерчер',
      fieldSoperviser: 'Cупервайзер',
      fieldBuyer: 'Байер',
      buttonAccept: 'Принять',
      buttonCancel: 'Отменить',
      buttonDelete: 'Удалить',

      supplierTitle: 'Список поставщиков',
      supplierActionsTitle: 'Действия: ',

      bsr: 'BSR*',
      amazonPrice: 'Amazon price*',
      fieldWidth: 'Ширина, дюймы*',
      fieldHeight: 'Высота, дюймы*',
      fieldLength: 'Длина, дюймы*',
      fieldWeight: 'Вес, кг*',
      fieldSupplier: 'Поставщик (ссылка)',
      typoExpress: 'Express',
      maxDeliveryPrice: 'Макс. доставка за ед., $',
      delivery: 'Доставка $',
      refferalFee: 'Referral fee, %',
      fbaFee: 'FBA fee , $',
      totalFba: 'Total FBA, $',
      minpurchase: 'Мин. закуп. цена, $',
      recommendedBatch: 'Рекомендованная партия FBA*',
      revenue: 'Прибыль $',
      fieldMargin: 'Маржа, %',
      fieldStatus: 'Status',
      descriptionOFGoods: 'Описание товара',
      csCode: 'Заголовок товара на Amazon',
      summary: 'Краткое описание на Amazon',
      description: 'Подробно',
      category: 'Категория',

      supplierPhotos: 'Фотографии',
      strategyLabel: 'Стратегия продукта',
      deliveryMethod: 'Метод отправки',
    },
    buyerBatchesView: {
      editBatch: 'Редактировать партию',
      mainTitle: 'Партии товаров',
      appBarTitle: 'Batches',
      appBarUsername: 'Buyer',
      appUser: 'buyer',
    },
    clientBatchesView: {
      editBatch: 'Редактировать партию',
      mainTitle: 'Мои отправления',
      appBarTitle: 'Batches',
      appBarUsername: 'Client',
      appUser: 'client',
    },
    adminBatchesView: {
      editBatch: 'Редактировать партию',
      mainTitle: 'Мои отправления',
      appBarTitle: 'Batches',
      appBarUsername: 'Client',
      appUser: 'client',
    },
    ordersViewsModalSetBarcode: {
      title: 'Установить штрихкод',
      code: 'Штрихкод товара:',
      saveBtn: 'Сохранить',
      closeBtn: 'Закрыть',
    },
    ordersViewsModalSetShippingLabel: {
      title: 'Установить Shipping label',
      code: 'Shipping label товара:',
      saveBtn: 'Сохранить',
      closeBtn: 'Закрыть',
    },
    ordersViewsModalEditOrder: {
      title: 'Редактирование заказа',
      orderNum: 'Заказ',
      productNum: 'Продукт',
      saveBtn: 'Сохранить',
      cancelBtn: 'Отмена',
      boxesTitle: 'Коробки по данному заказу:',
      suppliers: 'Поставщики',
      noBoxesYat: 'Коробок пока нет...',
      confirmTitle: 'Внимание.Вы уверены?',
      confirmStatusMessage: 'После сохранения, статус нельзя изменить на более ранний!',
      confirmSubmitMessage: 'Вы уверены что все данные внесены верно?',
      yesBtn: 'Да',
      noBtn: 'Нет',
      addBoxBtn: 'Добавить коробку',
      okBtn: 'ок',
      firstWarning: 'БУДЬТЕ ВНИМАТЕЛЬНЫ!!!',
    },
    freeOrdersView: {
      mainTitle: 'Свободные заказы',
      appBarTitle: 'Страница заказов',
      appBarUsername: 'Buyer',
      appUser: 'buyer',
      ordersBtn: 'Мои заказы',
      pickUp: 'Взять в работу',

      okBtn: 'ок',
      warningTitle: 'Заказ взят в работу и перенесен в раздел Мои заказы',
    },
    myProductsView: {
      mainTitle: 'Мои товары',
      appBarTitle: 'Products',
      appBarUsername: 'Buyer',
      appUser: 'buyer',
    },
    myOrdersView: {
      mainTitle: 'Мои заказы',
      appBarTitle: 'Страница заказов',
      appBarUsername: 'Buyer',
      appUser: 'buyer',
      ordersBtn: 'Мои заказы',
      dimensionsMessage: 'Для создания коробки поля должны быть заполнены!',
      okBtn: 'Ок',
    },

    mergeBoxModal: {
      mainTitle: 'Соедиение коробок:',
      deliveryMethod: 'Метод доставки',
      warehouse: 'Склад',
      valueNone: 'none',
      boxData: 'Данные итоговой коробки:',
      attention: 'Обратите внимание на изменение склада и способа доставки!!!',
      shippingLabel: 'Шиппинглейбл',
      comment: 'Комментарий клиента к задаче',
      saveBtn: 'Соединить',
      cancelBtn: 'Отмена',
    },

    buyerUserExchangeItem: {
      standartPrice: '$ 499',
      startBtn: 'Запустить',
      addBtn: 'Добавить за $ ',
      addBtnAlert: 'Card button click',
    },
    buyerUserActiveOrders: {
      mainTitle: 'Активные предложения на бирже товаров',
      buyGoodsOfUser: 'Купить товары пользователя',
      noActiveOffers: 'Активных предложений не найдено',
    },
    buerUserPurchaseHistory: {
      mainTitle: 'История ваших покупок у ',
      buyInfo: 'Вы приобрели информацию',
      pushedGoods: 'Запущенные товары',
      noHistory: 'История сделок не найдена',
    },
    buerUserReviews: {
      mainTitle: 'Отзывы',
      fromBuyers: 'От покупателей',
      fromSellers: 'От продавцов',
      noReviews: 'Отзывы не найдены',
    },
    buerUserFeedbackCard: {
      positiveReview: 'Положительный отзыв',
      negativeReview: 'Негативный отзыв',
    },
    buyerUserHeaderInfo: {
      mainTitle: 'Информация',
      investorsCount: 'Количество инвесторов',
      goodsFound: 'Товаров нашел',
      transactionsVolume: 'Объем сделок',
      earnedAmount: 'Заработано',
      addInSave: 'Добавили в избранное',
      inBlocked: 'Заблокирован(-а)',
      youBlocked: 'Заблокировал(-а)',
      accountCreateAt: 'Аккаунт создан',
      investors: ' инвесторов',
    },
    buerUserHeaderTested: {
      mainTitle: 'Прошел проверку по стратегиям',
      flipping: 'Флипинг',
      dropShiping: 'Дропшиппинг с Ибей',
      usa: 'Wholesale USA',
      privateLabel: 'Private Label',
    },
    buerUserHeader: {
      sendBtn: 'Отправить заказ',
      filter: 'Фильтровать его товары',
      ignore: 'Игнорировать его товары',
    },
    buyerUserModalContent: {
      mainTitle: 'Заказ товара',
      imgCell: 'Фото',
      categoryCell: 'Категория продукта',
      price: 'Цена',
      count: 'Кол-во',
      avgPrice: 'Ср. цена',
      recBatch: 'Рекомендуемая партия',
      weight: 'Вес',
      avgBsr: 'avg BSR',
      avgReviews: 'avg Reviews',
      avgRevenue: 'avg Revenue',
      costStart: 'Стоимость запуска',
      acManager: 'Аккаунт менеджер',
      buyNowBtn: 'Заказать сразу',
      cancelBtn: 'Отменить',
    },

    clientOrderProductModal: {
      mainTitle: 'Заказ товара',
      imgCell: 'Фото',

      product: 'Товар',
      price: 'Цена',
      avgDeliveryPrice: 'Ср. стоимость доставки за 1 шт.',
      amount: 'Кол-во',
      total: 'Итого',
      barCode: 'Баркод',
      deliveryMethod: 'Способ доставки',
      warehouse: 'Склад',
      comment: 'Комментарий клиента',

      addBasketBtn: 'Добавить в корзину',
      buyNowBtn: 'Заказать сразу',
      cancelBtn: 'Отменить',
    },

    clientBatchesForm: {
      title: 'Список полей для заполнения',
      typoSetChoosenBoxe: 'Задайте нужные значения всем выбранным коробкам.',
      makeChoose: 'Выбор стиля отображения:',
      spaceBetweenStyle: 'Стиль расположения элементов space-between:',
      spaceEvenlyStyle: 'Стиль расположения элементов space-evenly:',
      alignRightStyle: 'Стиль расположения элементов align=right, element spacing=32px:',
      widthHalfStyle: 'Стиль расположения элементов width=1/2 of parent width:',
      warehouse: 'Склад:',
      deliveryMethod: 'Способ доставки:',
      status: 'Статус:',
      track: 'Трек номер США:',
      dispatchDate: 'Ожидаемое время отправки:',
    },
    clientOrdersView: {
      mainTitle: 'Мои заказы',
      appBarTitle: 'Страница заказов',
      appBarUsername: 'Client',
      appUser: 'client',
      ordersBtn: 'Мои заказы',
    },
    clientOrdersNotificationsView: {
      mainTitle: 'Уведомления по заказам',
      appBarTitle: 'Страница уведомлений по заказам',
      appBarUsername: 'Client',
      appUser: 'client',
    },
    adminOrdersView: {
      mainTitle: 'Мои заказы',
      appBarTitle: 'Страница заказов',
      appBarUsername: 'Admin',
      appUser: 'admin',
      ordersBtn: 'Мои заказы',
    },

    adminFinancesView: {
      mainTitle: 'Финансы',
      appBarTitle: 'Страница финансов',
      appBarUsername: 'Admin',
      appUser: 'admin',
    },

    adminTasksView: {
      mainTitle: 'Задачи склада',
      appBarTitle: 'Страница задач склада',
      appBarUsername: 'Admin',
      appUser: 'admin',
      actionBtn: 'Смотреть подробнее',
    },
    clientOrdersTableRow: {
      asinTypo: 'ASIN ',
      setBarcodeLabel: 'Set barcode',
      barcodeDeleteAlert: 'Barcode deleting',
      distributeBtn: 'Распределить',
      titleToolTip: 'Финальный вес будет расчитан когда склад получит товар',
    },
    adminOrdersTableColumns: {
      createDateField: 'Создан',
      updateDateField: 'Обновлен',
      asinTypo: 'ASIN ',
      setBarcodeLabel: 'Set barcode',
      barcodeDeleteAlert: 'Barcode deleting',
      distributeBtn: 'Распределить',
      titleToolTip: 'Финальный вес будет расчитан когда склад получит товар',
      ordersField: 'Заказы',
      barCodeField: 'Баркод',
      amountField: 'Кол-во',
      warehouseField: 'Куда',
      boxField: 'Коробка',
      sumField: 'Сумма',
      weightField: 'Вес',
      grossWeightField: 'Общий вес',
      trackIdField: 'Трек номер',
      statusField: 'Статус',
    },

    subUsersTableColumns: {
      emailField: 'Почта',
      actionField: 'Действия',
    },

    adminFinancesTableColumns: {
      createDateField: 'Создано',
      commentField: 'Комментарий',
      sumField: 'Сумма',
      creatorNameField: 'Инициатор',
      recipientNameField: 'Реципиент ',
    },

    adminSinglePermissionsColumns: {
      createDateField: 'Создано',
      updateDateField: 'Обновлено',
      descriptionField: 'Описание',
      keyField: 'Ключ',
      titleField: 'Название',
      actionField: 'Действия',
    },

    adminGroupPermissionsColumns: {
      createDateField: 'Создано',
      updateDateField: 'Обновлено',
      descriptionField: 'Описание',
      keyField: 'Ключ',
      titleField: 'Название',
      actionField: 'Действия',
    },

    clientOrdersTableColumns: {
      createDateField: 'Дата',
      statusField: 'Статус',
      barCodeField: 'Баркод',

      asinTypo: 'ASIN ',
      setBarcodeLabel: 'Set barcode',
      barcodeDeleteAlert: 'Barcode deleting',
      distributeBtn: 'Распределить',
      titleToolTip: 'Финальный вес будет расчитан когда склад получит товар',
      ordersField: 'Заказы',
      barcodeField: 'Штрих-код',
      amountField: 'Кол-во',
      warehouseField: 'Куда',
      boxField: 'Коробка',
      sumField: 'Сумма',
      weightField: 'Вес',
      grossWeightField: 'Общий вес',
      trackIdField: 'Трек номер',
      neededToPayExtraField: 'Необходимо доплатить',
      forDeliveryFromTheWarehouse: 'Из них за доставку до склада Китая',
    },

    buyerMyOrdersTableColumns: {
      asinTypo: 'ASIN ',
      statusField: 'Статус',
      ordersField: 'Заказы',
      barcodeField: 'Баркод',
      amountField: 'Кол-во',
      warehouseField: 'Склад',
      deliveryField: 'Доставка',
      clientCommentField: 'Комментарий клиента',
      buyerCommentField: 'Комментарий закупщика',
      createdAtField: 'Создан',
      updatedAtField: 'Изменен',
    },

    buyerFreeOrdersTableColumns: {
      asinTypo: 'ASIN ',
      ordersField: 'Заказы',
      barcodeField: 'Баркод',
      amountField: 'Кол-во',
      warehouseField: 'Склад',
      deliveryField: 'Доставка',
      clientCommentField: 'Комментарий клиента',
      buyerCommentField: 'Комментарий закупщика',
      createdAtField: 'Создан',
      actionField: 'Действие',
      pickUp: 'Взять в работу',
    },

    adminBoxesTableColumns: {
      createdAtField: 'Дата создания',
      ordersField: 'Продукт',
      ordersId: 'id Заказа',
      barCode: 'Баркод',
      asinField: 'ASIN',
      qtyField: 'Количество',
      materialField: 'Материал',
      warehouseField: 'Склад',
      boxIdField: 'id Коробки',
      priceField: 'Цена',
      trackIdField: 'Трек id',
      weightField: 'Финальный Вес',
      grossWeightField: 'Общий вес',
    },

    adminUsersTableColumns: {
      createdAtField: 'Created',
      balanceField: 'Balance',
      freezeField: 'Freeze',
      emailField: 'Email',
      rateField: 'Rate',
      roleField: 'Role',
      statusField: 'User status',
      actionsField: 'Actions',

      editBtnText: 'Edit User',
      balanceBtnText: 'Balance',
    },

    clientBoxesTableColumns: {
      createdAtField: 'Создания',
      updatedAtField: 'Обновление',
      ordersField: 'Продукт',
      ordersId: 'id Заказа',
      barCode: 'Баркод',
      asinField: 'ASIN',
      qtyField: 'Количество',
      materialField: 'Материал',
      warehouseField: 'Склад',
      boxIdField: 'id Коробки',
      priceField: 'Цена',
      trackIdField: 'Трек id',
      weightField: 'Финальный Вес',
      grossWeightField: 'Общий вес',
    },

    warehouseBoxesTableColumns: {
      createdAtField: 'Дата создания',
      ordersField: 'Продукт',
      ordersId: 'id Заказа',
      barCode: 'Баркод',
      asinField: 'ASIN',
      qtyField: 'Количество',
      materialField: 'Материал',
      warehouseField: 'Склад',
      boxIdField: 'id Коробки',
      priceField: 'Цена',
      trackIdField: 'Трек id',
      weightField: 'Финальный Вес',
      grossWeightField: 'Общий вес',
    },

    adminTasksTableColumns: {
      createDateField: 'Дата создания',
      updateDateField: 'Последнее обновление',
      typeField: 'Тип',
      descriptionField: 'Описание',
      actionField: 'Действие',
      statusField: 'Статус',

      operatioTypeMerge: 'Соединить',
      operatioTypeSplit: 'Разделить',
      operatioTypeReceive: 'Принять',
      operatioTypeEdit: 'Изменить',

      actionBtn: 'Смотреть подробнее',
    },

    researcherProductsTableColumns: {
      strategyStatusField: 'Strategy',
      asinField: 'ASIN',
      statusField: 'STATUS',
      createDateField: 'Created',
      amazonPriceField: 'Amazon price',
      bsrField: 'BSR',
    },

    researcherProductsRequestsTableColumns: {
      strategyStatusField: 'Strategy',
      createDateField: 'Created',
      deadline: 'Deadline',
      costOfOneProposal: 'Cost of proposal',
      countOfProposals: 'Count of proposals',
    },

    supervisorProductsTableColumns: {
      strategyStatusField: 'Strategy',
      asinField: 'ASIN',
      statusField: 'STATUS',
      createDateField: 'Created',
      amazonPriceField: 'Amazon price',
      bsrField: 'BSR',
      researcherField: 'Researcher',
      buyerField: 'Buyer',

      updateDateField: 'Updated',
      fbafeeField: 'Fba fee',
      profitField: 'Profit',
    },

    buyerProductsTableColumns: {
      strategyStatusField: 'Strategy',
      asinField: 'ASIN',
      statusField: 'STATUS',
      createDateField: 'Created',
      amazonPriceField: 'Amazon price',
      bsrField: 'BSR',

      updateDateField: 'Updated',
      fbafeeField: 'Fba fee',
      feesAndNetField: 'Fees & Net',
      fbaamountField: 'Recommend amount',
    },

    warehouseVacantTasksTableColumns: {
      createDateField: 'Дата создания',
      updateDateField: 'Последнее обновление',
      typeField: 'Тип',
      descriptionField: 'Описание',
      actionField: 'Действие',
      statusField: 'Статус',

      operatioTypeMerge: 'Соединить',
      operatioTypeSplit: 'Разделить',
      operatioTypeReceive: 'Принять',
      operatioTypeEdit: 'Изменить',
      pickUp: 'Взять в работу',
    },

    clientExchangeTableColumns: {
      imageField: 'Image',
      strategyStatusField: 'Strategy',
      actionField: 'Action',
      categoryField: 'Category',
      priceField: 'Amazon price',
      weightField: 'Weight',
      bsrField: 'BSR',
      fbaamountField: 'Recommend batch',
      researcherField: 'Researcher',
      buyerField: 'Buyer',
      byForBtn: 'Купить за',
    },

    clientSearchRequestsTableColumns: {
      actionField: 'Действия',
      createDateField: 'Создана',
      budget: 'Бюджет',
      countOfProposals: 'Необходимо предложений',
      deadline: 'Дедлайн',
      strategyStatusField: 'Стратегия',
      minKeywords: 'Минимально ниш',
      minProductInProposals: 'Минимально продуктов',
      monthlySales: 'Месячные продажи',
      size: 'Размер',
      minAmazonPrice: 'Мин. цена амазона',
      maxAmazonPrice: 'Макс. цена амазона',
      minBSR: 'Мин. бср',
      maxBSR: 'Макс. бср',
      minRevenue: 'Мин. доход',
      maxRevenue: 'Макс. доход',
      minReviews: 'Мин. отзывы',
      maxReviews: 'Макс. отзывы',
    },

    warehouseMyTasksTableColumns: {
      createDateField: 'Дата создания',
      updateDateField: 'Последнее обновление',
      typeField: 'Тип',
      descriptionField: 'Описание',
      actionField: 'Действие',
      statusField: 'Статус',

      operatioTypeMerge: 'Соединить',
      operatioTypeSplit: 'Разделить',
      operatioTypeReceive: 'Принять',
      operatioTypeEdit: 'Изменить',
    },

    warehouseCanceledTasksTableColumns: {
      createDateField: 'Дата создания',
      updateDateField: 'Последнее обновление',
      typeField: 'Тип',
      descriptionField: 'Описание',
      actionField: 'Действие',
      statusField: 'Статус',

      operatioTypeMerge: 'Соединить',
      operatioTypeSplit: 'Разделить',
      operatioTypeReceive: 'Принять',
      operatioTypeEdit: 'Изменить',
      showBtn: 'Смотреть',
    },

    warehouseCompletedTasksTableColumns: {
      createDateField: 'Дата создания',
      updateDateField: 'Последнее обновление',
      typeField: 'Тип',
      descriptionField: 'Описание',
      actionField: 'Действие',
      statusField: 'Статус',

      operatioTypeMerge: 'Соединить',
      operatioTypeSplit: 'Разделить',
      operatioTypeReceive: 'Принять',
      operatioTypeEdit: 'Изменить',
      showBtn: 'Смотреть',
    },

    clientOrderView: {
      mainTitle: 'Заказ',
      appBarTitle: 'Страница заказов',
    },

    ResearcherRequestView: {
      mainTitle: 'Запрос на поск товаров/ниш',
      appBarTitle: 'Страница запросов на поиск',
    },

    ClientRequestView: {
      mainTitle: 'Запрос на поск товаров/ниш',
      appBarTitle: 'Страница запросов на поиск',
    },

    adminOrderView: {
      mainTitle: 'Заказ',
      appBarTitle: 'Страница заказов',
    },

    adminUserPermissionsView: {
      mainTitle: 'Разрешения',
      appBarTitle: 'Разрешения пользователей',
    },

    clientListingView: {
      appBarTitle: 'Листинг продукта',
    },

    clientOrderParameters: {
      minPrice: ' Цена закупки (мин)',
      qty: 'Количество (шт)',
      minBuyPrice: 'Цена покупки',
      supplier: 'Поставщик',
      maxDeliveryPrice: 'Макс доставка за единицу',
      sizes: 'Размеры (дюйм)',
      weight: 'Вес (кг)',
      extraParam: 'Дополнительный параметр',
      extraParamValue: 'Значение',
    },
    clientOrderLeftPanel: {
      id: 'ASIN: ',
      allParameters: 'Все параметры товара',
      close: 'Свернуть',
    },
    clientOrderComments: {
      mainTitle: 'Комментарии',
      buyerLabel: 'Закупщика',
      buyerComment:
        'Бубны распространённый инструмент, есть у разных народов мира, от сибирских шаманов, до индейцев америки.',
      clientLabel: 'Клиента',
      clientComment:
        'На руси бубны существовали еще в языческие времена, на бубнах играли на свадьбах, похоронах, и применяли на охоте и войнах, для устрашения',
    },
    clientOrderInfo: {
      mainTitle: 'Информация о заказе',
      priceBatch: 'Стоимость партии',
      batchPrice: '$ 1000',
      orderSum: 'Сумма заказа',
      orderPrice: '$ 3000',
      boxcList: 'Список коробок',
      boxesCount: 'Коробки, кол-во 40, вес 50 и прочие.',
      sendDate: 'Дата отправки',
      dateSend: '20 09 2020',
      sendNearDate: 'Дата ожи-мой доставки',
      dateNearSend: '30 09 2020',
      docs: 'Документы',
    },
    clientOrderDelivery: {
      mainTitle: 'Доставка',
      deliveryAddress: 'Адрес доставки',
      country: 'Страна*',
      city: 'Город*',
      street: 'Улица*',
      house: 'Дом*',
      deliveryMethod: 'Способ доставки',
    },
    inventoryView: {
      appbarTitle: 'Inventory',
      productsList: 'Products list',
      setBarCodeBtn: 'Set barcode',
      exchangeBtn: 'Exchange',
      setBarcodeChipLabel: 'Set barcode',
      addProductBtn: 'Добавить свой товар',
      addProductModal: 'Добавить свой товар',
    },

    setBarcodeModalContent: {
      title: 'Установить штрихкод',
      saveBtn: 'Сохранить',
      close: 'Закрыть',
      inputLabel: 'Штрихкод товара:',
    },
    dashboardInfoCard: {
      viewMoreBtn: 'View more',
    },
    clientExchnageModalContent: {
      title: 'Order product',
      orderNowBtn: 'Заказать сразу',
      cancelBtn: 'Отменить',
    },
    supervisorProductsView: {
      appBarTitle: 'Products',
      appBarUsername: 'Supervisor',
      appUser: 'supervisor',
      mainTitle: 'Products',
    },
    supervisorSettingsView: {
      appBarTitle: 'Settings',
      appBarUsername: 'Supervisor',
      appUser: 'supervisor',
      mainTitle: 'Settings page',
      fieldName: 'Name',
      fieldEmail: 'Email',
      fieldRate: 'Rate',
      fieldRole: 'Role',
      fieldFba: 'FBA',
      saveBtn: 'Save',
      cancelBtn: 'Cancel',
    },
    supervisorReadyToCheckView: {
      appBarTitle: 'Ready to check',
      appBarUsername: 'Supervisor',
      appUser: 'supervisor',
      mainTitle: 'Товары на проверку',
    },
    researcherAddProductForm: {
      buttonCheck: 'Проверить',
      buttonAdd: 'Добавить',
      linkAmazon: 'Введите ссылку на амазоне',
      codeOfGood: 'Код товара',
      successActionAlert: 'Operation complete',
    },
    warehouseHistory: {
      date: 'Дата создания',
      updateDate: 'Последнее обновление',
      theme: 'Тема',
      description: 'Описание',
      action: 'Действия',
      statusTitle: 'Статус',
    },
    userBalanceHistory: {
      mainTitle: 'Изменения баланса',
      date: 'Дата',
      amount: 'Количество',
      type: 'Тип',
      comment: 'Комментарий',
      reason: 'Причина',
      username: 'Имя пользователя',
      productId: 'Продукт Id',
      noPayments: 'Транзакций пока нет...',
    },
    warehouseHistoryBodyRow: {
      merge: 'Соединение в коробку: ',
      cancelAction: 'Действие отменено',
      unMerge: 'Разъедененние в коробки: ',
      changeStatus: ' изменил статус на ',
      paid: 'Оплачен',
      tasks: 'Задачи складу',
      orderChangeStatus: 'Заказ изменил статус',
      cancelBtn: 'Отменить',
      acceptBtn: 'Подтвердить',
      receive: 'Принять коробку:',
      edit: 'Изменить коробку:',
    },
    warehouseDashboardView: {
      appBarTitle: 'Dashboard',
      appBarUsername: 'Warehouse',
      appUser: 'warehouse',
      mainTitle: 'Dashboard',
      vacantTasksCardTitle: 'Кол-во вакантных задач',
      tasksMyCardTitle: 'Мои задачи',
      vacantBoxesCardTitle: 'Свободные коробки',
      boxesMyCardTitle: 'Мои коробки',
      batchesCardTitle: 'Партии',

      comletedTasksCardTitle: 'Кол-во выполненных задач',
      myStatsCardTitle: 'Моя статистика',
      myPaymentsCardTitle: 'Мои платежи',
      warehouseHistoryTitle: 'Вакантные задачи',
    },

    warehouseVacantTasksView: {
      appBarTitle: 'Dashboard',
      appBarUsername: 'Warehouse',
      appUser: 'warehouse',
      mainTitle: 'Вакантные задачи',
      okBtn: 'Ок',
      pickUp: 'Взять в работу',
      warningTitle: 'Данная задача взята в работу и перенесена в раздел Мои задачи',
    },

    appbarSettingsForm: {
      mainTitle: 'Настройки пользователя',
      noSettingsWarning: 'Настроек пользователя нет',
      everyDayReport: 'Ссылка на ежедневный отчет:',
      emptyPlaceholder: 'Ссылка',
      last30DaysReport: 'Ссылка на отчет за последние 30 дней:',
      editBtn: 'Изменить',
      createBtn: 'Создать',
      cancelBtn: 'Отмена',
    },

    singlePermissions: {
      mainTitle: 'Единичные разрешения',
      okBtn: 'Ок',
      addBtn: 'Добавить',

      confirmTitle: 'Внимание',
      confirmRemovePermMessage: 'Вы точно хотите удалить разрешение?',
      confirmCloseModalMessage: 'Данные не будут сохранены!',
      yesBtn: 'Да',
      noBtn: 'Нет',
    },

    groupPermissions: {
      mainTitle: 'Группы разрешений',
      okBtn: 'Ок',
      addBtn: 'Добавить',

      confirmTitle: 'Внимание',
      confirmRemoveGroupMessage: 'Вы точно хотите удалить группу?',
      confirmCloseModalMessage: 'Данные не будут сохранены!',
      yesBtn: 'Да',
      noBtn: 'Нет',
    },

    warehouseMyTasksView: {
      appBarTitle: 'Dashboard',
      appBarUsername: 'Warehouse',
      appUser: 'warehouse',
      mainTitle: 'Мои задачи',
      taskModalTitle: 'Решить задачу',
      dimensionsMessage: 'Внесите размеры',
      okBtn: 'Ок',

      modalCancelTaskLabel: 'Причина отмена задачи',
      cancelBtn: 'Отмена',
      resolveBtn: 'Решить',

      confirmTitle: 'Внимание',
      confirmMessage: 'Вы точно хотите отменить задачу?',
      yesBtn: 'Да',
      noBtn: 'Нет',
    },

    warehouseCompletedTasksView: {
      appBarTitle: 'Dashboard',
      appBarUsername: 'Warehouse',
      appUser: 'warehouse',
      mainTitle: 'Выполненные задачи',
      showBtn: 'Смотреть',
    },
    warehouseCanceledTasksView: {
      appBarTitle: 'Dashboard',
      appBarUsername: 'Warehouse',
      appUser: 'warehouse',
      mainTitle: 'Отмененные задачи',
      showBtn: 'Смотреть',
    },
    warehouseModalEditTask: {
      batchDestination: 'Не назначен',
      mainTitle: 'Просмотр/редактирование задачи',
      saveBtn: 'Сохранить',
      cancelBtn: 'Отмена',
    },
    warehouseViewsEditBoxModal: {
      title: 'Редактирование коробки',
      addPhotos: 'Добавьте фотографии:',
      saveBtn: 'Сохранить',
      closeBtn: 'Закрыть',

      lengthConfigText: 'Длина:',
      widthConfigText: 'Ширина:',
      heightConfigText: 'Высота:',
      volumeWeightConfigText: 'Вес:',
      weightFinalConfigText: 'Финальный вес:',

      lengthCmWarehouse: 'lengthCmWarehouse',
      widthCmWarehouse: 'widthCmWarehouse',
      heightCmWarehouse: 'heightCmWarehouse',
      weighGrossKgWarehouse: 'weighGrossKgWarehouse',
      volumeWeightKgWarehouse: 'volumeWeightKgWarehouse',
      weightFinalAccountingKgWarehouse: 'weightFinalAccountingKgWarehouse',

      amountOfSubBoxes: 'amountOfSubBoxes',
      amountIfItemsInBox: 'Items in box',
    },
    warehouseReceiveBoxModal: {
      title: 'Принять и распределить',
      redistributionTitle: 'Redistribution',
      newBoxesTitle: 'New boxes',
      productsLeftToRedistribute: 'Left to redistribute',
      qtyLabel: 'Qty',
      toRedistributeBtn: 'To redistribute',
      newBoxBtn: 'New box',
      cancelBtn: 'Cancel',
      actuallyAssembled: 'Actually assembled',
      dimensionsMessage: 'Внесите размеры всех коробок',
      okBtn: 'Ок',
    },

    boxesToCreateTable: {
      title: 'Принять и распределить',
      redistributionTitle: 'Redistribution',
      newBoxesTitle: 'Будут созданы коробки:',
      productsLeftToRedistribute: 'Left to redistribute',
      qtyLabel: 'Qty',
      toRedistributeBtn: 'To redistribute',
      newBoxBtn: 'New box',
      cancelBtn: 'Cancel',
      actuallyAssembled: 'Actually assembled',
      dimensionsMessage: 'Внесите размеры всех коробок',
      okBtn: 'Ок',
    },

    warehouseBeforeAfterBlock: {
      boxNum: 'Коробка номер:',
      count: 'Количество',
      material: 'Материал',
      shippingLabel: 'Шиппинг лебл:',
      setShippingLabel: 'Set shipping label',
      deleteAlert: 'delete',
      demensionsSupplier: 'Размеры от поставщика:',
      demensionsWarehouse: 'Размеры от склада:',
      length: 'Длина: ',
      width: 'Ширина: ',
      height: 'Высота: ',
      weight: 'Вес: ',
      volumeWeigh: 'Удельный вес: ',
      finalWeight: 'Финальный вес: ',
      codeCheck: 'Баркод проклеен поставщиком',
      photos: 'Фотографии:',
      editBtn: 'Редактировать коробку',
      incom: 'Поступление',
      newBoxes: 'Новые коробки',
      superTypo: 'Супер ',
      barCodeReallyIsGlued: 'Баркод действительно проклеен?',
      barCodeIsGluedWarehouse: 'Баркод проклеен складом',
      shippingLabelIsGluedWarehouse: 'Шиппинг лебл был проклеен складом',

      warehouseLabel: 'Склад',
      deliveryMethodLabel: 'Метод доставки',
      statusLabel: 'Статус заказа',
    },

    beforeAfterInfoTaskBlock: {
      boxNum: 'Коробка номер:',
      count: 'Количество',
      material: 'Материал',
      shippingLabel: 'Шиппинг лебл:',
      deleteAlert: 'delete',
      demensions: 'Габариты:',
      length: 'Длина: ',
      width: 'Ширина: ',
      height: 'Высота: ',
      weight: 'Вес: ',
      volumeWeigh: 'Удельный вес: ',
      finalWeight: 'Финальный вес: ',
      codeCheck: 'Баркод проклеен поставщиком',
      photos: 'Фотографии:',
      incom: 'Поступление',
      newBoxes: 'Новые коробки',
      superTypo: 'Супер ',
      barCodeIsGluedWarehouse: 'Баркод проклеен складом',
      shippingLabelIsGluedWarehouse: 'Шиппинг лебл проклеен складом',

      warehouseLabel: 'Склад',
      deliveryMethodLabel: 'Метод доставки',
      statusLabel: 'Статус заказа',
    },

    warehouseTaskForm: {
      taskTitle: 'Данные поступления',
      incomingBoxes: 'Поступившие коробки:',
      saveChangesBtn: 'Сохранить',
      cancelChangesBtn: 'Отмена',
      receiveBoxBtn: 'Принять коробку',
      reReceiveBoxBtn: 'Перераспределить',
    },

    imageFileInput: {
      dragAndDropBtn: 'Click or Drop here',
      hideImagesBtn: 'Hide images',
      showImagesBtn: 'Show images',
      removeAllBtn: 'Remove all',
    },

    warehouseCompletedTaskModal: {
      divideBox: 'Разьедена коробка номер:',
      divideBoxes: 'в коробки под номерами:',
      mergeBoxes: 'Соединины коробки под номерами:',
      mergeBox: 'в коробку номер:',
      receiveBoxes: 'Приняты коробки под номерами:',

      description: 'Описание задачи',
      sendData: 'Данные отправления',
      warehouse: 'Склад: ',
      deliveryMethod: 'Метод доставки: ',
      deliveryStatus: 'Статус доставки: ',
      okBtn: 'Ок',

      taskTitle: 'Данные поступления',
      warehouseLabel: 'Склад',
      deliveryMethodLabel: 'Метод доставки',
      statusLabel: 'Статус',
      incomingBoxes: 'Поступившие коробки:',
      saveChangesBtn: 'Сохранить',
      cancelChangesBtn: 'Отмена',
    },
    warehouseTasksBodyRow: {
      cancelBtn: 'Отменить',
      resolveBtn: 'Решить',
      viewBtn: 'Посмотреть',
      resolved: 'Решено',
      notResolved: 'Не решено',
      pickUp: 'Взять в работу',
      showBtn: 'Смотреть подробнее',

      merge: 'Соединение в коробку',
      unMerge: 'Разъедененние в коробки',
      changeStatus: ' изменил статус на ',
      receive: 'Принять коробку',
      edit: 'Изменить коробку',
    },
    productStatusButtonsConfigs: {
      checkedBySupervisor: 'Продукт подходит',
      sendToSupervisor: 'Создать продукт',
      createWithSupplier: 'Создать с поставщиком',
      searchForSupplier: 'Поиск поставщика (продукт подходит)',
      rejectedBySupervisor: 'Не подходит',
      supplierWasFound: 'Поставщик найден',
      supplierWasNotFound: 'Поставщик не найден',
      supplierPriceNotAccepted: 'Прайс поставщика не подходит',
      publish: 'Опубликовать на бирже',
    },
    boxItemCard: {
      count: 'Количество:',
      barCode: `Баркод:`,
      material: 'Материал',
      codeCheck: 'Баркод проклеен поставщиком',
    },

    taskInfoBoxItemCard: {
      count: 'Количество:',
      barCode: `Баркод:`,
      material: 'Материал',
      codeCheck: 'Баркод проклеен поставщиком',
      trulyСodeCheck: 'Баркод есть, проверено складом',

      isBarCodeAttachedByTheStorekeeper: 'Баркод проклеен складом!',

      category: 'Категория',
      bsr: 'BSR*',
      amazonPrice: 'Amazon price*',
      fieldWidth: 'Ширина, дюймы*',
      fieldHeight: 'Высота, дюймы*',
      fieldLength: 'Длина, дюймы*',
      fieldWeight: 'Вес, кг*',
      fieldSupplier: 'Поставщик (ссылка)',
      typoExpress: 'Express',
      maxDeliveryPrice: 'Макс. доставка за ед., $',
      delivery: 'Доставка $',
      refferalFee: 'Refferal fee , $',
      fbaFee: 'FBA fee , $',
      totalFba: 'Total FBA, $',
      minpurchase: 'Мин. закуп. цена, $',
      recommendedBatch: 'Рекомендованная партия FBA',
      revenue: 'Прибыль $',
      fieldMargin: 'Маржа, %',

      allParameters: 'Показать все параметры товара',
      close: 'Свернуть',
    },
    warehouseWarehouseView: {
      appbarTitle: 'Warehouse',
      mainTitle: 'Boxes for batches',
      confirmSendBatchBtn: 'Confirm send to batch',
    },
    appbarTexts: {
      menuTitle: 'Меню:',
      exit: 'Выйти',

      roleTitle: 'Текущая роль',
      chooseBtn: 'Выбрать',
      settingsBtn: 'Настройки',
    },
    commentsLine: {
      commentLabel: 'Комментарий склада',
      commentPlaceHolder: 'комментарий склада',

      defectiveLabel: 'Брак',
      defectivePlaceHolder: 'получили и нужно вернуть',

      receivedLabel: 'Получено складом',
      receivedPlaceHolder: 'общая сумма всех товаров в коробках когда склад заполнил их',

      differenceLabel: 'Разница',
      differencePlaceHolder: 'разница в количестве',
    },
    taskInfoModal: {
      divideBox: 'Разделить коробки',
      mergeBoxes: 'Соединить коробки',
      receiveBoxes: 'Принять коробку',
      editBox: 'Изменить коробку',
      closeBtn: 'Закрыть',

      clientLabel: 'Комментарий клиента',
      warehouseLabel: 'Комментарий склада',
      clientPlaceholder: 'Комментарий клиента к задаче',
      warehousePlaceholder: 'Комментарий склада к задаче для клиента',
    },

    supervisorReadyToCheckBodyRow: {
      goToWorkBtn: 'Взять в работу',
    },
    buyerFreeOrdersBodyRow: {
      goToWorkBtn: 'Взять в работу',
    },
    buyerReadyToCheckBodyRow: {
      goToWorkBtn: 'Взять в работу',
    },
    editOrderSuppliersTable: {
      fieldAsin: 'ID*',
      fieldLinkAmazon: 'Ссылка на товар Amazon',
      checkboxFba: 'FBA',
      tableName: 'Имя',
      tableLink: 'Ссылка',
      tablePrice: 'Цена',
      tableSheep: 'Доставка',
      tableCount: 'Количество',
      tableMinBatch: 'Минимальная партия',
      tableBatchCost: 'Цена партии',
      tableCost: 'Стоимость',
      tableComment: 'Комментарий',
      tableCellNoVendors: 'Нет поставщиков',
      supplierPhotos: 'Фотографии',
    },
    requestToSendBatchModal: {
      modalTitle: 'Отправка коробок',
    },
  },
}
