export const texts = {
  en: {
    entryLeftPanel: {
      companyName: 'Amazontop',
      greetingTitle: 'Hello, nice to meet you',
      greetingSubtitle: 'Just register to join with us',
      footer: 'Footer',
    },
    rangeInput: {
      start: 'from',
      end: 'to',
    },
    privateLabelCard: {
      price: 'Price',
      qty: 'Qty',
      avgPrice: 'Average price',
      recConsignmentQty: 'Рекомендуемая партия к запуску Private Label',
      recConsignmentWeight: 'Вес рекомендованной партии',
      avgBSR: 'Average BSR',
      avgReviews: 'Average Reviews',
      avgRevenue: 'Average Revenue',
    },
    authView: {
      title: 'Sign in',
      redirect: 'Create account',

      emailLabel: 'Your Email',
      emailPlaceholder: 'example@mail.com',
      passwordLabel: 'Your Password',
      passwordPlaceholder: 'password',
      checkboxLabel: 'Remember me',
      forgotPassword: 'Forgot password',
      button: 'Login',
    },
    registerScreen: {
      title: 'Register',
      redirect: 'Already have account?',

      emailLabel: 'Your Email',
      emailPlaceholder: 'example@mail.com',
      passwordLabel: 'Your Password',
      passwordPlaceholder: 'password',
      rePasswordLabel: 'Re-type Password',
      rePasswordPlaceholder: 'password',
      checkboxLabel: 'Agree with ',
      termsAndConditions: 'Terms & Conditions',
      button: 'Register',
    },
    clientDashboardView: {
      appbarTitle: 'Dashboard',
      balance: 'My balance',
      withdraw: 'Withdraw money',
      replenish: 'Add money',
      inventoryTitle: 'Inventory',
      ordersTitle: 'Orders',
      exchangeTitle: 'Exchange',
    },
    tableToolbar: {
      filter: 'Filter',
      searchPlaceholder: 'Search...',
      rowsPerPage: 'Rows per page',
    },
    clientExchangeView: {
      appbarTitle: 'Exchange',
      mainTitle: 'Active offers on exchange',
      modalOrderProductTitle: 'Order product',
    },
    exchangeBodyRow: {
      labelBtn: 'Private Label',
      priceBtn: 'Add $9.99',
    },
    clientExchangePrivateLabelView: {
      appbarTitle: 'Exchange - PrivateLabel',
      mainTitle: 'Information about Private Label',
    },
    clientExchangeRequestsView: {
      appbarTitle: 'Exchange - Requests',
      mainTitle: 'My requests on exchange',
      newRequest: 'New request',

      modalNewRequestTitle: 'New request',
      modalEditRequestTitle: 'Edit request',
      modalCloseRequestTitle: 'Close request',

      modalBtnSendRequest: 'Send request',
      modalBtnSaveRequest: 'Save request',
      modalBtnCloseRequest: 'Send',

      formStrategyLabel: 'Strategy',
      formMonthlySalesLabel: 'Monthly sales',
      formBudgetLabel: 'Budget',
      formAmazonPriceLabel: 'Amazon price',
      formAvgBSRLabel: 'Average BSR',
      formAvgReviewsLabel: 'Average Reviews',
      formAvgRevenueLabel: 'Average Revenue',
      formNotesLabel: 'Notes',
      formCheckboxForbidLabel:
        'Запрещать добавлять товары которые когда либо были проданы на площадке по данной стратегии',
      formCheckboxNoPayLabel: 'Не оплачиваю повторно купленные товары',
      formDeadlineLabel: 'Target date',
      formCheckboxNoCheckLabel: 'Сотрудники платформы не будут участвовать в проверке качества найденого товара',

      formCloseReasonLabel: 'Describe the reason for closing request',

      selectOptionFlipping: 'Flipping',
      selectOptionDropshipping: 'Dropshipping',
      selectOptionOnlineArbitrage: 'OnlineArbitrage',
      selectOptionPrivateLabel: 'PrivateLabel',
    },
    exchangeRequestsBodyRow: {
      editBtn: 'Edit',
      closeBtn: 'Close',
    },
    documentationView: {
      appBarTitle: 'Documentation',
      appBarUserName: 'User',
      mainTitle: 'Documentation Amazontop',
      mainCreated: 'Created: 12.01.2021',
      mainLastUpdate: '24.03.2021',
      authTitle: 'Аутентификация',
      authLink: 'https://stoic-northcutt-f04ad5.netlify.app/auth',
      authDescription: `При нажатии на "Create account" перенесет на страницу Регистрации`,
      registerTitle: 'Регистрация',
      registerLink: 'https://stoic-northcutt-f04ad5.netlify.app/register',
      registerDescription: `При нажатии на "Already have account" перенесет на страницу Аутентификации`,
    },
    inventoryView: {
      appbarTitle: 'Inventory',
      productsList: 'Products list',
    },
    freelancerDashboardView: {
      appBarTitle: 'Dashboard',
      appBarUsername: 'Freelancer',
      appUser: 'freelancer',
      mainTitle: 'Dashboard',
    },
    freelancerProductsView: {
      appBarTitle: 'Products',
      appBarUsername: 'Freelancer',
      appUser: 'freelancer',
      mainTitle: 'Мои товары',
      cardMainTitle: 'Проверка товара на наличии в базе',
      linkAmazon: 'Введите ссылку на амазоне',
      codeOfGood: 'Код товара',
      buttonChek: 'Проверить',
      buttonAdd: 'Добавить',
    },
    freelancerSettingsView: {
      appBarTitle: 'Settings',
      appBarUsername: 'Freelancer',
      appUser: 'freelancer',
      mainTitle: 'Settings page',
      fieldName: 'Name',
      fieldEmail: 'Email',
      fieldRate: 'Rate',
      fieldRole: 'Role',
      fieldFba: 'FBA',
      saveBtn: 'Сохранить',
      cancelBtn: 'Отменить',
    },
  },
  ru: {
    clientDashboardView: {
      withdrawFunds: 'Вывод средств',
      fillAccount: 'Пополнить счёт',
    },
    productView: {
      appBarTitle: 'Product',
      appBarUsername: 'Client',
      appUser: 'client',
      addVendor: 'Добавить нового поставщика',
      editVendor: 'Редактировать поставщика',
    },
    entryLeftPanel: {
      // change to russian
      companyName: 'Amazontop',
      greetingTitle: 'Hello, nice to meet you',
      greetingSubtitle: 'Just register to join with us',
      footer: 'Footer',
    },
    appbarComponent: {
      addGood: 'Добавлен новый товар у ресерчера на которого вы подписаны!',
      statusStart: 'Ваш запуск #77777 был ',
      statusEnd: 'обработан!',
      sendGood: 'Заказ #10391 был отправлен на склад платформы',
      allNotifications: 'View all Notifications',
    },
    buyerComponent: {
      goods: 'Байер - Продукты',
      myGoods: 'Байер - Мои продукты',
      myOrders: 'Байер - Заказы - Мои заказы',
      freeOrders: 'Байер - Заказы - Свободные заказы',
      myStore: 'Байер - Мой склад',
      clickSend: `При нажатии на кнопку "Отправить свой товар" появляется модальное окно с формой.`,
      clickSetBarcode: `При нажатии на кнопку "Set barcode" в поле таблицы "Штрихкод" появляется модальное окно с формой.`,
      clickReallocate: `При нажатии на кнопку "Перераспределить" появляется модальное окно, в котором можно распределить коробки.`,
      haveHistory: `Имеется история действий, которые можно отменять.`,
      batchGoods: 'Байер - Партии товаров',
      myProfile: 'Байер - Пользователи - Мой профиль',
      myUsers: 'Байер - Пользователи - Мои пользователи ',
    },
    clientComponent: {
      mainPage: 'Клиент - Главная страница',
      nextPages: 'Возможно перейти на следующие страницы:',
      inventory: 'Инвентарь',
      myOrders: 'Мои заказы',
      marketOfGoods: 'Биржа товаров',
      viewMore: `Переход на другие страницы осуществляется путем нажатие кнопки "View more".`,

      marketForks: 'Клиент - Биржа товаров - Биржа вилок',
      clickName: 'При нажатии на имя ресерчера открывается его профиль.',
      privateLabel: 'Клиент - Биржа товаров - Private Label',
      marketGoodsMyOrders: 'Клиент - Биржа товаров - Мои заявки',

      clickMakeOrder: `При нажатии на кнопку "Разместить заявку" появляется модальное окно с формой.`,
      clickEdit: `При нажатии на кнопки редактировать появляется модальное окно с формой.`,

      clientInventory: 'Клиент - Инвентарь',
      clickAddMyGood: `При нажатии на кнопку "Добавить свой товар" появляется модальное окно с формой.`,
      clickExchange: `При нажатии на кнопку "Выставить" в поле таблицы "Exchange" появляется поле для ввода цены, за которую продукт будет выставлен на бирже.`,
      clickMakeOrderModal: `При нажатии на кнопку "Заказать"появляется модальное окно с выбранными товарами.`,

      clientMyOrders: 'Клиент - Мои заказы',
      clickReallocate: `При нажатии на кнопку "Распределять" в поле таблицы "Коробка" перенаправляется на страницу "Мой склад".`,
      clickSetBarcode: `При нажатии на кнопку "Set barcode" в поле таблицы "Штрихкод" появляется модальное окно с формой.`,

      clientMyStore: 'Клиент - Мои склад',
      clickSendMyGood: `При нажатии на кнопку "Отправить свой товар" появляется модальное окно с формой.`,

      clickPereReallocateModal: `При нажатии на кнопку "Перераспределить" появляется модальное окно, в котором можно распределить коробки.`,
      haveHistory: `Имеется история действий, которые можно отменять.`,
      clientUsersMyProfile: 'Клиент - Пользователи - Мой профиль',
      clickExeModal: `При нажатии на кнопку "Запустить" появляется модальное окно с формой для запуска Private Label.`,

      clientUsersMyUsers: 'Клиент - Пользователи - Мои пользователи',
      clickAddUser: `При нажатии на кнопку "Add User" появляется модальное окно с формой, при нажатии кнопки "Manage Premission" откроется еще одно модальное окно.`,
      clickEditModal: `При нажатии на кнопки редактировать появляется модальное окно с формой.`,
      clientSettings: 'Клиент - Настройки',
      clientMessages: 'Клиент - Сообщения',

      clientFinances: 'Клиент - Финансы',
      clientProduct: 'Клиент - Продукт',
      clickAddButton: `При нажатии на кнопку добавления появляется модальное окно с формой.`,
      clickEditButton: `При нажатии на кнопку редактирования появляется модальное окно с формой.`,
      clickDeleteButton: `При нажатии на кнопки удаления, поставщик исчезает из списка.`,
    },
    freelancerComponent: {
      mainPage: 'Ресерчер - Главная страница',
      moveToMyOrders: `Возможно перейти на страницу "Мои заказы"`,
      viewMore: `Переход на другие страницы осуществляется путем нажатие кнопки "View more".`,
      myOrders: 'Ресерчер - Мои заказы',
      settings: 'Ресерчер - Настройки',
    },
    supervisorComponent: {
      mainPage: 'Супервизор - Главная страница',
      makeMovePages: 'Возможно перейти на следующие страницы:',
      prepareToSend: 'Готовые к проверке',
      myGoods: 'Мои Товары',

      viewMore: `Переход на другие страницы осуществляется путем нажатие кнопки "View more".`,
      supervisorPrepares: 'Супервизор - Готовые к проверке',
      supervisorMyGoods: 'Супервизор - Мои товары',
      settings: 'Супервизор - Настройки',
      productVar1: 'Супервизор - Продукт вариант 1',
    },
    contentCardComponent: {
      time: 'Время осталось',
    },
    modalContent: {
      name: 'Название',
      link: 'Ссылка',
      price: 'Цена за шт.',
      deliveryPrice: 'Доставка на 1 ед.',
      qty: 'Кол-во закупки',
      minQty: 'Минимальная партия',
      csCode: 'Цена партии',
      comment: 'Комментарий',
      saveBtn: 'Сохранить',
      cancelBtn: 'Отменить',
    },
    productWrapperComponent: {
      buttonParseAmazon: ' Parse Amazon ',
      buttonParseSellcentrall: 'Parse Sellcentrall',
      alertSuccess: 'Данные успешно получены.',

      fieldAsin: 'ID*',
      fieldLinkAmazon: 'Ссылка на товар Amazon',
      checkboxFba: 'FBA',
      tableName: 'Имя',
      tableLink: 'Ссылка',
      tablePrice: 'Цена',
      tableSheep: 'Доставка',
      tableCount: 'Количество',
      tableMinBatch: 'Минимальная партия',
      tableCost: 'Стоимость',
      tableComment: 'Комментарий',
      tableCellNoVendors: 'Нет поставщиков',

      typographyComments: 'Комментарии',
      fieldManager: 'Менеджер',
      fieldSoperviser: 'Cупервайзер',
      fieldBuyer: 'Байер',
      buttonAccept: 'Принять',
      buttonCancel: 'Отменить',
      buttonDelete: 'Удалить',

      bsr: 'BSR*',
      buyBoxPrice: 'Buybox price*',
      fieldWidth: 'Ширина, дюймы*',
      fieldHeight: 'Высота, дюймы*',
      fieldLength: 'Длина, дюймы*',
      minPrice: 'Мин. закуп. цена',
      fieldSupplier: 'Поставщик, $',
      typoExpress: 'Express',
      maxDeliveryPrice: 'Max. Доставка за ед., $',
      refferalFee: 'Refferal fee , $',
      fbaFee: 'FBA fee , $',
      totalFba: 'Total FBA, $',
      recConsignmentQty: 'Рекомендованная партия FBA',
      revenue: 'Прибыль $',
      fieldMargin: 'Маржа, %',
      fieldStatus: 'Status',
      descriptionOFGoods: 'Описание товара',
      csCode: 'Заголовок товара на Amazon',
      summary: 'Краткое описание на Amazon',
      description: 'Подробно',
    },
  },
}
