export const texts = {
  en: {
    entryLeftPanel: {
      companyName: 'Amazontop',
      greetingTitle: 'Hello, nice to meet you',
      greetingSubtitle: 'Just register to join with us',
      footer: 'Footer',
    },
    authView: {
      title: 'Sign in',
      redirect: 'Create account',

      emailLabel: 'Your Email',
      emailPlaceholder: 'example@mail.com',
      passwordLabel: 'Your Password',
      passwordPlaceholder: 'password',
      checkboxLabel: 'Remember me',
      forgotPassword: 'Forgot password',
      button: 'Login',
    },
    registerScreen: {
      title: 'Register',
      redirect: 'Already have account?',

      emailLabel: 'Your Email',
      emailPlaceholder: 'example@mail.com',
      passwordLabel: 'Your Password',
      passwordPlaceholder: 'password',
      rePasswordLabel: 'Re-type Password',
      rePasswordPlaceholder: 'password',
      checkboxLabel: 'Agree with ',
      termsAndConditions: 'Terms & Conditions',
      button: 'Register',
    },
    clientDashboardView: {
      appbarTitle: 'Dashboard',
      balance: 'My balance',
      withdraw: 'Withdraw money',
      replenish: 'Add money',
      inventoryTitle: 'Inventory',
      ordersTitle: 'Orders',
      exchangeTitle: 'Exchange',
    },
    documentationView: {
      appBarTitle: 'Documentation',
      appBarUserName: 'User',
      mainTitle: 'Documentation Amazontop',
      mainCreated: 'Created: 12.01.2021',
      mainLastUpdate: '24.03.2021',
      authTitle: 'Аутентификация',
      authLink: 'https://stoic-northcutt-f04ad5.netlify.app/auth',
      authDescription: `При нажатии на "Create account" перенесет на страницу Регистрации`,
      registerTitle: 'Регистрация',
      registerLink: 'https://stoic-northcutt-f04ad5.netlify.app/register',
      registerDescription: `При нажатии на "Already have account" перенесет на страницу Аутентификации`,
    },
    iventoryView: {
      appBarTitle: 'Inventory',
      appBarUsername: 'Client',
      appUser: 'client',
      listOfGoods: 'Список товаров',
    },
  },
  ru: {
    clientDashboardView: {
      withdrawFunds: 'Вывод средств',
      fillAccount: 'Пополнить счёт',
    },
    entryLeftPanel: {
      // change to russian
      companyName: 'Amazontop',
      greetingTitle: 'Hello, nice to meet you',
      greetingSubtitle: 'Just register to join with us',
      footer: 'Footer',
    },
    appbarComponent: {
      addGood: 'Добавлен новый товар у ресерчера на которого вы подписаны!',
      statusStart: 'Ваш запуск #77777 был ',
      statusEnd: 'обработан!',
      sendGood: 'Заказ #10391 был отправлен на склад платформы',
      allNotifications: 'View all Notifications',
    },
    buyerComponent: {
      goods: 'Байер - Продукты',
      myGoods: 'Байер - Мои продукты',
      myOrders: 'Байер - Заказы - Мои заказы',
      freeOrders: 'Байер - Заказы - Свободные заказы',
      myStore: 'Байер - Мой склад',
      clickSend: `При нажатии на кнопку "Отправить свой товар" появляется модальное окно с формой.`,
      clickSetBarcode: `При нажатии на кнопку "Set barcode" в поле таблицы "Штрихкод" появляется модальное окно с формой.`,
      clickReallocate: `При нажатии на кнопку "Перераспределить" появляется модальное окно, в котором можно распределить коробки.`,
      haveHistory: `Имеется история действий, которые можно отменять.`,
      batchGoods: 'Байер - Партии товаров',
      myProfile: 'Байер - Пользователи - Мой профиль',
      myUsers: 'Байер - Пользователи - Мои пользователи ',
    },
    clientComponent: {
      mainPage: 'Клиент - Главная страница',
      nextPages: 'Возможно перейти на следующие страницы:',
      inventory: 'Инвентарь',
      myOrders: 'Мои заказы',
      marketOfGoods: 'Биржа товаров',
      viewMore: `Переход на другие страницы осуществляется путем нажатие кнопки "View more".`,

      marketForks: 'Клиент - Биржа товаров - Биржа вилок',
      clickName: 'При нажатии на имя ресерчера открывается его профиль.',
      privateLabel: 'Клиент - Биржа товаров - Private Label',
      marketGoodsMyOrders: 'Клиент - Биржа товаров - Мои заявки',

      clickMakeOrder: `При нажатии на кнопку "Разместить заявку" появляется модальное окно с формой.`,
      clickEdit: `При нажатии на кнопки редактировать появляется модальное окно с формой.`,

      clientInventory: 'Клиент - Инвентарь',
      clickAddMyGood: `При нажатии на кнопку "Добавить свой товар" появляется модальное окно с формой.`,
      clickExchange: `При нажатии на кнопку "Выставить" в поле таблицы "Exchange" появляется поле для ввода цены, за которую продукт будет выставлен на бирже.`,
      clickMakeOrderModal: `При нажатии на кнопку "Заказать"появляется модальное окно с выбранными товарами.`,

      clientMyOrders: 'Клиент - Мои заказы',
      clickReallocate: `При нажатии на кнопку "Распределять" в поле таблицы "Коробка" перенаправляется на страницу "Мой склад".`,
      clickSetBarcode: `При нажатии на кнопку "Set barcode" в поле таблицы "Штрихкод" появляется модальное окно с формой.`,

      clientMyStore: 'Клиент - Мои склад',
      clickSendMyGood: `При нажатии на кнопку "Отправить свой товар" появляется модальное окно с формой.`,

      clickPereReallocateModal: `При нажатии на кнопку "Перераспределить" появляется модальное окно, в котором можно распределить коробки.`,
      haveHistory: `Имеется история действий, которые можно отменять.`,
      clientUsersMyProfile: 'Клиент - Пользователи - Мой профиль',
      clickExeModal: `При нажатии на кнопку "Запустить" появляется модальное окно с формой для запуска Private Label.`,

      clientUsersMyUsers: 'Клиент - Пользователи - Мои пользователи',
      clickAddUser: `При нажатии на кнопку "Add User" появляется модальное окно с формой, при нажатии кнопки "Manage Premission" откроется еще одно модальное окно.`,
      clickEditModal: `При нажатии на кнопки редактировать появляется модальное окно с формой.`,
      clientSettings: 'Клиент - Настройки',
      clientMessages: 'Клиент - Сообщения',

      clientFinances: 'Клиент - Финансы',
      clientProduct: 'Клиент - Продукт',
      clickAddButton: `При нажатии на кнопку добавления появляется модальное окно с формой.`,
      clickEditButton: `При нажатии на кнопку редактирования появляется модальное окно с формой.`,
      clickDeleteButton: `При нажатии на кнопки удаления, поставщик исчезает из списка.`,
    },
    freelancerComponent: {
      mainPage: 'Ресерчер - Главная страница',
      moveToMyOrders: `Возможно перейти на страницу "Мои заказы"`,
      viewMore: `Переход на другие страницы осуществляется путем нажатие кнопки "View more".`,
      myOrders: 'Ресерчер - Мои заказы',
      settings: 'Ресерчер - Настройки',
    },
    supervisorComponent: {
      mainPage: 'Супервизор - Главная страница',
      makeMovePages: 'Возможно перейти на следующие страницы:',
      prepareToSend: 'Готовые к проверке',
      myGoods: 'Мои Товары',

      viewMore: `Переход на другие страницы осуществляется путем нажатие кнопки "View more".`,
      supervisorPrepares: 'Супервизор - Готовые к проверке',
      supervisorMyGoods: 'Супервизор - Мои товары',
      settings: 'Супервизор - Настройки',
      productVar1: 'Супервизор - Продукт вариант 1',
    },
    contentCardComponent: {
      time: 'Время осталось',
    },
  },
}
