export const UserRole = {
  ADMIN: 'ADMIN',
  CLIENT: 'CLIENT',
  SUPERVISOR: 'SUPERVISOR',
  RESEARCHER: 'RESEARCHER',
  BUYER: 'BUYER',
  STOREKEEPER: 'STOREKEEPER',
}

export const UserRoleCodeMap = {
  0: 'ADMIN',
  10: 'CLIENT',
  20: 'SUPERVISOR',
  30: 'RESEARCHER',
  40: 'BUYER',
  45: 'STOREKEEPER',
  50: 'CANDIDATE',
}
