export const patchSuppliers = [
  'name',
  'link',
  'price',
  'amount',
  'minlot',
  'multiplicity',
  'paymentMethods',
  'images',
  'comment',
  'yuanRate',
  'priceInYuan',
  'batchDeliveryCostInDollar',
  'batchDeliveryCostInYuan',
  'batchTotalCostInDollar',
  'batchTotalCostInYuan',
  'productionTerm',
  'boxProperties',
  'priceVariations',
]

export const creatSupplier = [
  'name',
  'link',
  'price',
  'amount',
  'minlot',
  'multiplicity',
  'paymentMethods',
  'images',
  'comment',
  'yuanRate',
  'priceInYuan',
  'batchDeliveryCostInDollar',
  'batchDeliveryCostInYuan',
  'batchTotalCostInDollar',
  'batchTotalCostInYuan',
  'productionTerm',
  'boxProperties',
  'priceVariations',
]

export const IdeaPatch = [
  'title',
  'media',
  'comments',
  'productName',
  'productLinks',
  'criteria',
  'quantity',
  'price',
  'width',
  'height',
  'length',
]
