export enum BoxStatus {
  NEW = 'NEW',
  IN_STOCK = 'IN_STOCK',
  REQUESTED_SEND_TO_BATCH = 'REQUESTED_SEND_TO_BATCH',
  NEED_CONFIRMING_TO_DELIVERY_PRICE_CHANGE = 'NEED_CONFIRMING_TO_DELIVERY_PRICE_CHANGE',
  IN_BATCH = 'IN_BATCH',
  IN_BATCH_ON_THE_WAY = 'IN_BATCH_ON_THE_WAY',
  FINISH_PREP_CENTR_USA = 'FINISH_PREP_CENTR_USA',
  NEED_TO_UPDATE_THE_TARIFF = 'NEED_TO_UPDATE_THE_TARIFF',
  ACCEPTED_IN_PROCESSING = 'ACCEPTED_IN_PROCESSING',
}
