/**
 * amazonapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiV1AdminsUsersPermissions model module.
 * @module model/ApiV1AdminsUsersPermissions
 * @version v0.0.1
 */
class ApiV1AdminsUsersPermissions {
    /**
     * Constructs a new <code>ApiV1AdminsUsersPermissions</code>.
     * Отобразить permission
     * @alias module:model/ApiV1AdminsUsersPermissions
     * @param _id {String} GUID Permission в базе данных
     * @param key {String} Permission ключ
     * @param title {String} Простое название
     * @param description {String} Описание permission
     * @param allowedUrl {Array.<String>} Массив доступных url.
     * @param createdById {String} GUID любого, кто последний создал permission.
     * @param createdAt {Date} Дата создания
     * @param updatedAt {Date} Дата изменения
     */
    constructor(_id, key, title, description, allowedUrl, createdById, createdAt, updatedAt) { 
        
        ApiV1AdminsUsersPermissions.initialize(this, _id, key, title, description, allowedUrl, createdById, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _id, key, title, description, allowedUrl, createdById, createdAt, updatedAt) { 
        obj['_id'] = _id;
        obj['key'] = key;
        obj['title'] = title;
        obj['description'] = description;
        obj['allowedUrl'] = allowedUrl;
        obj['createdById'] = createdById;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>ApiV1AdminsUsersPermissions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1AdminsUsersPermissions} obj Optional instance to populate.
     * @return {module:model/ApiV1AdminsUsersPermissions} The populated <code>ApiV1AdminsUsersPermissions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1AdminsUsersPermissions();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('allowedUrl')) {
                obj['allowedUrl'] = ApiClient.convertToType(data['allowedUrl'], ['String']);
            }
            if (data.hasOwnProperty('createdById')) {
                obj['createdById'] = ApiClient.convertToType(data['createdById'], 'String');
            }
            if (data.hasOwnProperty('lastModifiedById')) {
                obj['lastModifiedById'] = ApiClient.convertToType(data['lastModifiedById'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * GUID Permission в базе данных
 * @member {String} _id
 */
ApiV1AdminsUsersPermissions.prototype['_id'] = undefined;

/**
 * Permission ключ
 * @member {String} key
 */
ApiV1AdminsUsersPermissions.prototype['key'] = undefined;

/**
 * Простое название
 * @member {String} title
 */
ApiV1AdminsUsersPermissions.prototype['title'] = undefined;

/**
 * Описание permission
 * @member {String} description
 */
ApiV1AdminsUsersPermissions.prototype['description'] = undefined;

/**
 * Массив доступных url.
 * @member {Array.<String>} allowedUrl
 */
ApiV1AdminsUsersPermissions.prototype['allowedUrl'] = undefined;

/**
 * GUID любого, кто последний создал permission.
 * @member {String} createdById
 */
ApiV1AdminsUsersPermissions.prototype['createdById'] = undefined;

/**
 * GUID любого, кто последний редактировал permission.
 * @member {String} lastModifiedById
 */
ApiV1AdminsUsersPermissions.prototype['lastModifiedById'] = undefined;

/**
 * Дата создания
 * @member {Date} createdAt
 */
ApiV1AdminsUsersPermissions.prototype['createdAt'] = undefined;

/**
 * Дата изменения
 * @member {Date} updatedAt
 */
ApiV1AdminsUsersPermissions.prototype['updatedAt'] = undefined;






export default ApiV1AdminsUsersPermissions;

