/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse20027Batch model module.
 * @module model/InlineResponse20027Batch
 * @version 0.1.0
 */
class InlineResponse20027Batch {
    /**
     * Constructs a new <code>InlineResponse20027Batch</code>.
     * @alias module:model/InlineResponse20027Batch
     */
    constructor() { 
        
        InlineResponse20027Batch.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20027Batch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20027Batch} obj Optional instance to populate.
     * @return {module:model/InlineResponse20027Batch} The populated <code>InlineResponse20027Batch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20027Batch();

            if (data.hasOwnProperty('isBeingCollected')) {
                obj['isBeingCollected'] = ApiClient.convertToType(data['isBeingCollected'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} isBeingCollected
 */
InlineResponse20027Batch.prototype['isBeingCollected'] = undefined;






export default InlineResponse20027Batch;

