/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse20030Finances from './InlineResponse20030Finances';
import InlineResponse20030Orders from './InlineResponse20030Orders';
import InlineResponse20030PendingOrders from './InlineResponse20030PendingOrders';
import InlineResponse20030Products from './InlineResponse20030Products';

/**
 * The InlineResponse20030 model module.
 * @module model/InlineResponse20030
 * @version 0.1.0
 */
class InlineResponse20030 {
    /**
     * Constructs a new <code>InlineResponse20030</code>.
     * @alias module:model/InlineResponse20030
     */
    constructor() { 
        
        InlineResponse20030.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20030</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20030} obj Optional instance to populate.
     * @return {module:model/InlineResponse20030} The populated <code>InlineResponse20030</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20030();

            if (data.hasOwnProperty('products')) {
                obj['products'] = InlineResponse20030Products.constructFromObject(data['products']);
            }
            if (data.hasOwnProperty('orders')) {
                obj['orders'] = InlineResponse20030Orders.constructFromObject(data['orders']);
            }
            if (data.hasOwnProperty('pendingOrders')) {
                obj['pendingOrders'] = InlineResponse20030PendingOrders.constructFromObject(data['pendingOrders']);
            }
            if (data.hasOwnProperty('finances')) {
                obj['finances'] = InlineResponse20030Finances.constructFromObject(data['finances']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse20030Products} products
 */
InlineResponse20030.prototype['products'] = undefined;

/**
 * @member {module:model/InlineResponse20030Orders} orders
 */
InlineResponse20030.prototype['orders'] = undefined;

/**
 * @member {module:model/InlineResponse20030PendingOrders} pendingOrders
 */
InlineResponse20030.prototype['pendingOrders'] = undefined;

/**
 * @member {module:model/InlineResponse20030Finances} finances
 */
InlineResponse20030.prototype['finances'] = undefined;






export default InlineResponse20030;

