/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject37 model module.
 * @module model/InlineObject37
 * @version 0.1.0
 */
class InlineObject37 {
    /**
     * Constructs a new <code>InlineObject37</code>.
     * @alias module:model/InlineObject37
     */
    constructor() { 
        
        InlineObject37.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject37</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject37} obj Optional instance to populate.
     * @return {module:model/InlineObject37} The populated <code>InlineObject37</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject37();

            if (data.hasOwnProperty('storekeeperId')) {
                obj['storekeeperId'] = ApiClient.convertToType(data['storekeeperId'], 'String');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = ApiClient.convertToType(data['item'], 'String');
            }
            if (data.hasOwnProperty('logicsTariffId')) {
                obj['logicsTariffId'] = ApiClient.convertToType(data['logicsTariffId'], 'String');
            }
            if (data.hasOwnProperty('trackNumberText')) {
                obj['trackNumberText'] = ApiClient.convertToType(data['trackNumberText'], 'String');
            }
            if (data.hasOwnProperty('trackNumberFile')) {
                obj['trackNumberFile'] = ApiClient.convertToType(data['trackNumberFile'], 'String');
            }
            if (data.hasOwnProperty('destinationId')) {
                obj['destinationId'] = ApiClient.convertToType(data['destinationId'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('deliveryCostToTheWarehouse')) {
                obj['deliveryCostToTheWarehouse'] = ApiClient.convertToType(data['deliveryCostToTheWarehouse'], 'Number');
            }
            if (data.hasOwnProperty('clientComment')) {
                obj['clientComment'] = ApiClient.convertToType(data['clientComment'], 'String');
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * GUID storekeeper-a
 * @member {String} storekeeperId
 */
InlineObject37.prototype['storekeeperId'] = undefined;

/**
 * @member {String} item
 */
InlineObject37.prototype['item'] = undefined;

/**
 * GUID тарифа доставки
 * @member {String} logicsTariffId
 */
InlineObject37.prototype['logicsTariffId'] = undefined;

/**
 * Текст трек номера
 * @member {String} trackNumberText
 */
InlineObject37.prototype['trackNumberText'] = undefined;

/**
 * Ссылка на фото трек номера
 * @member {String} trackNumberFile
 */
InlineObject37.prototype['trackNumberFile'] = undefined;

/**
 * GUID пункта назначения.
 * @member {String} destinationId
 */
InlineObject37.prototype['destinationId'] = undefined;

/**
 * Кол-во продукта по этой позиции.
 * @member {Number} amount
 */
InlineObject37.prototype['amount'] = undefined;

/**
 * Стоимость доставки до склада.
 * @member {Number} deliveryCostToTheWarehouse
 */
InlineObject37.prototype['deliveryCostToTheWarehouse'] = undefined;

/**
 * Комментарии клиента.
 * @member {String} clientComment
 */
InlineObject37.prototype['clientComment'] = undefined;

/**
 * Массив изображений.
 * @member {Array.<String>} images
 */
InlineObject37.prototype['images'] = undefined;






export default InlineObject37;

