/**
 * amazonapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject23 model module.
 * @module model/InlineObject23
 * @version v0.0.1
 */
class InlineObject23 {
    /**
     * Constructs a new <code>InlineObject23</code>.
     * @alias module:model/InlineObject23
     */
    constructor() { 
        
        InlineObject23.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject23</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject23} obj Optional instance to populate.
     * @return {module:model/InlineObject23} The populated <code>InlineObject23</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject23();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('delivery')) {
                obj['delivery'] = ApiClient.convertToType(data['delivery'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('minlot')) {
                obj['minlot'] = ApiClient.convertToType(data['minlot'], 'Number');
            }
            if (data.hasOwnProperty('lotcost')) {
                obj['lotcost'] = ApiClient.convertToType(data['lotcost'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * id поставщика.
 * @member {String} id
 */
InlineObject23.prototype['id'] = undefined;

/**
 * Название поставщика.
 * @member {String} name
 */
InlineObject23.prototype['name'] = undefined;

/**
 * Ссылка на поставщика.
 * @member {String} link
 */
InlineObject23.prototype['link'] = undefined;

/**
 * Цена
 * @member {Number} price
 */
InlineObject23.prototype['price'] = undefined;

/**
 * Тип доставки
 * @member {Number} delivery
 */
InlineObject23.prototype['delivery'] = undefined;

/**
 * кол-во
 * @member {Number} amount
 */
InlineObject23.prototype['amount'] = undefined;

/**
 * Минимальный лот.
 * @member {Number} minlot
 */
InlineObject23.prototype['minlot'] = undefined;

/**
 * Стоимость лота.
 * @member {Number} lotcost
 */
InlineObject23.prototype['lotcost'] = undefined;

/**
 * Комментарий
 * @member {String} comment
 */
InlineObject23.prototype['comment'] = undefined;






export default InlineObject23;

