/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject35 model module.
 * @module model/InlineObject35
 * @version 0.1.0
 */
class InlineObject35 {
    /**
     * Constructs a new <code>InlineObject35</code>.
     * @alias module:model/InlineObject35
     * @param attachedDocuments {Array.<String>} 
     */
    constructor(attachedDocuments) { 
        
        InlineObject35.initialize(this, attachedDocuments);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, attachedDocuments) { 
        obj['attachedDocuments'] = attachedDocuments;
    }

    /**
     * Constructs a <code>InlineObject35</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject35} obj Optional instance to populate.
     * @return {module:model/InlineObject35} The populated <code>InlineObject35</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject35();

            if (data.hasOwnProperty('attachedDocuments')) {
                obj['attachedDocuments'] = ApiClient.convertToType(data['attachedDocuments'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} attachedDocuments
 */
InlineObject35.prototype['attachedDocuments'] = undefined;






export default InlineObject35;

