/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject67 model module.
 * @module model/InlineObject67
 * @version 0.1.0
 */
class InlineObject67 {
    /**
     * Constructs a new <code>InlineObject67</code>.
     * @alias module:model/InlineObject67
     */
    constructor() { 
        
        InlineObject67.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject67</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject67} obj Optional instance to populate.
     * @return {module:model/InlineObject67} The populated <code>InlineObject67</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject67();

            if (data.hasOwnProperty('suppliersIds')) {
                obj['suppliersIds'] = ApiClient.convertToType(data['suppliersIds'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * GUIDы поставщиков, которые нужно добавить в БД.
 * @member {Array.<String>} suppliersIds
 */
InlineObject67.prototype['suppliersIds'] = undefined;






export default InlineObject67;

