/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse20063 model module.
 * @module model/InlineResponse20063
 * @version 0.1.0
 */
class InlineResponse20063 {
    /**
     * Constructs a new <code>InlineResponse20063</code>.
     * @alias module:model/InlineResponse20063
     */
    constructor() { 
        
        InlineResponse20063.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20063</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20063} obj Optional instance to populate.
     * @return {module:model/InlineResponse20063} The populated <code>InlineResponse20063</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20063();

            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('requestPlatformMarginInPercent')) {
                obj['requestPlatformMarginInPercent'] = ApiClient.convertToType(data['requestPlatformMarginInPercent'], 'Number');
            }
            if (data.hasOwnProperty('platformMargin')) {
                obj['platformMargin'] = ApiClient.convertToType(data['platformMargin'], 'Number');
            }
            if (data.hasOwnProperty('requestSupervisorFeeInPercent')) {
                obj['requestSupervisorFeeInPercent'] = ApiClient.convertToType(data['requestSupervisorFeeInPercent'], 'Number');
            }
            if (data.hasOwnProperty('supervisorFee')) {
                obj['supervisorFee'] = ApiClient.convertToType(data['supervisorFee'], 'Number');
            }
            if (data.hasOwnProperty('unitCost')) {
                obj['unitCost'] = ApiClient.convertToType(data['unitCost'], 'Number');
            }
            if (data.hasOwnProperty('maxAmountOfProposals')) {
                obj['maxAmountOfProposals'] = ApiClient.convertToType(data['maxAmountOfProposals'], 'Number');
            }
            if (data.hasOwnProperty('totalCost')) {
                obj['totalCost'] = ApiClient.convertToType(data['totalCost'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Цена за каждое предложение.
 * @member {Number} price
 */
InlineResponse20063.prototype['price'] = undefined;

/**
 * Процент с каждого предложения, маржа платформы, в процентах.
 * @member {Number} requestPlatformMarginInPercent
 */
InlineResponse20063.prototype['requestPlatformMarginInPercent'] = undefined;

/**
 * Услуги платформы.
 * @member {Number} platformMargin
 */
InlineResponse20063.prototype['platformMargin'] = undefined;

/**
 * Процент с каждого предложения для супервайзера, в процентах.
 * @member {Number} requestSupervisorFeeInPercent
 */
InlineResponse20063.prototype['requestSupervisorFeeInPercent'] = undefined;

/**
 * Услуги супервайзера.
 * @member {Number} supervisorFee
 */
InlineResponse20063.prototype['supervisorFee'] = undefined;

/**
 * Сумма.
 * @member {Number} unitCost
 */
InlineResponse20063.prototype['unitCost'] = undefined;

/**
 * Количество предложений, не менее.
 * @member {Number} maxAmountOfProposals
 */
InlineResponse20063.prototype['maxAmountOfProposals'] = undefined;

/**
 * Итого.
 * @member {Number} totalCost
 */
InlineResponse20063.prototype['totalCost'] = undefined;






export default InlineResponse20063;

