/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject108 model module.
 * @module model/InlineObject108
 * @version 0.1.0
 */
class InlineObject108 {
    /**
     * Constructs a new <code>InlineObject108</code>.
     * @alias module:model/InlineObject108
     * @param title {String} 
     */
    constructor(title) { 
        
        InlineObject108.initialize(this, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title) { 
        obj['title'] = title;
    }

    /**
     * Constructs a <code>InlineObject108</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject108} obj Optional instance to populate.
     * @return {module:model/InlineObject108} The populated <code>InlineObject108</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject108();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('iconImage')) {
                obj['iconImage'] = ApiClient.convertToType(data['iconImage'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
InlineObject108.prototype['title'] = undefined;

/**
 * @member {String} iconImage
 */
InlineObject108.prototype['iconImage'] = undefined;






export default InlineObject108;

