/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject66 model module.
 * @module model/InlineObject66
 * @version 0.1.0
 */
class InlineObject66 {
    /**
     * Constructs a new <code>InlineObject66</code>.
     * @alias module:model/InlineObject66
     * @param productName {String} Назавние продукта
     * @param price {Number} Желаемая цена
     */
    constructor(productName, price) { 
        
        InlineObject66.initialize(this, productName, price);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productName, price) { 
        obj['productName'] = productName;
        obj['price'] = price;
    }

    /**
     * Constructs a <code>InlineObject66</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject66} obj Optional instance to populate.
     * @return {module:model/InlineObject66} The populated <code>InlineObject66</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject66();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('media')) {
                obj['media'] = ApiClient.convertToType(data['media'], [NULL_SCHEMA_ERR]);
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('buyerComment')) {
                obj['buyerComment'] = ApiClient.convertToType(data['buyerComment'], 'String');
            }
            if (data.hasOwnProperty('productName')) {
                obj['productName'] = ApiClient.convertToType(data['productName'], 'String');
            }
            if (data.hasOwnProperty('productLinks')) {
                obj['productLinks'] = ApiClient.convertToType(data['productLinks'], [NULL_SCHEMA_ERR]);
            }
            if (data.hasOwnProperty('criteria')) {
                obj['criteria'] = ApiClient.convertToType(data['criteria'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('fbaFee')) {
                obj['fbaFee'] = ApiClient.convertToType(data['fbaFee'], 'Number');
            }
            if (data.hasOwnProperty('approximatePrice')) {
                obj['approximatePrice'] = ApiClient.convertToType(data['approximatePrice'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('length')) {
                obj['length'] = ApiClient.convertToType(data['length'], 'Number');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
            }
            if (data.hasOwnProperty('parentProductId')) {
                obj['parentProductId'] = ApiClient.convertToType(data['parentProductId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Название идеи
 * @member {String} title
 */
InlineObject66.prototype['title'] = undefined;

/**
 * Image URL
 * @member {Array.<String>} media
 */
InlineObject66.prototype['media'] = undefined;

/**
 * Комментарий к идее
 * @member {String} comments
 */
InlineObject66.prototype['comments'] = undefined;

/**
 * Комментарий байера
 * @member {String} buyerComment
 */
InlineObject66.prototype['buyerComment'] = undefined;

/**
 * Назавние продукта
 * @member {String} productName
 */
InlineObject66.prototype['productName'] = undefined;

/**
 * Ссылки на продукт, если есть
 * @member {Array.<String>} productLinks
 */
InlineObject66.prototype['productLinks'] = undefined;

/**
 * Дополнительные критерии для поиска товара
 * @member {String} criteria
 */
InlineObject66.prototype['criteria'] = undefined;

/**
 * Количество товаров
 * @member {Number} quantity
 */
InlineObject66.prototype['quantity'] = undefined;

/**
 * Желаемая цена
 * @member {Number} price
 */
InlineObject66.prototype['price'] = undefined;

/**
 * FBA Fee
 * @member {Number} fbaFee
 */
InlineObject66.prototype['fbaFee'] = undefined;

/**
 * Ориентационная цена
 * @member {Number} approximatePrice
 */
InlineObject66.prototype['approximatePrice'] = undefined;

/**
 * Ширина, см
 * @member {Number} width
 */
InlineObject66.prototype['width'] = undefined;

/**
 * Высота, см
 * @member {Number} height
 */
InlineObject66.prototype['height'] = undefined;

/**
 * Длина, см
 * @member {Number} length
 */
InlineObject66.prototype['length'] = undefined;

/**
 * Product ID
 * @member {String} productId
 */
InlineObject66.prototype['productId'] = undefined;

/**
 * Гуид родительского продукта
 * @member {String} parentProductId
 */
InlineObject66.prototype['parentProductId'] = undefined;






export default InlineObject66;

