/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse20013 from './InlineResponse20013';
import InlineResponse20018Group from './InlineResponse20018Group';

/**
 * The InlineResponse20018Rows model module.
 * @module model/InlineResponse20018Rows
 * @version 0.1.0
 */
class InlineResponse20018Rows {
    /**
     * Constructs a new <code>InlineResponse20018Rows</code>.
     * @alias module:model/InlineResponse20018Rows
     */
    constructor() { 
        
        InlineResponse20018Rows.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20018Rows</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20018Rows} obj Optional instance to populate.
     * @return {module:model/InlineResponse20018Rows} The populated <code>InlineResponse20018Rows</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20018Rows();

            if (data.hasOwnProperty('group')) {
                obj['group'] = InlineResponse20018Group.constructFromObject(data['group']);
            }
            if (data.hasOwnProperty('boxes')) {
                obj['boxes'] = ApiClient.convertToType(data['boxes'], [InlineResponse20013]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse20018Group} group
 */
InlineResponse20018Rows.prototype['group'] = undefined;

/**
 * @member {Array.<module:model/InlineResponse20013>} boxes
 */
InlineResponse20018Rows.prototype['boxes'] = undefined;






export default InlineResponse20018Rows;

