/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject98 model module.
 * @module model/InlineObject98
 * @version 0.1.0
 */
class InlineObject98 {
    /**
     * Constructs a new <code>InlineObject98</code>.
     * @alias module:model/InlineObject98
     * @param requestIds {Array.<String>} 
     * @param uploadedToListing {Boolean} 
     */
    constructor(requestIds, uploadedToListing) { 
        
        InlineObject98.initialize(this, requestIds, uploadedToListing);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requestIds, uploadedToListing) { 
        obj['requestIds'] = requestIds;
        obj['uploadedToListing'] = uploadedToListing;
    }

    /**
     * Constructs a <code>InlineObject98</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject98} obj Optional instance to populate.
     * @return {module:model/InlineObject98} The populated <code>InlineObject98</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject98();

            if (data.hasOwnProperty('requestIds')) {
                obj['requestIds'] = ApiClient.convertToType(data['requestIds'], ['String']);
            }
            if (data.hasOwnProperty('uploadedToListing')) {
                obj['uploadedToListing'] = ApiClient.convertToType(data['uploadedToListing'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} requestIds
 */
InlineObject98.prototype['requestIds'] = undefined;

/**
 * @member {Boolean} uploadedToListing
 */
InlineObject98.prototype['uploadedToListing'] = undefined;






export default InlineObject98;

