/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject23 model module.
 * @module model/InlineObject23
 * @version 0.1.0
 */
class InlineObject23 {
    /**
     * Constructs a new <code>InlineObject23</code>.
     * @alias module:model/InlineObject23
     */
    constructor() { 
        
        InlineObject23.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject23</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject23} obj Optional instance to populate.
     * @return {module:model/InlineObject23} The populated <code>InlineObject23</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject23();

            if (data.hasOwnProperty('lengthCmWarehouse')) {
                obj['lengthCmWarehouse'] = ApiClient.convertToType(data['lengthCmWarehouse'], 'Number');
            }
            if (data.hasOwnProperty('widthCmWarehouse')) {
                obj['widthCmWarehouse'] = ApiClient.convertToType(data['widthCmWarehouse'], 'Number');
            }
            if (data.hasOwnProperty('heightCmWarehouse')) {
                obj['heightCmWarehouse'] = ApiClient.convertToType(data['heightCmWarehouse'], 'Number');
            }
            if (data.hasOwnProperty('weighGrossKgWarehouse')) {
                obj['weighGrossKgWarehouse'] = ApiClient.convertToType(data['weighGrossKgWarehouse'], 'Number');
            }
            if (data.hasOwnProperty('volumeWeightKgWarehouse')) {
                obj['volumeWeightKgWarehouse'] = ApiClient.convertToType(data['volumeWeightKgWarehouse'], 'Number');
            }
            if (data.hasOwnProperty('isShippingLabelAttachedByStorekeeper')) {
                obj['isShippingLabelAttachedByStorekeeper'] = ApiClient.convertToType(data['isShippingLabelAttachedByStorekeeper'], 'Boolean');
            }
            if (data.hasOwnProperty('storekeeperComment')) {
                obj['storekeeperComment'] = ApiClient.convertToType(data['storekeeperComment'], 'String');
            }
            if (data.hasOwnProperty('variationTariffId')) {
                obj['variationTariffId'] = ApiClient.convertToType(data['variationTariffId'], 'String');
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} lengthCmWarehouse
 */
InlineObject23.prototype['lengthCmWarehouse'] = undefined;

/**
 * @member {Number} widthCmWarehouse
 */
InlineObject23.prototype['widthCmWarehouse'] = undefined;

/**
 * @member {Number} heightCmWarehouse
 */
InlineObject23.prototype['heightCmWarehouse'] = undefined;

/**
 * @member {Number} weighGrossKgWarehouse
 */
InlineObject23.prototype['weighGrossKgWarehouse'] = undefined;

/**
 * @member {Number} volumeWeightKgWarehouse
 */
InlineObject23.prototype['volumeWeightKgWarehouse'] = undefined;

/**
 * Поле будет указывать на то что при решении задачи сторкипером на обновление коробок что он проклеил шиппинг лейбл.
 * @member {Boolean} isShippingLabelAttachedByStorekeeper
 */
InlineObject23.prototype['isShippingLabelAttachedByStorekeeper'] = undefined;

/**
 * Комментарии к коробке
 * @member {String} storekeeperComment
 */
InlineObject23.prototype['storekeeperComment'] = undefined;

/**
 * Гуид вариации
 * @member {String} variationTariffId
 */
InlineObject23.prototype['variationTariffId'] = undefined;

/**
 * Массив ссылок на фотографии.
 * @member {Array.<String>} images
 */
InlineObject23.prototype['images'] = undefined;






export default InlineObject23;

