/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject112 model module.
 * @module model/InlineObject112
 * @version 0.1.0
 */
class InlineObject112 {
    /**
     * Constructs a new <code>InlineObject112</code>.
     * @alias module:model/InlineObject112
     * @param email {String} Почта от аккаунта, пароль которого Вы забыли
     */
    constructor(email) { 
        
        InlineObject112.initialize(this, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email) { 
        obj['email'] = email;
    }

    /**
     * Constructs a <code>InlineObject112</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject112} obj Optional instance to populate.
     * @return {module:model/InlineObject112} The populated <code>InlineObject112</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject112();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Почта от аккаунта, пароль которого Вы забыли
 * @member {String} email
 */
InlineObject112.prototype['email'] = undefined;






export default InlineObject112;

