/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject88 model module.
 * @module model/InlineObject88
 * @version 0.1.0
 */
class InlineObject88 {
    /**
     * Constructs a new <code>InlineObject88</code>.
     * @alias module:model/InlineObject88
     */
    constructor() { 
        
        InlineObject88.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject88</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject88} obj Optional instance to populate.
     * @return {module:model/InlineObject88} The populated <code>InlineObject88</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject88();

            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('lamazon')) {
                obj['lamazon'] = ApiClient.convertToType(data['lamazon'], 'String');
            }
            if (data.hasOwnProperty('bsr')) {
                obj['bsr'] = ApiClient.convertToType(data['bsr'], 'Number');
            }
            if (data.hasOwnProperty('fba')) {
                obj['fba'] = ApiClient.convertToType(data['fba'], 'Boolean');
            }
            if (data.hasOwnProperty('amazon')) {
                obj['amazon'] = ApiClient.convertToType(data['amazon'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('length')) {
                obj['length'] = ApiClient.convertToType(data['length'], 'Number');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
            if (data.hasOwnProperty('reffee')) {
                obj['reffee'] = ApiClient.convertToType(data['reffee'], 'Number');
            }
            if (data.hasOwnProperty('fbafee')) {
                obj['fbafee'] = ApiClient.convertToType(data['fbafee'], 'Number');
            }
            if (data.hasOwnProperty('fbaamount')) {
                obj['fbaamount'] = ApiClient.convertToType(data['fbaamount'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('icomment')) {
                obj['icomment'] = ApiClient.convertToType(data['icomment'], 'String');
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], ['String']);
            }
            if (data.hasOwnProperty('amazonDescription')) {
                obj['amazonDescription'] = ApiClient.convertToType(data['amazonDescription'], 'String');
            }
            if (data.hasOwnProperty('amazonDetail')) {
                obj['amazonDetail'] = ApiClient.convertToType(data['amazonDetail'], 'String');
            }
            if (data.hasOwnProperty('amazonTitle')) {
                obj['amazonTitle'] = ApiClient.convertToType(data['amazonTitle'], 'String');
            }
            if (data.hasOwnProperty('material')) {
                obj['material'] = ApiClient.convertToType(data['material'], 'String');
            }
            if (data.hasOwnProperty('productUsage')) {
                obj['productUsage'] = ApiClient.convertToType(data['productUsage'], 'String');
            }
            if (data.hasOwnProperty('chinaTitle')) {
                obj['chinaTitle'] = ApiClient.convertToType(data['chinaTitle'], 'String');
            }
            if (data.hasOwnProperty('barCode')) {
                obj['barCode'] = ApiClient.convertToType(data['barCode'], 'String');
            }
            if (data.hasOwnProperty('minpurchase')) {
                obj['minpurchase'] = ApiClient.convertToType(data['minpurchase'], 'Number');
            }
            if (data.hasOwnProperty('profit')) {
                obj['profit'] = ApiClient.convertToType(data['profit'], 'Number');
            }
            if (data.hasOwnProperty('margin')) {
                obj['margin'] = ApiClient.convertToType(data['margin'], 'Number');
            }
            if (data.hasOwnProperty('listingName')) {
                obj['listingName'] = ApiClient.convertToType(data['listingName'], 'String');
            }
            if (data.hasOwnProperty('listingBulletPoints')) {
                obj['listingBulletPoints'] = ApiClient.convertToType(data['listingBulletPoints'], ['String']);
            }
            if (data.hasOwnProperty('listingProductDetails')) {
                obj['listingProductDetails'] = ApiClient.convertToType(data['listingProductDetails'], 'String');
            }
            if (data.hasOwnProperty('listingSearchTerms')) {
                obj['listingSearchTerms'] = ApiClient.convertToType(data['listingSearchTerms'], 'String');
            }
            if (data.hasOwnProperty('listingSubjectMatters')) {
                obj['listingSubjectMatters'] = ApiClient.convertToType(data['listingSubjectMatters'], ['String']);
            }
            if (data.hasOwnProperty('listingImages')) {
                obj['listingImages'] = ApiClient.convertToType(data['listingImages'], ['String']);
            }
            if (data.hasOwnProperty('strategyStatus')) {
                obj['strategyStatus'] = ApiClient.convertToType(data['strategyStatus'], 'Number');
            }
            if (data.hasOwnProperty('niche')) {
                obj['niche'] = ApiClient.convertToType(data['niche'], 'String');
            }
            if (data.hasOwnProperty('asins')) {
                obj['asins'] = ApiClient.convertToType(data['asins'], 'String');
            }
            if (data.hasOwnProperty('totalRevenue')) {
                obj['totalRevenue'] = ApiClient.convertToType(data['totalRevenue'], 'String');
            }
            if (data.hasOwnProperty('coefficient')) {
                obj['coefficient'] = ApiClient.convertToType(data['coefficient'], 'String');
            }
            if (data.hasOwnProperty('avgRevenue')) {
                obj['avgRevenue'] = ApiClient.convertToType(data['avgRevenue'], 'String');
            }
            if (data.hasOwnProperty('avgBSR')) {
                obj['avgBSR'] = ApiClient.convertToType(data['avgBSR'], 'String');
            }
            if (data.hasOwnProperty('avgPrice')) {
                obj['avgPrice'] = ApiClient.convertToType(data['avgPrice'], 'String');
            }
            if (data.hasOwnProperty('avgReviews')) {
                obj['avgReviews'] = ApiClient.convertToType(data['avgReviews'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Категория
 * @member {String} category
 */
InlineObject88.prototype['category'] = undefined;

/**
 * Ссылка на этот продукт на амазоне.
 * @member {String} lamazon
 */
InlineObject88.prototype['lamazon'] = undefined;

/**
 * 
 * @member {Number} bsr
 */
InlineObject88.prototype['bsr'] = undefined;

/**
 * Признак fba
 * @member {Boolean} fba
 */
InlineObject88.prototype['fba'] = undefined;

/**
 * 
 * @member {Number} amazon
 */
InlineObject88.prototype['amazon'] = undefined;

/**
 * @member {Number} height
 */
InlineObject88.prototype['height'] = undefined;

/**
 * @member {Number} width
 */
InlineObject88.prototype['width'] = undefined;

/**
 * @member {Number} length
 */
InlineObject88.prototype['length'] = undefined;

/**
 * @member {Number} weight
 */
InlineObject88.prototype['weight'] = undefined;

/**
 * комиссия которую берет амазон за любой заказ - 15%
 * @member {Number} reffee
 */
InlineObject88.prototype['reffee'] = undefined;

/**
 * ФБА комиссия
 * @member {Number} fbafee
 */
InlineObject88.prototype['fbafee'] = undefined;

/**
 *  Общая сумма с фба.
 * @member {Number} fbaamount
 */
InlineObject88.prototype['fbaamount'] = undefined;

/**
 *  Статус товара. У ресечера: 0 - новый товар. 5- готов к проверке супером. 10 - новый товар с поставщиком
 * @member {Number} status
 */
InlineObject88.prototype['status'] = undefined;

/**
 * Комментарии к товару.
 * @member {String} icomment
 */
InlineObject88.prototype['icomment'] = undefined;

/**
 * Массив изображений.
 * @member {Array.<String>} images
 */
InlineObject88.prototype['images'] = undefined;

/**
 * @member {String} amazonDescription
 */
InlineObject88.prototype['amazonDescription'] = undefined;

/**
 * @member {String} amazonDetail
 */
InlineObject88.prototype['amazonDetail'] = undefined;

/**
 * @member {String} amazonTitle
 */
InlineObject88.prototype['amazonTitle'] = undefined;

/**
 * Материл продукта
 * @member {String} material
 */
InlineObject88.prototype['material'] = undefined;

/**
 * Применение продукта
 * @member {String} productUsage
 */
InlineObject88.prototype['productUsage'] = undefined;

/**
 * chinese title?
 * @member {String} chinaTitle
 */
InlineObject88.prototype['chinaTitle'] = undefined;

/**
 * @member {String} barCode
 */
InlineObject88.prototype['barCode'] = undefined;

/**
 * @member {Number} minpurchase
 */
InlineObject88.prototype['minpurchase'] = undefined;

/**
 * Прибыль
 * @member {Number} profit
 */
InlineObject88.prototype['profit'] = undefined;

/**
 * Маржа
 * @member {Number} margin
 */
InlineObject88.prototype['margin'] = undefined;

/**
 * 
 * @member {String} listingName
 */
InlineObject88.prototype['listingName'] = undefined;

/**
 * Массив ...
 * @member {Array.<String>} listingBulletPoints
 */
InlineObject88.prototype['listingBulletPoints'] = undefined;

/**
 * 
 * @member {String} listingProductDetails
 */
InlineObject88.prototype['listingProductDetails'] = undefined;

/**
 * 
 * @member {String} listingSearchTerms
 */
InlineObject88.prototype['listingSearchTerms'] = undefined;

/**
 * Массив ...
 * @member {Array.<String>} listingSubjectMatters
 */
InlineObject88.prototype['listingSubjectMatters'] = undefined;

/**
 * массив картинок(в виде прямых ссылок).
 * @member {Array.<String>} listingImages
 */
InlineObject88.prototype['listingImages'] = undefined;

/**
 * У поля на данный момент будет 5 возможных значений: 0, 10, 20, 30, 40
 * @member {Number} strategyStatus
 */
InlineObject88.prototype['strategyStatus'] = undefined;

/**
 * Ниша
 * @member {String} niche
 */
InlineObject88.prototype['niche'] = undefined;

/**
 * Асины
 * @member {String} asins
 */
InlineObject88.prototype['asins'] = undefined;

/**
 * Общий доход
 * @member {String} totalRevenue
 */
InlineObject88.prototype['totalRevenue'] = undefined;

/**
 * Коэффициент прибыли
 * @member {String} coefficient
 */
InlineObject88.prototype['coefficient'] = undefined;

/**
 * Средний доход
 * @member {String} avgRevenue
 */
InlineObject88.prototype['avgRevenue'] = undefined;

/**
 * Средний BSR
 * @member {String} avgBSR
 */
InlineObject88.prototype['avgBSR'] = undefined;

/**
 * Средняя цена
 * @member {String} avgPrice
 */
InlineObject88.prototype['avgPrice'] = undefined;

/**
 * Средний отзывы
 * @member {String} avgReviews
 */
InlineObject88.prototype['avgReviews'] = undefined;






export default InlineObject88;

