/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse20035Batch from './InlineResponse20035Batch';
import InlineResponse20035Boxes from './InlineResponse20035Boxes';
import InlineResponse20035Orders from './InlineResponse20035Orders';
import InlineResponse20035Products from './InlineResponse20035Products';
import InlineResponse20035Requests from './InlineResponse20035Requests';
import InlineResponse20035Shops from './InlineResponse20035Shops';

/**
 * The InlineResponse20035 model module.
 * @module model/InlineResponse20035
 * @version 0.1.0
 */
class InlineResponse20035 {
    /**
     * Constructs a new <code>InlineResponse20035</code>.
     * @alias module:model/InlineResponse20035
     */
    constructor() { 
        
        InlineResponse20035.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20035</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20035} obj Optional instance to populate.
     * @return {module:model/InlineResponse20035} The populated <code>InlineResponse20035</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20035();

            if (data.hasOwnProperty('orders')) {
                obj['orders'] = InlineResponse20035Orders.constructFromObject(data['orders']);
            }
            if (data.hasOwnProperty('shops')) {
                obj['shops'] = InlineResponse20035Shops.constructFromObject(data['shops']);
            }
            if (data.hasOwnProperty('requests')) {
                obj['requests'] = InlineResponse20035Requests.constructFromObject(data['requests']);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = InlineResponse20035Products.constructFromObject(data['products']);
            }
            if (data.hasOwnProperty('batch')) {
                obj['batch'] = InlineResponse20035Batch.constructFromObject(data['batch']);
            }
            if (data.hasOwnProperty('boxes')) {
                obj['boxes'] = InlineResponse20035Boxes.constructFromObject(data['boxes']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse20035Orders} orders
 */
InlineResponse20035.prototype['orders'] = undefined;

/**
 * @member {module:model/InlineResponse20035Shops} shops
 */
InlineResponse20035.prototype['shops'] = undefined;

/**
 * @member {module:model/InlineResponse20035Requests} requests
 */
InlineResponse20035.prototype['requests'] = undefined;

/**
 * @member {module:model/InlineResponse20035Products} products
 */
InlineResponse20035.prototype['products'] = undefined;

/**
 * @member {module:model/InlineResponse20035Batch} batch
 */
InlineResponse20035.prototype['batch'] = undefined;

/**
 * @member {module:model/InlineResponse20035Boxes} boxes
 */
InlineResponse20035.prototype['boxes'] = undefined;






export default InlineResponse20035;

