/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiV1RequestsCustomDetails from './ApiV1RequestsCustomDetails';
import ApiV1RequestsCustomRequest from './ApiV1RequestsCustomRequest';

/**
 * The InlineObject50 model module.
 * @module model/InlineObject50
 * @version 0.1.0
 */
class InlineObject50 {
    /**
     * Constructs a new <code>InlineObject50</code>.
     * Схема кастомной заявки.
     * @alias module:model/InlineObject50
     */
    constructor() { 
        
        InlineObject50.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject50</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject50} obj Optional instance to populate.
     * @return {module:model/InlineObject50} The populated <code>InlineObject50</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject50();

            if (data.hasOwnProperty('request')) {
                obj['request'] = ApiV1RequestsCustomRequest.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiV1RequestsCustomDetails.constructFromObject(data['details']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ApiV1RequestsCustomRequest} request
 */
InlineObject50.prototype['request'] = undefined;

/**
 * @member {module:model/ApiV1RequestsCustomDetails} details
 */
InlineObject50.prototype['details'] = undefined;






export default InlineObject50;

