/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse20036Batch from './InlineResponse20036Batch';
import InlineResponse20036Boxes from './InlineResponse20036Boxes';
import InlineResponse20036Orders from './InlineResponse20036Orders';
import InlineResponse20036Products from './InlineResponse20036Products';
import InlineResponse20036Requests from './InlineResponse20036Requests';
import InlineResponse20036Shops from './InlineResponse20036Shops';

/**
 * The InlineResponse20036 model module.
 * @module model/InlineResponse20036
 * @version 0.1.0
 */
class InlineResponse20036 {
    /**
     * Constructs a new <code>InlineResponse20036</code>.
     * @alias module:model/InlineResponse20036
     */
    constructor() { 
        
        InlineResponse20036.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20036</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20036} obj Optional instance to populate.
     * @return {module:model/InlineResponse20036} The populated <code>InlineResponse20036</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20036();

            if (data.hasOwnProperty('orders')) {
                obj['orders'] = InlineResponse20036Orders.constructFromObject(data['orders']);
            }
            if (data.hasOwnProperty('shops')) {
                obj['shops'] = InlineResponse20036Shops.constructFromObject(data['shops']);
            }
            if (data.hasOwnProperty('requests')) {
                obj['requests'] = InlineResponse20036Requests.constructFromObject(data['requests']);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = InlineResponse20036Products.constructFromObject(data['products']);
            }
            if (data.hasOwnProperty('batch')) {
                obj['batch'] = InlineResponse20036Batch.constructFromObject(data['batch']);
            }
            if (data.hasOwnProperty('boxes')) {
                obj['boxes'] = InlineResponse20036Boxes.constructFromObject(data['boxes']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse20036Orders} orders
 */
InlineResponse20036.prototype['orders'] = undefined;

/**
 * @member {module:model/InlineResponse20036Shops} shops
 */
InlineResponse20036.prototype['shops'] = undefined;

/**
 * @member {module:model/InlineResponse20036Requests} requests
 */
InlineResponse20036.prototype['requests'] = undefined;

/**
 * @member {module:model/InlineResponse20036Products} products
 */
InlineResponse20036.prototype['products'] = undefined;

/**
 * @member {module:model/InlineResponse20036Batch} batch
 */
InlineResponse20036.prototype['batch'] = undefined;

/**
 * @member {module:model/InlineResponse20036Boxes} boxes
 */
InlineResponse20036.prototype['boxes'] = undefined;






export default InlineResponse20036;

