/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject50 model module.
 * @module model/InlineObject50
 * @version 0.1.0
 */
class InlineObject50 {
    /**
     * Constructs a new <code>InlineObject50</code>.
     * @alias module:model/InlineObject50
     */
    constructor() { 
        
        InlineObject50.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject50</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject50} obj Optional instance to populate.
     * @return {module:model/InlineObject50} The populated <code>InlineObject50</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject50();

            if (data.hasOwnProperty('productName')) {
                obj['productName'] = ApiClient.convertToType(data['productName'], 'String');
            }
            if (data.hasOwnProperty('productLinks')) {
                obj['productLinks'] = ApiClient.convertToType(data['productLinks'], [NULL_SCHEMA_ERR]);
            }
            if (data.hasOwnProperty('linksToMediaFiles')) {
                obj['linksToMediaFiles'] = ApiClient.convertToType(data['linksToMediaFiles'], [NULL_SCHEMA_ERR]);
            }
            if (data.hasOwnProperty('criteria')) {
                obj['criteria'] = ApiClient.convertToType(data['criteria'], 'String');
            }
            if (data.hasOwnProperty('dimensions')) {
                obj['dimensions'] = ApiClient.convertToType(data['dimensions'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Назавние продукта
 * @member {String} productName
 */
InlineObject50.prototype['productName'] = undefined;

/**
 * Ссылки на продукт, если есть
 * @member {Array.<String>} productLinks
 */
InlineObject50.prototype['productLinks'] = undefined;

/**
 * Image URL
 * @member {Array.<String>} linksToMediaFiles
 */
InlineObject50.prototype['linksToMediaFiles'] = undefined;

/**
 * Дополнительные критерии для поиска товара
 * @member {String} criteria
 */
InlineObject50.prototype['criteria'] = undefined;

/**
 * Размеры
 * @member {String} dimensions
 */
InlineObject50.prototype['dimensions'] = undefined;

/**
 * Количество товаров
 * @member {Number} quantity
 */
InlineObject50.prototype['quantity'] = undefined;

/**
 * Желаемая цена
 * @member {Number} price
 */
InlineObject50.prototype['price'] = undefined;

/**
 * Product ID
 * @member {String} productId
 */
InlineObject50.prototype['productId'] = undefined;






export default InlineObject50;

