/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject47 model module.
 * @module model/InlineObject47
 * @version 0.1.0
 */
class InlineObject47 {
    /**
     * Constructs a new <code>InlineObject47</code>.
     * @alias module:model/InlineObject47
     */
    constructor() { 
        
        InlineObject47.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject47</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject47} obj Optional instance to populate.
     * @return {module:model/InlineObject47} The populated <code>InlineObject47</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject47();

            if (data.hasOwnProperty('media')) {
                obj['media'] = ApiClient.convertToType(data['media'], [NULL_SCHEMA_ERR]);
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('productName')) {
                obj['productName'] = ApiClient.convertToType(data['productName'], 'String');
            }
            if (data.hasOwnProperty('productLinks')) {
                obj['productLinks'] = ApiClient.convertToType(data['productLinks'], [NULL_SCHEMA_ERR]);
            }
            if (data.hasOwnProperty('criteria')) {
                obj['criteria'] = ApiClient.convertToType(data['criteria'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('length')) {
                obj['length'] = ApiClient.convertToType(data['length'], 'Number');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Image URL
 * @member {Array.<String>} media
 */
InlineObject47.prototype['media'] = undefined;

/**
 * Комментарий к идее
 * @member {String} comments
 */
InlineObject47.prototype['comments'] = undefined;

/**
 * Назавние продукта
 * @member {String} productName
 */
InlineObject47.prototype['productName'] = undefined;

/**
 * Ссылки на продукт, если есть
 * @member {Array.<String>} productLinks
 */
InlineObject47.prototype['productLinks'] = undefined;

/**
 * Дополнительные критерии для поиска товара
 * @member {String} criteria
 */
InlineObject47.prototype['criteria'] = undefined;

/**
 * Количество товаров
 * @member {Number} quantity
 */
InlineObject47.prototype['quantity'] = undefined;

/**
 * Желаемая цена
 * @member {Number} price
 */
InlineObject47.prototype['price'] = undefined;

/**
 * Ширина, см
 * @member {Number} width
 */
InlineObject47.prototype['width'] = undefined;

/**
 * Высота, см
 * @member {Number} height
 */
InlineObject47.prototype['height'] = undefined;

/**
 * Длина, см
 * @member {Number} length
 */
InlineObject47.prototype['length'] = undefined;

/**
 * Product ID
 * @member {String} productId
 */
InlineObject47.prototype['productId'] = undefined;






export default InlineObject47;

