/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse20061 model module.
 * @module model/InlineResponse20061
 * @version 0.1.0
 */
class InlineResponse20061 {
    /**
     * Constructs a new <code>InlineResponse20061</code>.
     * @alias module:model/InlineResponse20061
     */
    constructor() { 
        
        InlineResponse20061.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20061</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20061} obj Optional instance to populate.
     * @return {module:model/InlineResponse20061} The populated <code>InlineResponse20061</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20061();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('humanFriendlyId')) {
                obj['humanFriendlyId'] = ApiClient.convertToType(data['humanFriendlyId'], 'Number');
            }
            if (data.hasOwnProperty('typeTask')) {
                obj['typeTask'] = ApiClient.convertToType(data['typeTask'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * GUID заявки
 * @member {String} _id
 */
InlineResponse20061.prototype['_id'] = undefined;

/**
 * Номер заявки
 * @member {Number} humanFriendlyId
 */
InlineResponse20061.prototype['humanFriendlyId'] = undefined;

/**
 * Тип задачи заявки
 * @member {Number} typeTask
 */
InlineResponse20061.prototype['typeTask'] = undefined;

/**
 * Название заявки
 * @member {String} title
 */
InlineResponse20061.prototype['title'] = undefined;

/**
 * Статус заявки
 * @member {String} status
 */
InlineResponse20061.prototype['status'] = undefined;






export default InlineResponse20061;

