/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse20018Rows from './InlineResponse20018Rows';

/**
 * The InlineResponse20018 model module.
 * @module model/InlineResponse20018
 * @version 0.1.0
 */
class InlineResponse20018 {
    /**
     * Constructs a new <code>InlineResponse20018</code>.
     * @alias module:model/InlineResponse20018
     */
    constructor() { 
        
        InlineResponse20018.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20018</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20018} obj Optional instance to populate.
     * @return {module:model/InlineResponse20018} The populated <code>InlineResponse20018</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20018();

            if (data.hasOwnProperty('rows')) {
                obj['rows'] = ApiClient.convertToType(data['rows'], [InlineResponse20018Rows]);
            }
<<<<<<< HEAD
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
=======
            if (data.hasOwnProperty('asin')) {
                obj['asin'] = ApiClient.convertToType(data['asin'], 'String');
            }
            if (data.hasOwnProperty('skusByClient')) {
                obj['skusByClient'] = ApiClient.convertToType(data['skusByClient'], ['String']);
            }
            if (data.hasOwnProperty('strategyStatus')) {
                obj['strategyStatus'] = ApiClient.convertToType(data['strategyStatus'], 'Number');
            }
            if (data.hasOwnProperty('checkednotes')) {
                obj['checkednotes'] = ApiClient.convertToType(data['checkednotes'], 'String');
            }
            if (data.hasOwnProperty('bsr')) {
                obj['bsr'] = ApiClient.convertToType(data['bsr'], 'Number');
            }
            if (data.hasOwnProperty('amazon')) {
                obj['amazon'] = ApiClient.convertToType(data['amazon'], 'Number');
            }
            if (data.hasOwnProperty('reffee')) {
                obj['reffee'] = ApiClient.convertToType(data['reffee'], 'Number');
            }
            if (data.hasOwnProperty('fbafee')) {
                obj['fbafee'] = ApiClient.convertToType(data['fbafee'], 'Number');
            }
            if (data.hasOwnProperty('fbaamount')) {
                obj['fbaamount'] = ApiClient.convertToType(data['fbaamount'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], ['String']);
            }
            if (data.hasOwnProperty('amazonTitle')) {
                obj['amazonTitle'] = ApiClient.convertToType(data['amazonTitle'], 'String');
            }
            if (data.hasOwnProperty('profit')) {
                obj['profit'] = ApiClient.convertToType(data['profit'], 'Number');
            }
            if (data.hasOwnProperty('material')) {
                obj['material'] = ApiClient.convertToType(data['material'], 'String');
            }
            if (data.hasOwnProperty('productUsage')) {
                obj['productUsage'] = ApiClient.convertToType(data['productUsage'], 'String');
            }
            if (data.hasOwnProperty('chinaTitle')) {
                obj['chinaTitle'] = ApiClient.convertToType(data['chinaTitle'], 'String');
            }
            if (data.hasOwnProperty('ideasCounter')) {
                obj['ideasCounter'] = ApiClient.convertToType(data['ideasCounter'], 'Number');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
>>>>>>> e781ddfbc (save)
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/InlineResponse20018Rows>} rows
 */
InlineResponse20018.prototype['rows'] = undefined;

/**
 * @member {Number} count
 */
<<<<<<< HEAD
InlineResponse20018.prototype['count'] = undefined;
=======
InlineResponse20018.prototype['asin'] = undefined;

/**
 * @member {Array.<String>} skusByClient
 */
InlineResponse20018.prototype['skusByClient'] = undefined;

/**
 * У поля на данный момент будет 5 возможных значений: 0, 10, 20, 30, 40
 * @member {Number} strategyStatus
 */
InlineResponse20018.prototype['strategyStatus'] = undefined;

/**
 * 
 * @member {String} checkednotes
 */
InlineResponse20018.prototype['checkednotes'] = undefined;

/**
 * 
 * @member {Number} bsr
 */
InlineResponse20018.prototype['bsr'] = undefined;

/**
 * 
 * @member {Number} amazon
 */
InlineResponse20018.prototype['amazon'] = undefined;

/**
 * комиссия которую берет амазон за любой заказ - 15%
 * @member {Number} reffee
 */
InlineResponse20018.prototype['reffee'] = undefined;

/**
 * ФБА комиссия
 * @member {Number} fbafee
 */
InlineResponse20018.prototype['fbafee'] = undefined;

/**
 *  Общая сумма с фба.
 * @member {Number} fbaamount
 */
InlineResponse20018.prototype['fbaamount'] = undefined;

/**
 * Код текущего статуса
 * @member {Number} status
 */
InlineResponse20018.prototype['status'] = undefined;

/**
 * Массив картинок.
 * @member {Array.<String>} images
 */
InlineResponse20018.prototype['images'] = undefined;

/**
 * Заголовок на товар с сайта амазон.
 * @member {String} amazonTitle
 */
InlineResponse20018.prototype['amazonTitle'] = undefined;

/**
 * Прибыль
 * @member {Number} profit
 */
InlineResponse20018.prototype['profit'] = undefined;

/**
 * Материл продукта
 * @member {String} material
 */
InlineResponse20018.prototype['material'] = undefined;

/**
 * Применение продукта
 * @member {String} productUsage
 */
InlineResponse20018.prototype['productUsage'] = undefined;

/**
 * chinese title?
 * @member {String} chinaTitle
 */
InlineResponse20018.prototype['chinaTitle'] = undefined;

/**
 * Кол-во идей продукта в статусе 10
 * @member {Number} ideasCounter
 */
InlineResponse20018.prototype['ideasCounter'] = undefined;

/**
 * Дата создания
 * @member {Date} createdAt
 */
InlineResponse20018.prototype['createdAt'] = undefined;

/**
 * Дата изменения
 * @member {Date} updatedAt
 */
InlineResponse20018.prototype['updatedAt'] = undefined;
>>>>>>> e781ddfbc (save)






export default InlineResponse20018;

