/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2007 model module.
 * @module model/InlineResponse2007
 * @version 0.1.0
 */
class InlineResponse2007 {
    /**
     * Constructs a new <code>InlineResponse2007</code>.
     * @alias module:model/InlineResponse2007
     */
    constructor() { 
        
        InlineResponse2007.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2007</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2007} obj Optional instance to populate.
     * @return {module:model/InlineResponse2007} The populated <code>InlineResponse2007</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2007();

            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('deliveryCost')) {
                obj['deliveryCost'] = ApiClient.convertToType(data['deliveryCost'], 'Number');
            }
            if (data.hasOwnProperty('volumeWeightKgWarehouse')) {
                obj['volumeWeightKgWarehouse'] = ApiClient.convertToType(data['volumeWeightKgWarehouse'], 'Number');
            }
            if (data.hasOwnProperty('weightFinalAccountingKgWarehouse')) {
                obj['weightFinalAccountingKgWarehouse'] = ApiClient.convertToType(data['weightFinalAccountingKgWarehouse'], 'Number');
            }
            if (data.hasOwnProperty('deliveryRate')) {
                obj['deliveryRate'] = ApiClient.convertToType(data['deliveryRate'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The unique identifier of the box.
 * @member {String} guid
 */
InlineResponse2007.prototype['guid'] = undefined;

/**
 * The delivery cost of the box.
 * @member {Number} deliveryCost
 */
InlineResponse2007.prototype['deliveryCost'] = undefined;

/**
 * The volume weight of the box in kg.
 * @member {Number} volumeWeightKgWarehouse
 */
InlineResponse2007.prototype['volumeWeightKgWarehouse'] = undefined;

/**
 * The weight of the box in kg.
 * @member {Number} weightFinalAccountingKgWarehouse
 */
InlineResponse2007.prototype['weightFinalAccountingKgWarehouse'] = undefined;

/**
 * The delivery rate of the box. $/kg
 * @member {Number} deliveryRate
 */
InlineResponse2007.prototype['deliveryRate'] = undefined;






export default InlineResponse2007;

