/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject86 model module.
 * @module model/InlineObject86
 * @version 0.1.0
 */
class InlineObject86 {
    /**
     * Constructs a new <code>InlineObject86</code>.
     * @alias module:model/InlineObject86
     * @param action {module:model/InlineObject86.ActionEnum} 
     */
    constructor(action) { 
        
        InlineObject86.initialize(this, action);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action) { 
        obj['action'] = action;
    }

    /**
     * Constructs a <code>InlineObject86</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject86} obj Optional instance to populate.
     * @return {module:model/InlineObject86} The populated <code>InlineObject86</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject86();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineObject86.ActionEnum} action
 */
InlineObject86.prototype['action'] = undefined;

/**
 * Причина смены статуса.
 * @member {String} reason
 */
InlineObject86.prototype['reason'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject86['ActionEnum'] = {

    /**
     * value: "LINK"
     * @const
     */
    "LINK": "LINK",

    /**
     * value: "UNLINK"
     * @const
     */
    "UNLINK": "UNLINK"
};



export default InlineObject86;

