/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse20064Rows from './InlineResponse20064Rows';

/**
 * The InlineResponse20064 model module.
 * @module model/InlineResponse20064
 * @version 0.1.0
 */
class InlineResponse20064 {
    /**
     * Constructs a new <code>InlineResponse20064</code>.
     * @alias module:model/InlineResponse20064
     */
    constructor() { 
        
        InlineResponse20064.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20064</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20064} obj Optional instance to populate.
     * @return {module:model/InlineResponse20064} The populated <code>InlineResponse20064</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20064();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('rows')) {
                obj['rows'] = ApiClient.convertToType(data['rows'], [InlineResponse20064Rows]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} count
 */
InlineResponse20064.prototype['count'] = undefined;

/**
 * Массив заявок.
 * @member {Array.<module:model/InlineResponse20064Rows>} rows
 */
InlineResponse20064.prototype['rows'] = undefined;






export default InlineResponse20064;

