version: '3.5'

volumes:
  nginx-logs:
  nginx-certificates:

services:
  # certbot:
  #   image: docker.hrsinternational.com/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   volumes:
  #     - /etc/certbot/conf:/etc/letsencrypt
  #     - /etc/certbot/www:/var/www/certbot

  reverse-proxy:
    image: docker.hrsinternational.com/nginx
    restart: always
    container_name: reverse-proxy
    volumes:
      - nginx-logs:/var/log/nginx/
      - nginx-certificates:/etc/nginx/ssl
      - ./nginx/default.staging.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      # - /etc/certbot/conf:/etc/letsencrypt
      # - /etc/certbot/www:/var/www/certbot
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ['CMD-SHELL', 'service nginx status || exit 1']
    ports:
      - '80:80'
      # - '443:443'

  frontend:
    image: ${CI_REGISTRY}/frontend:${CI_COMMIT_REF_SLUG}
    container_name: frontend
    restart: unless-stopped
    env_file: ../.env