export enum ProductTubs {
  MAIN_INFO = 'MAIN_INFO',
  ORDERS = 'ORDERS',
  REPORTS = 'REPORTS',
  INTEGRATIONS = 'INTEGRATIONS',
  LISTING = 'LISTING',
  SUPPLIERS_AND_IDEAS = 'SUPPLIERS_AND_IDEAS',
  FREELANCE = 'FREELANCE',
  MANAGEMENT = 'MANAGEMENT',
}
