/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1BoxesManyV2Items
 */
export interface ApiV1BoxesManyV2Items {
    /**
     * Штрихкод продукта
     * @type {string}
     * @memberof ApiV1BoxesManyV2Items
     */
    barCode?: string;
    /**
     * Защита листинга
     * @type {string}
     * @memberof ApiV1BoxesManyV2Items
     */
    transparencyFile?: string;
    /**
     * Защита листинга прикреплена кладовщиком
     * @type {boolean}
     * @memberof ApiV1BoxesManyV2Items
     */
    isTransparencyFileAttachedByTheStorekeeper?: boolean;
    /**
     * Защита листинга уже прикреплена поставщиком
     * @type {boolean}
     * @memberof ApiV1BoxesManyV2Items
     */
    isTransparencyFileAlreadyAttachedByTheSupplier?: boolean;
    /**
     * Штрихкод уже прикреплен поставщиком
     * @type {boolean}
     * @memberof ApiV1BoxesManyV2Items
     */
    isBarCodeAlreadyAttachedByTheSupplier?: boolean;
    /**
     * Штрихкод прикреплен кладовщиком
     * @type {boolean}
     * @memberof ApiV1BoxesManyV2Items
     */
    isBarCodeAttachedByTheStorekeeper?: boolean;
    /**
     * Product guid
     * @type {string}
     * @memberof ApiV1BoxesManyV2Items
     */
    productId?: string;
    /**
     * Order guid
     * @type {string}
     * @memberof ApiV1BoxesManyV2Items
     */
    orderId?: string;
}


