/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1BoxesClientsLightProductRedFlags
 */
export interface ApiV1BoxesClientsLightProductRedFlags {
    /**
     * Гуид красного флага
     * @type {string}
     * @memberof ApiV1BoxesClientsLightProductRedFlags
     */
    _id?: string;
    /**
     * Значение красного флага
     * @type {number}
     * @memberof ApiV1BoxesClientsLightProductRedFlags
     */
    value?: number;
    /**
     * Название красного флага
     * @type {string}
     * @memberof ApiV1BoxesClientsLightProductRedFlags
     */
    title?: string;
    /**
     * Ссылка на иконку
     * @type {string}
     * @memberof ApiV1BoxesClientsLightProductRedFlags
     */
    iconImage?: string;
}


