/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiV1BatchesProductPaymentMethods
 */
export interface ApiV1BatchesProductPaymentMethods {
    /**
     * GUID метода оплаты в базе данных
     * @type {string}
     * @memberof ApiV1BatchesProductPaymentMethods
     */
    _id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1BatchesProductPaymentMethods
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1BatchesProductPaymentMethods
     */
    iconImage?: string;
    /**
     * Дата создания
     * @type {string}
     * @memberof ApiV1BatchesProductPaymentMethods
     */
    createdAt?: string;
    /**
     * Дата обновления
     * @type {string}
     * @memberof ApiV1BatchesProductPaymentMethods
     */
    updatedAt?: string;
}


