/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiV1AnnouncementsMyCreatedBy } from './api-v1-announcements-my-created-by';

/**
 * 
 * @export
 * @interface InlineResponse20052Rows
 */
export interface InlineResponse20052Rows {
    /**
     * Гуид тега
     * @type {string}
     * @memberof InlineResponse20052Rows
     */
    _id?: string;
    /**
     * Тег
     * @type {string}
     * @memberof InlineResponse20052Rows
     */
    title?: string;
    /**
     * Кол-во продуктов, которые используют этот тег
     * @type {number}
     * @memberof InlineResponse20052Rows
     */
    productCount?: number;
    /**
     * 
     * @type {Array<ApiV1AnnouncementsMyCreatedBy>}
     * @memberof InlineResponse20052Rows
     */
    shopUsers?: Array<ApiV1AnnouncementsMyCreatedBy>;
    /**
     * 
     * @type {Array<ApiV1AnnouncementsMyCreatedBy>}
     * @memberof InlineResponse20052Rows
     */
    productUsers?: Array<ApiV1AnnouncementsMyCreatedBy>;
}


