/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject150
 */
export interface InlineObject150 {
    /**
     * Почта от аккаунта, пароль которого Вы забыли
     * @type {string}
     * @memberof InlineObject150
     */
    email: string;
}


