/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse20096Rows } from './inline-response20096-rows';

/**
 * 
 * @export
 * @interface InlineResponse20096
 */
export interface InlineResponse20096 {
    /**
     * Кол-во значений
     * @type {number}
     * @memberof InlineResponse20096
     */
    count?: number;
    /**
     * Массив данных о складах.
     * @type {Array<InlineResponse20096Rows>}
     * @memberof InlineResponse20096
     */
    rows?: Array<InlineResponse20096Rows>;
}


