/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse20037LogicsTariffConditionsByRegion } from './inline-response20037-logics-tariff-conditions-by-region';

/**
 * 
 * @export
 * @interface InlineResponse20037LogicsTariff
 */
export interface InlineResponse20037LogicsTariff {
    /**
     * GUID в базе данных
     * @type {string}
     * @memberof InlineResponse20037LogicsTariff
     */
    _id?: string;
    /**
     * Название тарифа
     * @type {string}
     * @memberof InlineResponse20037LogicsTariff
     */
    name?: string;
    /**
     * 
     * @type {InlineResponse20037LogicsTariffConditionsByRegion}
     * @memberof InlineResponse20037LogicsTariff
     */
    conditionsByRegion?: InlineResponse20037LogicsTariffConditionsByRegion;
}


