/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject7
 */
export interface InlineObject7 {
    /**
     * Название партии
     * @type {string}
     * @memberof InlineObject7
     */
    title?: string;
    /**
     * Метод подсчта массы партии
     * @type {number}
     * @memberof InlineObject7
     */
    calculationMethod?: number;
    /**
     * Делитель объема партии
     * @type {number}
     * @memberof InlineObject7
     */
    volumeWeightDivide?: number;
    /**
     * Трек номер партии
     * @type {string}
     * @memberof InlineObject7
     */
    trackingNumber?: string;
    /**
     * Настоящая стоимость доставки
     * @type {number}
     * @memberof InlineObject7
     */
    actualShippingCost?: number;
}


