/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject106
 */
export interface InlineObject106 {
    /**
     * Поставить оценку юзеру
     * @type {number}
     * @memberof InlineObject106
     */
    rating?: number;
    /**
     * Комментарий причин изменения статуса.
     * @type {string}
     * @memberof InlineObject106
     */
    reason?: string;
    /**
     * Массив ссылок на медиафайлы.
     * @type {Array<string>}
     * @memberof InlineObject106
     */
    linksToMediaFiles?: Array<string>;
}


