/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse20057Order
 */
export interface InlineResponse20057Order {
    /**
     * id заказ.
     * @type {number}
     * @memberof InlineResponse20057Order
     */
    id?: number;
    /**
     * GUID данной записи в БД.
     * @type {string}
     * @memberof InlineResponse20057Order
     */
    _id?: string;
    /**
     * кол-во
     * @type {number}
     * @memberof InlineResponse20057Order
     */
    amount?: number;
    /**
     * Статус заказа
     * @type {number}
     * @memberof InlineResponse20057Order
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20057Order
     */
    createdAt?: string;
}


