/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject17
 */
export interface InlineObject17 {
    /**
     * GUID спека
     * @type {string}
     * @memberof InlineObject17
     */
    specId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject17
     */
    linksToMediaFiles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof InlineObject17
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject17
     */
    description?: string;
}


