/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject13
 */
export interface InlineObject13 {
    /**
     * Название склада.
     * @type {string}
     * @memberof InlineObject13
     */
    name: string;
    /**
     * Страна.
     * @type {string}
     * @memberof InlineObject13
     */
    country?: string;
    /**
     * Индекс. 5 цифр.
     * @type {string}
     * @memberof InlineObject13
     */
    zipCode?: string;
    /**
     * Штат.
     * @type {string}
     * @memberof InlineObject13
     */
    state?: string;
    /**
     * Город.
     * @type {string}
     * @memberof InlineObject13
     */
    city?: string;
    /**
     * Адрес склада.
     * @type {string}
     * @memberof InlineObject13
     */
    address?: string;
    /**
     * Цвет шрифта
     * @type {string}
     * @memberof InlineObject13
     */
    fontColor?: string;
}


