/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiV1ProductsKeepaOffers } from './api-v1-products-keepa-offers';
import { ApiV1ProductsKeepaStats } from './api-v1-products-keepa-stats';

/**
 * 
 * @export
 * @interface InlineResponse20087
 */
export interface InlineResponse20087 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20087
     */
    isRecommended?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20087
     */
    trackingSince?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20087
     */
    lastRatingUpdate?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20087
     */
    rootCategory?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof InlineResponse20087
     */
    categories?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20087
     */
    parentAsin?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20087
     */
    variationCSV?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineResponse20087
     */
    frequentlyBoughtTogether?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20087
     */
    manufacturer?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20087
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20087
     */
    productGroup?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20087
     */
    publicationDate?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20087
     */
    releaseDate?: number;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof InlineResponse20087
     */
    contributors?: Array<Array<number>>;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20087
     */
    size?: string;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse20087
     */
    salesRanks?: object;
    /**
     * 
     * @type {Array<ApiV1ProductsKeepaOffers>}
     * @memberof InlineResponse20087
     */
    offers?: Array<ApiV1ProductsKeepaOffers>;
    /**
     * 
     * @type {Array<number>}
     * @memberof InlineResponse20087
     */
    liveOffersOrder?: Array<number>;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineResponse20087
     */
    buyBoxSellerIdHistory?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20087
     */
    availabilityAmazon?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20087
     */
    newPriceIsMAP?: boolean;
    /**
     * 
     * @type {ApiV1ProductsKeepaStats}
     * @memberof InlineResponse20087
     */
    stats?: ApiV1ProductsKeepaStats;
}


