/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse2002OrderVariationTariff
 */
export interface InlineResponse2002OrderVariationTariff {
    /**
     * variationTariff _id
     * @type {string}
     * @memberof InlineResponse2002OrderVariationTariff
     */
    _id?: string;
    /**
     * Цена в юанях
     * @type {number}
     * @memberof InlineResponse2002OrderVariationTariff
     */
    pricePerKgRmb?: number;
    /**
     * Цена в долларах
     * @type {number}
     * @memberof InlineResponse2002OrderVariationTariff
     */
    pricePerKgUsd?: number;
    /**
     * id склада - склады куда отправляют 
     * @type {string}
     * @memberof InlineResponse2002OrderVariationTariff
     */
    destinationId?: string;
}


