/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiV1AdminsGetProductsByStatusCreatedBy } from './api-v1-admins-get-products-by-status-created-by';
import { ApiV1AnnouncementsMySpec } from './api-v1-announcements-my-spec';
import { InlineResponse20085RequestAnnouncement } from './inline-response20085-request-announcement';
import { InlineResponse20085RequestProduct } from './inline-response20085-request-product';

/**
 * 
 * @export
 * @interface InlineResponse20085Request
 */
export interface InlineResponse20085Request {
    /**
     * GUID заявки в базе данных.
     * @type {string}
     * @memberof InlineResponse20085Request
     */
    _id?: string;
    /**
     * Ключ заявки числом
     * @type {number}
     * @memberof InlineResponse20085Request
     */
    humanFriendlyId?: number;
    /**
     * Тип заявки.
     * @type {string}
     * @memberof InlineResponse20085Request
     */
    type?: string;
    /**
     * Приоритет заявки
     * @type {number}
     * @memberof InlineResponse20085Request
     */
    priority?: number;
    /**
     * Заявка без подтверждения
     * @type {boolean}
     * @memberof InlineResponse20085Request
     */
    withoutConfirmation?: boolean;
    /**
     * 
     * @type {InlineResponse20085RequestAnnouncement}
     * @memberof InlineResponse20085Request
     */
    announcement?: InlineResponse20085RequestAnnouncement;
    /**
     * 
     * @type {InlineResponse20085RequestProduct}
     * @memberof InlineResponse20085Request
     */
    product?: InlineResponse20085RequestProduct;
    /**
     * Сложность заявки
     * @type {number}
     * @memberof InlineResponse20085Request
     */
    taskComplexity?: number;
    /**
     * Title заявки.
     * @type {string}
     * @memberof InlineResponse20085Request
     */
    title?: string;
    /**
     * Количество предложений.
     * @type {number}
     * @memberof InlineResponse20085Request
     */
    maxAmountOfProposals?: number;
    /**
     * Время закрытия заявки.
     * @type {string}
     * @memberof InlineResponse20085Request
     */
    timeoutAt?: string;
    /**
     * Направление заявки, исходящая или входящая.
     * @type {string}
     * @memberof InlineResponse20085Request
     */
    direction?: InlineResponse20085RequestDirectionEnum;
    /**
     * 
     * @type {ApiV1AnnouncementsMySpec}
     * @memberof InlineResponse20085Request
     */
    spec?: ApiV1AnnouncementsMySpec;
    /**
     * 
     * @type {ApiV1AdminsGetProductsByStatusCreatedBy}
     * @memberof InlineResponse20085Request
     */
    createdBy?: ApiV1AdminsGetProductsByStatusCreatedBy;
    /**
     * Дата создания
     * @type {string}
     * @memberof InlineResponse20085Request
     */
    createdAt?: string;
    /**
     * Дата изменения
     * @type {string}
     * @memberof InlineResponse20085Request
     */
    updatedAt?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum InlineResponse20085RequestDirectionEnum {
    In = 'IN',
    Out = 'OUT'
}



