/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse20025LogicsTariff
 */
export interface InlineResponse20025LogicsTariff {
    /**
     * GUID тарифа
     * @type {string}
     * @memberof InlineResponse20025LogicsTariff
     */
    _id?: string;
    /**
     * Название тарифа
     * @type {string}
     * @memberof InlineResponse20025LogicsTariff
     */
    name?: string;
}


