/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse20039Rows
 */
export interface InlineResponse20039Rows {
    /**
     * GUID продукта в базе данных
     * @type {string}
     * @memberof InlineResponse20039Rows
     */
    _id?: string;
    /**
     * ASIN продукта
     * @type {string}
     * @memberof InlineResponse20039Rows
     */
    asin?: string;
    /**
     * ID магазинa для продукта
     * @type {string}
     * @memberof InlineResponse20039Rows
     */
    shopId?: string;
    /**
     * Заголовок на товар с сайта амазон.
     * @type {string}
     * @memberof InlineResponse20039Rows
     */
    amazonTitle?: string;
    /**
     * SKU введенным клиентом.
     * @type {string}
     * @memberof InlineResponse20039Rows
     */
    skuByClient?: string;
    /**
     * GUID пользователя(байера)
     * @type {string}
     * @memberof InlineResponse20039Rows
     */
    buyerId?: string;
    /**
     * Массив картинок.
     * @type {Array<string>}
     * @memberof InlineResponse20039Rows
     */
    images?: Array<string>;
}


