/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse20056Finances } from './inline-response20056-finances';
import { InlineResponse20058Products } from './inline-response20058-products';

/**
 * 
 * @export
 * @interface InlineResponse20058
 */
export interface InlineResponse20058 {
    /**
     * 
     * @type {InlineResponse20058Products}
     * @memberof InlineResponse20058
     */
    products?: InlineResponse20058Products;
    /**
     * 
     * @type {InlineResponse20056Finances}
     * @memberof InlineResponse20058
     */
    finances?: InlineResponse20056Finances;
}


