/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse20053Rows } from './inline-response20053-rows';

/**
 * 
 * @export
 * @interface InlineResponse20053
 */
export interface InlineResponse20053 {
    /**
     * Кол-во товаров
     * @type {number}
     * @memberof InlineResponse20053
     */
    count?: number;
    /**
     * Массив товаров.
     * @type {Array<InlineResponse20053Rows>}
     * @memberof InlineResponse20053
     */
    rows?: Array<InlineResponse20053Rows>;
}


