/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiV1AdminsGetProductsByStatusCreatedBy } from './api-v1-admins-get-products-by-status-created-by';

/**
 * 
 * @export
 * @interface InlineResponse20044Rows
 */
export interface InlineResponse20044Rows {
    /**
     * Guid of shop
     * @type {string}
     * @memberof InlineResponse20044Rows
     */
    _id?: string;
    /**
     * Name of shop
     * @type {string}
     * @memberof InlineResponse20044Rows
     */
    name?: string;
    /**
     * Count of shop products
     * @type {number}
     * @memberof InlineResponse20044Rows
     */
    productsCount?: number;
    /**
     * 
     * @type {Array<ApiV1AdminsGetProductsByStatusCreatedBy>}
     * @memberof InlineResponse20044Rows
     */
    shopUsers?: Array<ApiV1AdminsGetProductsByStatusCreatedBy>;
    /**
     * 
     * @type {Array<ApiV1AdminsGetProductsByStatusCreatedBy>}
     * @memberof InlineResponse20044Rows
     */
    productUsers?: Array<ApiV1AdminsGetProductsByStatusCreatedBy>;
}


