/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject31
 */
export interface InlineObject31 {
    /**
     * 
     * @type {number}
     * @memberof InlineObject31
     */
    lengthCmWarehouse?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject31
     */
    widthCmWarehouse?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject31
     */
    heightCmWarehouse?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineObject31
     */
    weighGrossKgWarehouse?: number;
    /**
     * Массив ссылок на фотографии.
     * @type {Array<string>}
     * @memberof InlineObject31
     */
    images?: Array<string>;
}


