/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse20035InventoryShop } from './inline-response20035-inventory-shop';

/**
 * Схема репорта amazon_data
 * @export
 * @interface InlineResponse20058Rows
 */
export interface InlineResponse20058Rows {
    /**
     * Гуид записи
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    _id?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    shopId?: string;
    /**
     * The asin of product
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    asin?: string;
    /**
     * The sku of product
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    sku?: string;
    /**
     * Price
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    price?: number;
    /**
     * fba_fee
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    fbaFee?: number;
    /**
     * ref_fee
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    refFee?: number;
    /**
     * image
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    image?: string;
    /**
     * Category ABC
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    categoryAbc?: string;
    /**
     * available
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    available?: number;
    /**
     * inbound
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    inbound?: number;
    /**
     * reserved
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    reserved?: number;
    /**
     * Дата обновления
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    dateUpdated?: string;
    /**
     * Время обновления
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    timeUpdated?: string;
    /**
     * organicCv
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    organicCv?: number;
    /**
     * historical_days_of_supply
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    historicalDaysOfSupply?: number;
    /**
     * estimated_storage_cost
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    estimatedStorageCost?: number;
    /**
     * estimated_aged_inventory_surcharge
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    estimatedAgedInventorySurcharge?: number;
    /**
     * age_0_to_90_days
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    age0to90Days?: number;
    /**
     * age_91_to_180_days
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    age91to180Days?: number;
    /**
     * age_181_to_270_days
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    age181to270Days?: number;
    /**
     * age_271_to_365_days
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    age271to365Days?: number;
    /**
     * age_365_plus_days
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    age365plusDays?: number;
    /**
     * storage_volume
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    storageVolume?: number;
    /**
     * low_inventory_level_fee
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    lowInventoryLevelFee?: number;
    /**
     * cog
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    cog?: number;
    /**
     * unitProfit
     * @type {number}
     * @memberof InlineResponse20058Rows
     */
    unitProfit?: number;
    /**
     * Дата создания
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    createdAt?: string;
    /**
     * Дата обновления
     * @type {string}
     * @memberof InlineResponse20058Rows
     */
    updatedAt?: string;
    /**
     * 
     * @type {InlineResponse20035InventoryShop}
     * @memberof InlineResponse20058Rows
     */
    shop?: InlineResponse20035InventoryShop;
}


