/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse20081Products } from './inline-response20081-products';

/**
 * 
 * @export
 * @interface InlineResponse20081Rows
 */
export interface InlineResponse20081Rows {
    /**
     * ID магазина.
     * @type {string}
     * @memberof InlineResponse20081Rows
     */
    _id?: string;
    /**
     * Имя магазина, у удного пользователя не может быть два магазина с одинаковыми именами.
     * @type {string}
     * @memberof InlineResponse20081Rows
     */
    name?: string;
    /**
     * 
     * @type {Array<InlineResponse20081Products>}
     * @memberof InlineResponse20081Rows
     */
    products?: Array<InlineResponse20081Products>;
}


