/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiV1AdminsGetProductsByStatusCreatedBy } from './api-v1-admins-get-products-by-status-created-by';
import { InlineResponse20042Shop } from './inline-response20042-shop';

/**
 * 
 * @export
 * @interface InlineResponse20081Product
 */
export interface InlineResponse20081Product {
    /**
     * Гуид продукта
     * @type {string}
     * @memberof InlineResponse20081Product
     */
    _id?: string;
    /**
     * ASIN продукта
     * @type {string}
     * @memberof InlineResponse20081Product
     */
    asin?: string;
    /**
     * SKU введенным клиентом.
     * @type {string}
     * @memberof InlineResponse20081Product
     */
    skuByClient?: string;
    /**
     * Массив картинок.
     * @type {Array<string>}
     * @memberof InlineResponse20081Product
     */
    images?: Array<string>;
    /**
     * 
     * @type {InlineResponse20042Shop}
     * @memberof InlineResponse20081Product
     */
    shop?: InlineResponse20042Shop;
    /**
     * Заголовок на товар с сайта амазон.
     * @type {string}
     * @memberof InlineResponse20081Product
     */
    amazonTitle?: string;
    /**
     * 
     * @type {Array<ApiV1AdminsGetProductsByStatusCreatedBy>}
     * @memberof InlineResponse20081Product
     */
    subUsers?: Array<ApiV1AdminsGetProductsByStatusCreatedBy>;
    /**
     * ID магазина продукта
     * @type {string}
     * @memberof InlineResponse20081Product
     */
    shopId?: string;
}


