/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Общая информация о пользователи
 * @export
 * @interface InlineResponse2006SubUsers
 */
export interface InlineResponse2006SubUsers {
    /**
     * GUID пользователя.
     * @type {string}
     * @memberof InlineResponse2006SubUsers
     */
    _id?: string;
    /**
     * Имя пользователя.
     * @type {string}
     * @memberof InlineResponse2006SubUsers
     */
    name?: string;
    /**
     * Рейтинг пользователя.
     * @type {number}
     * @memberof InlineResponse2006SubUsers
     */
    rating?: number;
    /**
     * Последний раз онлайн
     * @type {string}
     * @memberof InlineResponse2006SubUsers
     */
    lastSeen?: string;
    /**
     * email
     * @type {string}
     * @memberof InlineResponse2006SubUsers
     */
    email?: string;
}


