/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiV1AdminsGetProductsByStatusBoxAmounts } from './api-v1-admins-get-products-by-status-box-amounts';
import { ApiV1AdminsGetProductsByStatusCreatedBy } from './api-v1-admins-get-products-by-status-created-by';
import { ApiV1AdminsGetProductsByStatusRedFlags } from './api-v1-admins-get-products-by-status-red-flags';
import { ApiV1AdminsGetProductsByStatusSuppliers } from './api-v1-admins-get-products-by-status-suppliers';
import { ApiV1AdminsGetProductsByStatusTags } from './api-v1-admins-get-products-by-status-tags';

/**
 * 
 * @export
 * @interface InlineResponse20030Rows
 */
export interface InlineResponse20030Rows {
    /**
     * GUID продукта в базе данных
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    _id?: string;
    /**
     * ASIN продукта
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    asin?: string;
    /**
     * SKU введенным клиентом.
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    skuByClient?: string;
    /**
     * 
     * @type {Array<ApiV1AdminsGetProductsByStatusSuppliers>}
     * @memberof InlineResponse20030Rows
     */
    suppliers?: Array<ApiV1AdminsGetProductsByStatusSuppliers>;
    /**
     * 
     * @type {ApiV1AdminsGetProductsByStatusSuppliers}
     * @memberof InlineResponse20030Rows
     */
    currentSupplier?: ApiV1AdminsGetProductsByStatusSuppliers;
    /**
     * GUID поставщика в базе данных
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    currentSupplierId?: string;
    /**
     * Гуид родительского продукта
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    parentProductId?: string;
    /**
     * Имеет ли дочерние продукты данный продукт (по parentProductId)
     * @type {boolean}
     * @memberof InlineResponse20030Rows
     */
    hasChildren?: boolean;
    /**
     * Категория
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    category?: string;
    /**
     * Ссылка на этот продукт на амазоне.
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    lamazon?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    bsr?: number;
    /**
     * Признак fba
     * @type {boolean}
     * @memberof InlineResponse20030Rows
     */
    fba?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    amazon?: number;
    /**
     * Высота
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    height?: number;
    /**
     * Ширина
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    width?: number;
    /**
     * Длинна
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    length?: number;
    /**
     * Вес
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    weight?: number;
    /**
     * комиссия которую берет амазон за любой заказ - 15%
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    reffee?: number;
    /**
     * ФБА комиссия
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    fbafee?: number;
    /**
     *  Общая сумма с фба.
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    fbaamount?: number;
    /**
     * Код текущего статуса
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    status?: number;
    /**
     * Комментарии к товару.
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    icomment?: string;
    /**
     * Комментарии к товару, от клиента.
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    clientComment?: string;
    /**
     * Массив картинок.
     * @type {Array<string>}
     * @memberof InlineResponse20030Rows
     */
    images?: Array<string>;
    /**
     * Последние seo-файлы
     * @type {Array<string>}
     * @memberof InlineResponse20030Rows
     */
    latestSeoFiles?: Array<string>;
    /**
     * Цена для клиента
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    priceForClient?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    checkednotes?: string;
    /**
     * Признак isCreatedByClient
     * @type {boolean}
     * @memberof InlineResponse20030Rows
     */
    isCreatedByClient?: boolean;
    /**
     * 
     * @type {ApiV1AdminsGetProductsByStatusCreatedBy}
     * @memberof InlineResponse20030Rows
     */
    client?: ApiV1AdminsGetProductsByStatusCreatedBy;
    /**
     * Описание с сайта амазон.
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    amazonDescription?: string;
    /**
     * Данные из поля детали с сайта амазон.
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    amazonDetail?: string;
    /**
     * Заголовок на товар с сайта амазон.
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    amazonTitle?: string;
    /**
     * Материл продукта
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    material?: string;
    /**
     * Применение продукта
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    productUsage?: string;
    /**
     * chinese title?
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    chinaTitle?: string;
    /**
     * Баркод
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    barCode?: string;
    /**
     * Защита листинга (bool)
     * @type {boolean}
     * @memberof InlineResponse20030Rows
     */
    transparency?: boolean;
    /**
     * Минимальный заказ
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    minpurchase?: number;
    /**
     * Прибыль
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    profit?: number;
    /**
     * Маржа
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    margin?: number;
    /**
     * Кол-во товаров, которые находятся в пути
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    inTransfer?: number;
    /**
     * 
     * @type {ApiV1AdminsGetProductsByStatusCreatedBy}
     * @memberof InlineResponse20030Rows
     */
    createdBy?: ApiV1AdminsGetProductsByStatusCreatedBy;
    /**
     * 
     * @type {ApiV1AdminsGetProductsByStatusCreatedBy}
     * @memberof InlineResponse20030Rows
     */
    checkedBy?: ApiV1AdminsGetProductsByStatusCreatedBy;
    /**
     * Дата создания
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    createdAt?: string;
    /**
     * Дата изменения
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    updatedAt?: string;
    /**
     * Дата проверки
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    checkedAt?: string;
    /**
     * 
     * @type {ApiV1AdminsGetProductsByStatusCreatedBy}
     * @memberof InlineResponse20030Rows
     */
    buyer?: ApiV1AdminsGetProductsByStatusCreatedBy;
    /**
     * Дедлаин на на поиск поставщика байером.
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    buyerTimeoutAt?: string;
    /**
     * Комментарии к товару от байера.
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    buyersComment?: string;
    /**
     * ID магазина продукта
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    shopId?: string;
    /**
     * Савка ресечера.
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    researcherRate?: number;
    /**
     * Савка супервайзера.
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    supervisorRate?: number;
    /**
     * Дата оплаты
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    paidAt?: string;
    /**
     * Савка байера.
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    buyerRate?: number;
    /**
     * У поля на данный момент будет 5 возможных значений: 0, 10, 20, 30, 40
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    strategyStatus?: number;
    /**
     * Признак needCheckBySupervisor
     * @type {boolean}
     * @memberof InlineResponse20030Rows
     */
    needCheckBySupervisor?: boolean;
    /**
     * Сколько такого продукта находится в заказах.
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    amountInOrders?: number;
    /**
     * Сколько такого продукта находится в заказах в статусах 0, 2, 3.
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    amountInPendingOrders?: number;
    /**
     * 
     * @type {Array<ApiV1AdminsGetProductsByStatusBoxAmounts>}
     * @memberof InlineResponse20030Rows
     */
    boxAmounts?: Array<ApiV1AdminsGetProductsByStatusBoxAmounts>;
    /**
     * Флаг указывает что продукт в архиве.
     * @type {boolean}
     * @memberof InlineResponse20030Rows
     */
    archive?: boolean;
    /**
     * hsCode продукта.
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    hsCode?: string;
    /**
     * Ниша
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    niche?: string;
    /**
     * Асины
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    asins?: string;
    /**
     * Общий доход
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    totalRevenue?: string;
    /**
     * Коэффициент прибыли
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    coefficient?: string;
    /**
     * Средний доход
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    avgRevenue?: string;
    /**
     * Средний BSR
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    avgBSR?: string;
    /**
     * Средняя цена
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    avgPrice?: string;
    /**
     * Средний отзывы
     * @type {string}
     * @memberof InlineResponse20030Rows
     */
    avgReviews?: string;
    /**
     * Каков должен быть сток за 4 месяца
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    fourMonthesStock?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    stockUSA?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    reservedSum?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    sentToFbaSum?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    fbaFbmStockSum?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    ideasOnCheck?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    ideasFinished?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    ideasClosed?: number;
    /**
     * 
     * @type {Array<ApiV1AdminsGetProductsByStatusCreatedBy>}
     * @memberof InlineResponse20030Rows
     */
    subUsers?: Array<ApiV1AdminsGetProductsByStatusCreatedBy>;
    /**
     * 
     * @type {Array<ApiV1AdminsGetProductsByStatusRedFlags>}
     * @memberof InlineResponse20030Rows
     */
    redFlags?: Array<ApiV1AdminsGetProductsByStatusRedFlags>;
    /**
     * 
     * @type {Array<ApiV1AdminsGetProductsByStatusTags>}
     * @memberof InlineResponse20030Rows
     */
    tags?: Array<ApiV1AdminsGetProductsByStatusTags>;
    /**
     * 
     * @type {Array<object>}
     * @memberof InlineResponse20030Rows
     */
    productsInWarehouse?: Array<object>;
    /**
     * Кол-во идей продукта в статусе 10
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    ideasCounter?: number;
    /**
     * “sumStock”=“boxAmounts” + ”inTransfer” + ”productsInWarehouse”(“reserved” + ”fbaFbmStock” + ”sentToFba”) + “amountInOrders“ + “stockUSA“
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    sumStock?: number;
    /**
     * “purchaseQuantity”=”fourMonthesStock” - “sumStock” - меньше нуля быть не может, если отрицательное значение выставляем 0
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    purchaseQuantity?: number;
    /**
     * (amount/batchTotalCostInDollar) * sumStock
     * @type {number}
     * @memberof InlineResponse20030Rows
     */
    stockCost?: number;
}


