/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse20037PpcSalesWeeks
 */
export interface InlineResponse20037PpcSalesWeeks {
    /**
     * Гуид записи
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    _id?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    productId?: string;
    /**
     * The shop _id
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    shop?: string;
    /**
     * Гуид shop-a
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    shopId?: string;
    /**
     * asin
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    asin?: string;
    /**
     * sku
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    sku?: string;
    /**
     * period_start
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    periodStart?: string;
    /**
     * period_end
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    periodEnd?: string;
    /**
     * week
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    week?: number;
    /**
     * acos
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    acos?: number;
    /**
     * image
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    image?: string;
    /**
     * ppc_impressions
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    ppcImpressions?: number;
    /**
     * clicks
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    clicks?: number;
    /**
     * spend
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    spend?: number;
    /**
     * ppc_orders
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    ppcOrders?: number;
    /**
     * ppc_units
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    ppcUnits?: number;
    /**
     * ppc_sales
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    ppcSales?: number;
    /**
     * order_sales_cost
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    orderSalesCost?: number;
    /**
     * unit_sales_cost
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    unitSalesCost?: number;
    /**
     * organic_sessions
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    organicSessions?: number;
    /**
     * organic_orders
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    organicOrders?: number;
    /**
     * organic_units
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    organicUnits?: number;
    /**
     * organic_sales
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    organicSales?: number;
    /**
     * organic_avg_order_price
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    organicAvgOrderPrice?: number;
    /**
     * organic_avg_unit_price
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    organicAvgUnitPrice?: number;
    /**
     * impressions
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    impressions?: number;
    /**
     * sessions
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    sessions?: number;
    /**
     * ctr
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    ctr?: number;
    /**
     * orders
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    orders?: number;
    /**
     * units
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    units?: number;
    /**
     * avg_units_in_per_order
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    avgUnitsInPerOrder?: number;
    /**
     * sales
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    sales?: number;
    /**
     * avg_price_order
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    avgPriceOrder?: number;
    /**
     * avg_unit_price
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    avgUnitPrice?: number;
    /**
     * buy_box
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    buyBox?: number;
    /**
     * ppc_sale
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    ppcSale?: number;
    /**
     * organic_sale
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    organicSale?: number;
    /**
     * conversion
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    conversion?: number;
    /**
     * conversion_ppc
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    conversionPpc?: number;
    /**
     * conversion_organic
     * @type {number}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    conversionOrganic?: number;
    /**
     * date_updated
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    dateUpdated?: string;
    /**
     * createdAt
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    createdAt?: string;
    /**
     * updatedAt
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    updatedAt?: string;
    /**
     * The product _id
     * @type {string}
     * @memberof InlineResponse20037PpcSalesWeeks
     */
    product?: string;
}


