/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InlineResponse20047Rows } from './inline-response20047-rows';

/**
 * 
 * @export
 * @interface InlineResponse20047
 */
export interface InlineResponse20047 {
    /**
     * Count of rows
     * @type {number}
     * @memberof InlineResponse20047
     */
    count?: number;
    /**
     * 
     * @type {Array<InlineResponse20047Rows>}
     * @memberof InlineResponse20047
     */
    rows?: Array<InlineResponse20047Rows>;
}


