/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse20086CountProposalsByStatuses
 */
export interface InlineResponse20086CountProposalsByStatuses {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20086CountProposalsByStatuses
     */
    allProposals?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20086CountProposalsByStatuses
     */
    waitedProposals?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20086CountProposalsByStatuses
     */
    atWorkProposals?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20086CountProposalsByStatuses
     */
    verifyingProposals?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20086CountProposalsByStatuses
     */
    acceptedProposals?: number;
}


