/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiV1AdminsGetProductsByStatusCreatedBy } from './api-v1-admins-get-products-by-status-created-by';
<<<<<<< HEAD
import { ApiV1AnnouncementsMySpec } from './api-v1-announcements-my-spec';
=======
import { InlineResponse20054RequestSpec } from './inline-response20054-request-spec';
>>>>>>> pre-release
import { InlineResponse20061Proposals } from './inline-response20061-proposals';

/**
 * 
 * @export
 * @interface InlineResponse20061RequestsOnCheck
 */
export interface InlineResponse20061RequestsOnCheck {
    /**
     * Гуид заявки
     * @type {string}
     * @memberof InlineResponse20061RequestsOnCheck
     */
    _id?: string;
    /**
     * номер заявки
     * @type {number}
     * @memberof InlineResponse20061RequestsOnCheck
     */
    humanFriendlyId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20061RequestsOnCheck
     */
    title?: string;
    /**
     * Статус заявки
     * @type {string}
     * @memberof InlineResponse20061RequestsOnCheck
     */
    status?: string;
    /**
     * 
<<<<<<< HEAD
     * @type {ApiV1AnnouncementsMySpec}
     * @memberof InlineResponse20061RequestsOnCheck
     */
    spec?: ApiV1AnnouncementsMySpec;
=======
     * @type {InlineResponse20054RequestSpec}
     * @memberof InlineResponse20061RequestsOnCheck
     */
    spec?: InlineResponse20054RequestSpec;
>>>>>>> pre-release
    /**
     * 
     * @type {Array<InlineResponse20061Proposals>}
     * @memberof InlineResponse20061RequestsOnCheck
     */
    proposals?: Array<InlineResponse20061Proposals>;
    /**
     * 
     * @type {ApiV1AdminsGetProductsByStatusCreatedBy}
     * @memberof InlineResponse20061RequestsOnCheck
     */
    executor?: ApiV1AdminsGetProductsByStatusCreatedBy;
}


