/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse20085RequestAnnouncement
 */
export interface InlineResponse20085RequestAnnouncement {
    /**
     * GUID анонса
     * @type {string}
     * @memberof InlineResponse20085RequestAnnouncement
     */
    _id?: string;
    /**
     * Title анонса
     * @type {string}
     * @memberof InlineResponse20085RequestAnnouncement
     */
    title?: string;
}


