/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiV1AdminsGetProductsByStatusShop } from './api-v1-admins-get-products-by-status-shop';

/**
 * 
 * @export
 * @interface InlineResponse20042Product
 */
export interface InlineResponse20042Product {
    /**
     * Гуид продукта
     * @type {string}
     * @memberof InlineResponse20042Product
     */
    _id?: string;
    /**
     * ASIN продукта
     * @type {string}
     * @memberof InlineResponse20042Product
     */
    asin?: string;
    /**
     * SKU введенным клиентом.
     * @type {string}
     * @memberof InlineResponse20042Product
     */
    skuByClient?: string;
    /**
     * Массив картинок.
     * @type {Array<string>}
     * @memberof InlineResponse20042Product
     */
    images?: Array<string>;
    /**
     * Заголовок на товар с сайта амазон.
     * @type {string}
     * @memberof InlineResponse20042Product
     */
    amazonTitle?: string;
    /**
     * 
     * @type {ApiV1AdminsGetProductsByStatusShop}
     * @memberof InlineResponse20042Product
     */
    shop?: ApiV1AdminsGetProductsByStatusShop;
}


