/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Редактировать группу permission
 * @export
 * @interface PermissionGroupPatchDtoSchema
 */
export interface PermissionGroupPatchDtoSchema {
    /**
     * Простое название
     * @type {string}
     * @memberof PermissionGroupPatchDtoSchema
     */
    title?: string;
    /**
     * Описание permission
     * @type {string}
     * @memberof PermissionGroupPatchDtoSchema
     */
    description?: string;
    /**
     * Для фронта, чтобы хранить иерархию.
     * @type {number}
     * @memberof PermissionGroupPatchDtoSchema
     */
    hierarchy?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PermissionGroupPatchDtoSchema
     */
    permissions?: Array<string>;
}


