/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * testing the fastify swagger api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PermissionPatchDtoSchemaAllowedUrls } from './permission-patch-dto-schema-allowed-urls';

/**
 * Редактировать permission
 * @export
 * @interface PermissionPatchDtoSchema
 */
export interface PermissionPatchDtoSchema {
    /**
     * Простое название
     * @type {string}
     * @memberof PermissionPatchDtoSchema
     */
    title?: string;
    /**
     * описание permission
     * @type {string}
     * @memberof PermissionPatchDtoSchema
     */
    description?: string;
    /**
     * Массив доступных url
     * @type {Array<PermissionPatchDtoSchemaAllowedUrls>}
     * @memberof PermissionPatchDtoSchema
     */
    allowedUrls?: Array<PermissionPatchDtoSchemaAllowedUrls>;
    /**
     * Для фронта, чтобы хранить иерархию.
     * @type {number}
     * @memberof PermissionPatchDtoSchema
     */
    hierarchy?: number;
    /**
     * Роль для которого данный permission
     * @type {number}
     * @memberof PermissionPatchDtoSchema
     */
    role?: number;
}


