import { throttle } from '@utils/throttle'

import { ActionButtonsCellProps } from './action-buttons-cell.type'

export const getButtonActionsConfig = (props: ActionButtonsCellProps) => [
  {
    dropdown: props.firstDropdown,
    showButton: props.showFirst,
    danger: props.firstDanger,
    ghost: props.firstGhost,
    icon: props.firstIcon,
    iconPosition: props.firstIconPosition,
    loading: props.firstLoading,
    shape: props.firstShape,
    size: props.firstSize,
    type: props.firstType,
    content: props.firstContent,
    disabled: props.firstDisabled,
    description: props.firstDescription,
    onClick: throttle(props.onClickFirst),
    onClickEdit: props.onClickEditFirst ? throttle(props.onClickEditFirst) : undefined,
    onClickRemove: props.onClickRemoveFirst ? throttle(props.onClickRemoveFirst) : undefined,
    onClickPrint: props.onClickPrintFirst ? throttle(props.onClickPrintFirst) : undefined,
  },
  {
    dropdown: props.secondDropdown,
    showButton: props.showSecond,
    danger: props.secondDanger,
    ghost: props.secondGhost,
    icon: props.secondIcon,
    iconPosition: props.secondIconPosition,
    loading: props.secondLoading,
    shape: props.secondShape,
    size: props.secondSize,
    type: props.secondType,
    content: props.secondContent,
    disabled: props.secondDisabled,
    description: props.secondDescription,
    onClick: throttle(props.onClickSecond),
    onClickEdit: props.onClickEditSecond ? throttle(props.onClickEditSecond) : undefined,
    onClickRemove: props.onClickRemoveSecond ? throttle(props.onClickRemoveSecond) : undefined,
    onClickPrint: props.onClickPrintSecond ? throttle(props.onClickPrintSecond) : undefined,
  },
  {
    dropdown: props.thirdDropdown,
    showButton: props.showThird,
    danger: props.thirdDanger,
    ghost: props.thirdGhost,
    icon: props.thirdIcon,
    iconPosition: props.thirdIconPosition,
    loading: props.thirdLoading,
    shape: props.thirdShape,
    size: props.thirdSize,
    type: props.thirdType,
    content: props.thirdContent,
    disabled: props.thirdDisabled,
    description: props.thirdDescription,
    onClick: throttle(props.onClickThird),
    onClickEdit: props.onClickEditThird ? throttle(props.onClickEditThird) : undefined,
    onClickRemove: props.onClickRemoveThird ? throttle(props.onClickRemoveThird) : undefined,
    onClickPrint: props.onClickPrintThird ? throttle(props.onClickPrintThird) : undefined,
  },
]
