import { throttle } from '@utils/throttle'

import { ActionButtonsCellProps } from './action-buttons-cell.type'

export const getButtonActionsConfig = (props: ActionButtonsCellProps) => [
  {
    dropdown: props.firstDropdown,
    showButton: props.showFirst,
    showEdit: props.showFirstEdit,
    showRemove: props.showFirstRemove,
    danger: props.firstDanger,
    ghost: props.firstGhost,
    icon: props.firstIcon,
    iconPosition: props.firstIconPosition,
    loading: props.firstLoading,
    shape: props.firstShape,
    size: props.firstSize,
    type: props.firstType,
    content: props.firstContent,
    disabled: props.firstDisabled,
    description: props.firstDescription,
    onClick: throttle(props.onClickFirst),
    onClickEdit: throttle(props.onClickEditFirst),
    onClickRemove: throttle(props.onClickRemoveFirst),
  },
  {
    dropdown: props.secondDropdown,
    showButton: props.showSecond,
    showEdit: props.showSecondEdit,
    showRemove: props.showSecondRemove,
    danger: props.secondDanger,
    ghost: props.secondGhost,
    icon: props.secondIcon,
    iconPosition: props.secondIconPosition,
    loading: props.secondLoading,
    shape: props.secondShape,
    size: props.secondSize,
    type: props.secondType,
    content: props.secondContent,
    disabled: props.secondDisabled,
    description: props.secondDescription,
    onClick: throttle(props.onClickSecond),
    onClickEdit: throttle(props.onClickEditSecond),
    onClickRemove: throttle(props.onClickRemoveSecond),
  },
  {
    dropdown: props.thirdDropdown,
    showButton: props.showThird,
    showEdit: props.showThirdEdit,
    showRemove: props.showThirdRemove,
    danger: props.thirdDanger,
    ghost: props.thirdGhost,
    icon: props.thirdIcon,
    iconPosition: props.thirdIconPosition,
    loading: props.thirdLoading,
    shape: props.thirdShape,
    size: props.thirdSize,
    type: props.thirdType,
    content: props.thirdContent,
    disabled: props.thirdDisabled,
    description: props.thirdDescription,
    onClick: throttle(props.onClickThird),
    onClickEdit: throttle(props.onClickEditThird),
    onClickRemove: throttle(props.onClickRemoveThird),
  },
]
