export const filtersFields = [
  'humanFriendlyId',
  'updatedAt',
  'status',
  'title',
  'typeTask',
  'price',
  'timeoutAt',
  'asin',
  'skuByClient',
  'amazonTitle',
  'createdBy',
  'subUsers',
  'priceAmazon',
  'withoutConfirmation',
  'taskComplexity',
]
