export enum ChatMessageType {
  'CREATED_NEW_PROPOSAL_PROPOSAL_DESCRIPTION' = 'CREATED_NEW_PROPOSAL_PROPOSAL_DESCRIPTION',
  'CREATED_NEW_PROPOSAL_REQUEST_DESCRIPTION' = 'CREATED_NEW_PROPOSAL_REQUEST_DESCRIPTION',
  'PROPOSAL_STATUS_CHANGED' = 'PROPOSAL_STATUS_CHANGED',
  'PROPOSAL_RESULT_EDITED' = 'PROPOSAL_RESULT_EDITED',
  'CREATED_NEW_BLOGGER_PROPOSAL' = 'CREATED_NEW_BLOGGER_PROPOSAL',
  'CREATED_NEW_DESIGNER_PROPOSAL' = 'CREATED_NEW_DESIGNER_PROPOSAL',
  'BLOGGER_PROPOSAL_RESULT_EDITED' = 'BLOGGER_PROPOSAL_RESULT_EDITED',
  'DESIGNER_PROPOSAL_RESULT_EDITED' = 'DESIGNER_PROPOSAL_RESULT_EDITED',
  'PROPOSAL_EDITED' = 'PROPOSAL_EDITED',
  'SYSTEM' = 'system:default',
  'USER' = 'user:default',
}
