export const columnnsKeys = {
  supervisor: {},
  buyer: {
    MY_ORDERS_STATUS: 'MY_ORDERS_STATUS',
    ORDERS_PRIORITY: 'ORDERS_PRIORITY',
    MY_PRODUCTS_STATUS: 'MY_PRODUCTS_STATUS',
  },
  storekeeper: {},
  client: {
    WAREHOUSE_IN_STOCK_SHOPS: 'WAREHOUSE_IN_STOCK_SHOPS',
    WAREHOUSE_IN_STOCK_IS_FORMED: 'WAREHOUSE_IN_STOCK_IS_FORMED',
    WAREHOUSE_ID: 'WAREHOUSE_ID',
    ORDERS_STATUS: 'ORDERS_STATUS',

    MY_ORDERS_PRIORITY: 'MY_ORDERS_PRIORITY',

    FREELANCE_REQUEST_TYPE: 'FREELANCE_REQUEST_TYPE',
    FREELANCE_REQUEST_TYPE_MY: 'FREELANCE_REQUEST_TYPE_MY',
    FREELANCE_MY_REQUESTS: 'FREELANCE_MY_REQUESTS',
    FREELANCE_REQUESTS_CREATED_BY: 'FREELANCE_REQUESTS_CREATED_BY',
    FREELANCE_REQUESTS_PRIORITY: 'FREELANCE_REQUESTS_PRIORITY',

    WAREHOUSE_IN_STOCK_PRODUCT: 'WAREHOUSE_IN_STOCK_PRODUCT',
    WAREHOUSE_IN_STOCK_ORDER_IDS_ITEMS: 'WAREHOUSE_IN_STOCK_ORDER_IDS_ITEMS',
    WAREHOUSE_IN_STOCK_DESTINATION: 'WAREHOUSE_IN_STOCK_DESTINATION',

    INVENTORY_PURCHASE_QUANTITY: 'INVENTORY_PURCHASE_QUANTITY',
    INVENTORY_PRODUCT: 'INVENTORY_PRODUCT',
    INVENTORY_SHOPS: 'INVENTORY_SHOPS',
    INVENTORY_STRATEGY_STATUS: 'INVENTORY_STRATEGY_STATUS',
    INVENTORY_STATUS: 'INVENTORY_STATUS',
    INVENTORY_IN_STOCK: 'INVENTORY_IN_STOCK',
    INVENTORY_BARCODE: 'INVENTORY_BARCODE',

    FREELANCER_REQUEST_LISTING: 'FREELANCER_REQUEST_LISTING',
  },
  researcher: {},
  freelancer: {
    FREELANCE_REQUESTS_CONFIRMATION: 'FREELANCE_REQUESTS_CONFIRMATION',
  },

  shared: {
    DATE: 'DATE',
    QUANTITY: 'QUANTITY',
    STRING: 'STRING',
    PRODUCT_ORDERS_STATUS: 'PRODUCT_ORDERS_STATUS',
    BOXES_STATUS: 'BOXES_STATUS',
    OBJECT: 'OBJECT',
    MY_REQUESTS_ORDERS_STATUS: 'MY_REQUESTS_ORDERS_STATUS',
    PAYMENTS: 'PAYMENTS',
    RED_FLAGS: 'RED_FLAGS',
  },
}
