export enum EntityType {
  PRODUCT = 'PRODUCT',
  ORDER = 'ORDER',
  BOX = 'BOX',
  REQUEST_PROPOSAL_CUSTOM = 'REQUEST-PROPOSAL-CUSTOM',
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  FINE = 'FINE',
}
