import { action, observable } from 'mobx'

export const observerConfig = {
  groupPermissions: observable,
  singlePermissions: observable,
  newPermissionIds: observable,
  tabIndex: observable,
  permissionIdToRemove: observable,
  exportPermissions: observable,
  showAddOrEditGroupPermissionModal: observable,
  showAddOrEditSinglePermissionModal: observable,
  showConfirmModal: observable,
  addOrEditPermissionSettings: observable,

  onChangeTabIndex: action.bound,
  createPermission: action.bound,
  onCreateGroupPermission: action.bound,
  updateSinglePermission: action.bound,
  updateGroupPermission: action.bound,
  removeSinglePermission: action.bound,
  removeGroupPermission: action.bound,
  onSubmitCreateSinglePermission: action.bound,
  onSubmitCreateGroupPermission: action.bound,
  onSubmitUpdateSinglePermission: action.bound,
  onSubmitUpdateGroupPermission: action.bound,
  onClickAddBtn: action.bound,
  onClickEditBtn: action.bound,
  onClickCancelBtn: action.bound,
  onClickRemoveBtn: action.bound,
  cancelTheOrder: action.bound,
  onClickExportPermissions: action.bound,
  onClickImportPermissions: action.bound,
  getGroupPermissions: action.bound,
  getSinglePermissions: action.bound,
}
