export enum TabLabels {
  MAIN = 'MAIN',
  FREELANCE = 'FREELANCE',
  SUPPLIER_SEARCH = 'SUPPLIER SEARCH',
  ORDERS = 'ORDERS',
  DESTINATIONS = 'DESTINATIONS',
  RED_FLAGS = 'RED FLAGS',
  PAYMENT_METHODS = 'PAYMENT METHODS',
  COUNTRIES = 'COUNTRIES',
  CATEGORIES = 'CATEGORIES',
  TAGS = 'TAGS',
  LAUNCHES_REPORTS = 'LAUNCHES REPORTS',
  SHUTDOWN = 'SHUTDOWN',
}
